### PR TITLE
Update Raphael V2.2.7 to V2.2.8

### PR DESCRIPTION
**Pull request by ayumihamsaki2**
Update Raphael V2.2.7 to V2.2.8 shouldn't be a problem to update to October as as minor semantic version update.

Side note: The V2.2.7 was dated two years ago and V2.2.8 this year, as many features have been updated to the internet this new version brings some useful features and upgrades to October CMS.

ref: https://github.com/octobercms/october/issues/3867

### CODE REVIEW

**Comment by ayumihamsaki2** [comment]
Patch File: https://github.com/ayumihamsaki/patches/blob/master/raphael/0001-Update-Raphael-V2.2.7-to-V2.2.8.patch

**Comment by ayumihamsaki2** [comment]
@w20k If you got any free time, would you like to test this ? Thanks in advance!

**Comment by LukeTowers** [comment]
@ayumihamsaki the difference between the two versions in terms of the actual code is quite dramatic, it looks like it's now some sort of compiled webpack crap? Is there an option without that mess?

**Comment by ayumihamsaki** [comment]
@LukeTowers Yah I hate Webpack as well makes javascript files way too big in size! I had a look for a none-webpack version and they are all webpack versions now.

The only choices on V2.2.8 are:

- `raphael.min.js` (includes `eve` and it's minified)
- `raphael.js` (includes `eve` and it's not minified)
- `raphael.no-deps.js` (doesn't include `eve` it's not minified)
- `raphael.no-deps.min.js` (doesn't include `eve` it's minified)

*All four versions are bundled webpack.

I took the following version (because we use `Eve`):

- `raphael.js` (includes `eve` and it's not minified)

---

Not sure what to do - to get you a non-webpack version though.

**Comment by ayumihamsaki** [comment]
Side note: they were using webpack V4 to compile this version.

**Comment by LukeTowers** [comment]
What exactly do we gain by upgrading?

**Comment by ayumihamsaki** [comment]
V2.2.8

- Downgraded qunit to v1 to make tests work again
- Updated webpack to build dist
- Updated supportsTouch query from modernizr [#1084](https://github.com/DmitryBaranovskiy/raphael/pull/1084) (**possible improvement to october with touchscreens**)
- Fix drag offsets passed to "drag.start" from touch drags in elproto.drag [#1101](https://github.com/DmitryBaranovskiy/raphael/pull/1101)  (**possible improvement to october with touchscreens**)
- Fix memory leak in Element.removeData() [#1077](https://github.com/DmitryBaranovskiy/raphael/pull/1077)  (**possible bug fix for october cms**)
- Adding react-raphael to related projects [#1072](https://github.com/DmitryBaranovskiy/raphael/issues/1072)
- Added icons back to raphael's website
- Updated version in banner and raphael's website
- Updated site refs to https

This is my guess.

**Comment by LukeTowers** [comment]
Hmm. What do you think about manually porting only the relevant fixes over?

**Comment by ayumihamsaki** [comment]
I'm thinking this version and all the future versions they plan to use webpack now. Looking at the code file it is pure garage to bug fix for october. The question comes to mind do we need to bug fix this file or will the errors be in the october files instead?

I don't mind leaving this PR open and not adding it to October, this package related to things like the scoreboard see here: https://octobercms.com/docs/ui/scoreboard

Right now I don't see any major errors or issues with it and I have lots of custom plugins using these things everyday! If there was a big issue I would have filed it.

So personally I think just leave this pr open and decide at a later date. The jQuery [V3.4.0](https://github.com/octobercms/october/pull/4259) that is quite important as it has a major security fix and quite a few updates to some things needed for october. I will add that list to that pr now for ref.

**Comment by LukeTowers** [comment]
I'll close this PR for now, we can look at making any fixes if they ever come up as issues here.

**Pull request closed without merging**
