### PR TITLE
Fix Sidebar and File Column bar in the code editor section

### PR DESCRIPTION
**Pull request by ayumihamasaki2**
re-complied from pr https://github.com/octobercms/october/pull/4038

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
See github Issue: #4005

**Comment by LukeTowers** [comment]
@ayumihamsaki you need to pull in the latest dev branch and compile the CSS again. Your current version is missing the no_icons navbar mode.

**Comment by ayumihamsaki** [comment]
Quick question, what compiler do you use ? Are there any Gulp files I can use ?

**Comment by w20k** [comment]
Don't think there is something like that right now @ayumihamsaki .

**Comment by ayumihamsaki** [comment]
Would it be a good idea to add one ? Something for the `compiler` and `testing`. Just create an extra folder in this repo and store them in and then it might make things easier with regards to this subject and also standardize things.

**Comment by w20k** [comment]
I don't think that util.gulp for this single use case (though you've got a point) is a good idea.
It would be better to create a proper builder process for JS files, and I'm not a big fan of gulp, If you ask me 😄

**Comment by LukeTowers** [comment]
@ayumihamsaki the built in OctoberCMS asset compiler: `php artisan october:util compile less`

**Comment by ayumihamasaki2** [comment]
Need to close this Github is refusing for me to push anything? Will open a new pr.

**Comment by ayumihamsaki** [comment]
moved to here: https://github.com/octobercms/october/pull/4293

**Pull request closed without merging**
