### PR TITLE
Add extra features to menus

### PR DESCRIPTION
**Pull request by summercms**
Here's an example:

```php
    public function registerNavigation()
    {
        return [
            'example' => [
                'label'       => 'Title',
                'url'         => Backend::url('acme/example/start'),
                'icon'        => 'oc-smile',
                'iconSvg'     => 'plugins/acme/example/assets/img/icon.svg',
                'permissions' => ['acme.example.*'],
                'order'       => 10,
                'keywords'    => ['translate', 'content', 'language'],
                'description' => 'Enables multi-lingual websites and translate website contents',

                'sideMenu' => [
                    'one' => [
                        'label'       => 'Title 1',
                        'iconSvg'     => 'plugins/acme/example/assets/img/icon1.svg',
                        'url'         => Backend::url('acme/example/one'),
                        'permissions' => ['acme.example.one'],
                        'keywords'    => ['translate', 'locale', 'prefixes'],
                        'description' => 'Adds locale route prefixes.',
                        'group'       => 'translate',
                        'order'       => 20,
                    ],
                    'two' => [
                        'label'       => 'Title 2',
                        'iconSvg'     => 'plugins/acme/example/assets/img/icon2.svg',
                        'url'         => Backend::url('acme/example/two'),
                        'permissions' => ['acme.example.two'],
                        'keywords'    => ['translate', 'tabs'],
                        'description' => 'Adds translatable tabs.',
                        'group'       => 'translate',
                        'order'       => 30,
                    ]
                ]
            ]
        ];
    }
```

### Targeted Plugin Recommendations

See screenshot of current setup:

image

The list of plugins is pretty poor and NOT TARGETED! By adding `keywords` to plugin menus we can now give a more targeted list of recommendations based off what the end-user has previous downloaded and comparing it to related `keywords`.

### Search Side Menus

Again by adding `keywords` we can search for the exact sub-menu page.

### Sub-menu groups

Currently this feature is setup only in the settings page and not for the rest of the cms, below is an example screenshot:

image

Above: Three entries grouped under the heading **SYSTEM**.

By adding `group` we can group several sub-menu entries under a single header. A useful feature for developers to organize menu entries better.

### Descriptions

Currently this feature is setup only in the settings page and not for the rest of the cms, below is an example screenshot:

image

By adding `description` we can give the end-users a bit more information about the menu option.

### Other examples

Could go on and on,... but hopefully I pushed my case across to add these extra properties to the api's.

### Testing

I tested the attached code in v1.1.1 and saw it working through various api's listed in the `NavigationManager`, I tested the rest of the cms and saw no conflicts, I tested a working menu fine with these new properties and I tested other menu's that don't contain these properties - no conflicts were found.

### This pr also fixes these issues

- https://github.com/octobercms/october/issues/5214 (requested to add `group` property).

---

Fingers crossed to get added - hard to please all the admins 💯 

Maybe this will help:

image

### CODE REVIEW

**Comment by ayumi-cloud** [comment]
This pr also fixes the issue: https://github.com/octobercms/october/issues/5214

**Comment by LukeTowers** [comment]
> The list of plugins is pretty poor and NOT TARGETED! By adding keywords to plugin menus we can now give a more targeted list of recommendations based off what the end-user has previous downloaded and comparing it to related keywords.

I don't think this is necessarily an improvement, you'd end up with recommendations for plugins that do things that the user already has plugins for, not sure the benefit in that.

**Comment by summercms** [comment]
It's hard to say as I don't want to get into great details about all the use cases!

Long story short, we expanded the backend with a machine learning api and use the `keywords` to connect up to a search widget, that can send users to a sub-menu level.

Plus the menu's we totally re-designed and added loads of new features, which are all totally customizable to the end-user.

I basically just wanted to bridge the gap between the work we're doing behind the scenes and with October. I'm reluctant to show live examples, though it's all working we keep adding and adjusting things.

This pr is more for developers that want to customize October and not just use the standard out of the box features. What I mean by that is a developer can create a plugin and use the normal sidebar menu, or they can create a custom sidebar plus use the extra features found in this pr.

Sorry to be cryptic!

p.s. Thanks to bennothommo for fixing the github actions 👍

**Comment by LukeTowers** [comment]
@ayumi-cloud I think the actual fix that's needed then is to allow the MenuItem classes to support arbitrary properties so we're not continually adding properties for people's specific use cases, they can just add them themselves.

**Comment by summercms** [comment]
That sounds like the best solution! Should I open a new github issue or add it to the open issue here? #5214

**Comment by LukeTowers** [comment]
Closing in favour of https://github.com/octobercms/october/issues/5214

**Pull request closed without merging**
