### PR TITLE
Fixes issue with tabs height

### PR DESCRIPTION
**Pull request by ariponce**
Fixes issue where tabs content height makes tabs to vary their position on the page (i.e: when having a short content,  the tab is pushed to the bottom, and if the next tab has a long content, it's pushed up again)

### CODE REVIEW

**Comment by daftspunk** [comment]
Can you give me some sample code that demonstrates the problem?

**Comment by ariponce** [comment]
Here's a screenshot showing the problem



The code on the view:
```php
<?php Block::put('form-contents') ?>
    <?= $this->formRenderOutsideFields() ?>
    <?= $this->formRenderPrimaryTabs() ?>
<?php Block::endPut() ?>

<?php Block::put('form-sidebar') ?>
    <div class="hide-tabs"><?= $this->formRenderSecondaryTabs() ?></div>
<?php Block::endPut() ?>

<?php Block::put('body') ?>
    <?= Form::open(['class'=>'layout stretch']) ?>
    <?= $this->makeLayout('form-with-sidebar') ?>
    <?= Form::close() ?>
<?php Block::endPut() ?>
```

**Comment by jamiegrand** [comment]
+1

**Comment by daftspunk** [comment]
The proposed PR breaks the layout system (the buttons no longer sit at the bottom of the screen).

You need to tell the layout which container should stretch like so:

```
<?php Block::put('form-contents') ?>
    <div class="layout-row min-size">
        <?= $this->formRenderOutsideFields() ?>
    </div>
    <div class="layout-row">
        <?= $this->formRenderPrimaryTabs() ?>
    </div>
<?php Block::endPut() ?>

<?php Block::put('form-sidebar') ?>
    <div class="hide-tabs"><?= $this->formRenderSecondaryTabs() ?></div>
<?php Block::endPut() ?>

<?php Block::put('body') ?>
    <?= Form::open(['class'=>'layout stretch']) ?>
    <?= $this->makeLayout('form-with-sidebar') ?>
    <?= Form::close() ?>
<?php Block::endPut() ?>
```

**Pull request closed without merging**
