### PR TITLE
 Added New Resposive Tabs

### PR DESCRIPTION
**Pull request by ayumihamsaki**
Updated Color Scheme to Match rest of October's Backend, see github issue: https://github.com/octobercms/october/issues/3856

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Ignore these four commits:

jsdiff Update  - cc5da21
Updated Dropzone.js  - 28256be
Updated jCrop (2013) v0.9.12 - (2018) v0.9.15  - 28f6973
Updated Raphaël and Eve JS Library  - 5355209

They belong to PR found here: https://github.com/octobercms/october/pull/3872

My github got all screwed up.

**Comment by amdad** [comment]
image

**Comment by LukeTowers** [comment]
@ayumihamsaki you'll need to split them up, can't merge this one if it has the other commits

**Comment by w20k** [comment]
Agree with @LukeTowers.
@ayumihamsaki, it's easier to test in separate PR's, if something is not working :) It's a bit pain, But, like they say: "no pain - no gain" :D

**Comment by ayumihamsaki** [comment]
@LukeTowers Going to close this, have created a Fixed PR see here: https://github.com/octobercms/october/pull/3877

Sorry about this, I have now switched over to Sublime Merge - much better software!

**Pull request closed without merging**
