### PR TITLE
Replaced short open tags

### PR DESCRIPTION
**Pull request by mariusvw**
Replaced short open tags due compatibility

### CODE REVIEW

**Comment by daftspunk** [comment]
Can you explain what this is not compatible with? <?= $var ?> is fully supported in PHP 5.4 and above.

**Comment by mariusvw** [comment]
On some servers short open tags are disabled.

This results that the installation script (and CMS) crash on short open tags.

After replacing all those it works fine.

**Comment by NemoD503** [comment]
I think short open tags is BETTER in that case.

**Comment by mariusvw** [comment]
I believe it can be better, but not every person has the ability to enable them on the server they use for hosting.

**Comment by daftspunk** [comment]
AFAIK <?= $var ?> is not considered a short tag

<? echo $var ?> is an example of a short tag.

What version of PHP are you using @mariusvw ?

**Comment by mariusvw** [comment]
I'm running version 5.5.x

**Comment by daftspunk** [comment]
> Starting with PHP 5.4, short echo tag <?= is always recognized and valid, regardless of the short_open_tag setting.

Source: http://php.net/manual/en/language.basic-syntax.phpmode.php

**Pull request closed without merging**
