### PR TITLE
CONTRIBUTING.md October Name Consistentcy

### PR DESCRIPTION
**Pull request by sjclark**

### CODE REVIEW

**Comment by munxar** [comment]
For SEO reasons I would NOT name it October. Please keep it OctoberCMS.

**Comment by sjclark** [comment]
Even though the entirety of README.md has been altered to read **October**?

**Comment by sjclark** [comment]
Also SEO is surely a rather secondary consideration for project contributor documentation on github?

**Comment by LukeTowers** [comment]
@sjclark Thanks for your interest in contributing! However, I don't see a good enough reason for this change to merge it.

If you're still interested in contributing, there are plenty of open issues that it would be very helpful if you could attempt to replicate the issues and then provide more details on what the problem is: https://github.com/octobercms/october/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20sort%3Aupdated-desc%20label%3A%22Type%3A%20Unconfirmed%20Bug%22%20

**Pull request closed without merging**
