### PR TITLE
Alter `reserved` column to nullable when rolling back migration

### PR DESCRIPTION
**Pull request by kuloed**
We should add column `reserved` to nullable to prevent this error,
```General error: 1 Cannot add a NOT NULL column with default value NULL (SQL: alter table "jobs" add column "reserved" integer not null)```

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why is this required? I have no idea what bug is being solved from your brief description, please explain in more detail.

**Comment by kuloed** [comment]
if we already have some data in jobs table, we cannot alter the table to add 'reserved' not null column. so the command will throw the exeption i said before.

**Comment by LukeTowers** [comment]
That still doesn't tell me exactly what you are doing that is causing this bug and why it is something that needs to happen to the project as a whole instead of a just specific to you thing.

**Comment by kuloed** [comment]
like when i'm using october as testing application, and add some jobs queue, then after i'm finished i run october:down to reset october's table. If you see this is not problem then we can close this.

**Comment by LukeTowers** [comment]
So does october throw an error running `october down` when there is content in the jobs table?

**Pull request closed without merging**
