### PR TITLE
Fix Sidebar and File Column bar in the code editor section

### PR DESCRIPTION
**Pull request by ayumihamasaki2**
Re-complied as per luke spec, github giving me a big headache on this will force it through the console (so many things don't wont now every since Microsoft bought it).

See github Issue: #4005

### CODE REVIEW

**Comment by ayumihamasaki2** [comment]
I give up! I Did exactly what Luke said and still problems!

> you need to pull in the latest dev branch and compile the CSS again.

I used the dev branch and complied using: `php artisan october:util compile less`

**Comment by w20k** [comment]
@ayumihamasaki2 do you have library dev branch as well?

**Comment by ayumihamsaki** [comment]
> do you have library dev branch as well?

Yah I used that for this.

**Comment by w20k** [comment]
@ayumihamsaki will look at this matter on weekends probably. 
I'm not yet sure it's a good idea to go for 'vh', because we still need to support IE11/IEmobile.

**Comment by PubliAlex** [comment]
You should forgot IE and use flexbox and vw / vh, it's game changer

**Comment by w20k** [comment]
I don't think we have that kind of freedom here @PubliAlex.

**Comment by ayumihamsaki** [comment]
This is probably a good time to bring this up, I have been meaning to ask you w20k and luketowers about this. Windows have said that Windows 7 will no longer have any support by the end of this year and that all windows users switch over to using windows 10 between now and the end of this year.

What that means is basically IE11 is a dead browser that works on windows 7 and not on windows 10 which uses the evergreen browser Edge (currently on version 18).

So I have been wondering this week about October CMS role with regards to IE11 Browser. There must be a time where support will get dropped in the near future. Just makes no sense to keep trying to support a dead browser which usage score is so low now in the wild.

Anyway, tag me when you have had time to look into this and I will try and update the pr.

**Comment by ayumihamsaki** [comment]
@w20k Had a quick think, got two links for you!

List of Modernizr Polyfills: https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills

If you search for `vw` and `vh` you will see two Polyfills listed, see here:

https://github.com/saabi/vminpoly

Makes `vw` and `vh` work in IE 5.5+

**Comment by LukeTowers** [comment]
@ayumihamsaki I don't see us dropping support for IE 11 for a while. It's something that can happen eventually, but for now there are people that both use October and IE11 so support is not going to get dropped just yet. Perhaps in a few years.

**Comment by ayumihamsaki** [comment]
@LukeTowers fair enough, what do you think about adding one of the polyfills to this pr?

**Comment by ayumihamsaki** [comment]
@LukeTowers fair enough, what do you think about adding one of the polyfills to this pr?

Code example: https://github.com/ayumihamsaki/vw-vh-polyfill/blob/master/vw-vh-polyfill.js

**Comment by ayumihamsaki** [comment]
@LukeTowers fair enough, what do you think about adding one of the polyfills to this pr?

Code example: https://github.com/ayumihamsaki/vw-vh-polyfill/blob/master/vw-vh-polyfill.js

---

Or maybe another way is to add the following modules to Moderizr:

- CSS vh unit
- CSS vw unit
- CSS vmax unit
- CSS vmin unit

As pre PR: https://github.com/octobercms/october/pull/4316

**Comment by ayumihamsaki** [comment]
@LukeTowers fair enough, what do you think about adding one of the polyfills to this pr?

Code example: https://github.com/ayumihamsaki/vw-vh-polyfill/blob/master/vw-vh-polyfill.js

---

Or maybe another way is to add the following modules to Modernizr:

- CSS vh unit
- CSS vw unit
- CSS vmax unit
- CSS vmin unit

As pre PR: https://github.com/octobercms/october/pull/4316

**Comment by ayumihamsaki** [comment]
Had a quick think and will update Modernizr, it is the easiest way to sort this out and allows dynamic updates of the polyfill by Modernizr, also this functionally can help other PR's and Issues, I'm thinking that issue with the textarea stretch function could also benefit from this update as well.

**Comment by ayumihamsaki** [comment]
Had a quick think and will update Modernizr, it is the easiest way to sort this out and allows dynamic updates of the polyfill by Modernizr, also this functionally can help other PR's and Issues, I'm thinking that issue with the textarea stretch function could also benefit from this update as well. 

Will update the pr and link to all the related pr's and issues.

**Comment by ayumihamsaki** [comment]
Have updated the Modernizr PR to allow support `vw` and `vh` for this pr, see commit: https://github.com/octobercms/october/pull/4316/commits/5e5f19381457d5c9990863353db118753aafdde5

**Comment by ayumihamsaki** [comment]
Will try to merge this into the pr I am writing for this issue: https://github.com/octobercms/october/issues/4437

(As I am trying to re-code October to using flexbox now)

**Comment by ayumihamasaki2** [comment]
Going to close this pr. I've coded a better solution today that fixes this issue, without the need of javascript and gives a much better result using flexbox, I've already merged the code into the Add 3 and 4 column support in backend  pr. So best to close this.

**Comment by PubliAlex** [comment]
Very excited to see that new UI, especially more columns support in backend.

**Pull request closed without merging**
