### PR TITLE
Update jquery.isotope library from v1.5.26 to v3.0.6

### PR DESCRIPTION
**Pull request by ayumihamsaki2**
Update jquery.isotope library from v1.5.26 to v3.0.6. I could not find any special instructions to update from V1 to V3.

IE8 and 9 support has been dropped; should not be a problem because global usage for those two are at zero now.

This update is for github issue: https://github.com/octobercms/october/issues/3958

@w20k if you got any time would you like to run some tests on this please and thank you for all your help.

### CODE REVIEW

**Comment by ayumihamsaki2** [comment]
I need to also ref this github issue: https://github.com/octobercms/october/issues/3867

**Comment by ayumihamsaki** [comment]
Added Patch for Testing found here: https://github.com/ayumihamsaki/patches/blob/master/isotope/0001-added-to-create-patch.patch

**Comment by w20k** [comment]
@ayumihamsaki, cloned himself 👍 Double work! Ooouu....no)))

Add it to my 'Weekends todo list' 😉

**Comment by w20k** [comment]
Couldn't find any problems with the new Isotope.js version. Works faster and smoother. Refreshing and resizing seems much better in the updated version.

_Status_: **Done**

**Pull request merged**
