### PR TITLE
Revert of 'loader.less', based on the issue #3792

### PR DESCRIPTION
**Pull request by w20k**
Fix for #3792 , revert for PR #3394 

screenshot 2018-10-03 at 14 39 17

### CODE REVIEW

**Comment by LukeTowers** [comment]
@w20k could you revert https://github.com/octobercms/october/commit/5ee8ee09170fa52cd6bb5dbb2416345aeea186e5 as well?

**Comment by w20k** [comment]
@LukeTowers - easy peasy ;)

**Comment by LukeTowers** [comment]
@w20k could you run `php artisan october:util compile less` as well and commit the compiled file?

**Comment by w20k** [comment]
@LukeTowers - done ;)

**Comment by LukeTowers** [comment]
Thanks @w20k :)

**Pull request merged**
