### PR TITLE
Ability to sync data for *Many relations on Saving Form.

### PR DESCRIPTION
**Pull request by Upperfoot**
Fixes: Ability to sync data for *Many relations on Saving Form.

No idea why it was not there in the first place?

Missing pull request functionality (save relations after model create).

### CODE REVIEW

**Comment by daftspunk** [comment]
Hey @Upperfoot, it wasn't there in the first place because it doesn't need to be. Take a look at the [belongsToMany unit test](https://github.com/octobercms/october/blob/master/tests/unit/plugins/database/BelongsToManyModelTest.php#L39):

```
// Same as $author->roles()->sync(1,2,3,..);
$author->roles = [1, 2, 3, ...];
```

**Comment by daftspunk** [comment]
Feel free to submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue.

**Comment by Upperfoot** [comment]
Just tried this against a fresh copy of Master branch of October, and a fresh copy of the Rainlab Plugin.

Assigning groups to a user fails to save, CTRL+F5 on a user edit page after assigning that user to a group shows that the groups have not been saved.

https://github.com/rainlab/user-plugin/blob/master/models/user/fields.yaml#L58-L62

**Comment by daftspunk** [comment]
Hmm, I was unable to replicate this. 

1. I opened an existing user
1. Assigned the default group.
1. Clicked save
1. Refresh the page
1. The group was still assigned

**Pull request closed without merging**
