### PR TITLE
update htacess

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please explain why this is necessary.

**Comment by ctf0** [comment]
the outside world shouldnt be able to access anything other the storage folder, so everything else was blacklisted.

**Comment by LukeTowers** [comment]
@daftspunk any input?

**Comment by daftspunk** [comment]
The .htaccess mimics the `october:mirror` command

```
    protected $wildcards = [
        'modules/*/assets',
        'modules/*/resources',
        'modules/*/behaviors/*/assets',
        'modules/*/behaviors/*/resources',
        'modules/*/widgets/*/assets',
        'modules/*/widgets/*/resources',
        'modules/*/formwidgets/*/assets',
        'modules/*/formwidgets/*/resources',
        'modules/*/reportwidgets/*/assets',
        'modules/*/reportwidgets/*/resources',

        'plugins/*/*/assets',
        'plugins/*/*/resources',
        'plugins/*/*/behaviors/*/assets',
        'plugins/*/*/behaviors/*/resources',
        'plugins/*/*/reportwidgets/*/assets',
        'plugins/*/*/reportwidgets/*/resources',
        'plugins/*/*/formwidgets/*/assets',
        'plugins/*/*/formwidgets/*/resources',
        'plugins/*/*/widgets/*/assets',
        'plugins/*/*/widgets/*/resources',

        'themes/*/assets',
        'themes/*/resources',
    ];
```

This proposed personalized version should not be included because it breaks the platform.

**Pull request closed without merging**
