### PR TITLE
Changed z-index

### PR DESCRIPTION
**Pull request by VoroninWD**
Before:
image

After:
image

### CODE REVIEW

**Comment by w20k** [comment]
Recompile pliz CSS assets `php artisan october:util compile less`!

**Comment by w20k** [comment]
@LukeTowers - tested.

Status - ✅

Before (had to mess up with css height to make it visible):
screenshot 2019-01-26 at 23 01 43

After:
screenshot 2019-01-26 at 23 05 06

Found a minor UI bug: while in a popup if you scroll down, your options list will tag along 😄

**Comment by LukeTowers** [comment]
@w20k how about in nested popups or outside of popups?

**Comment by w20k** [comment]
@LukeTowers never ever used nested pop-ups)) Will look at it, think should be fine. Because it should be relative to pop-up window.
Outside - works as it should!

**Comment by LukeTowers** [comment]
Alright. I hate mucking about with zindex changes, it always ends up breaking something somewhere in unexpected ways.

**Pull request merged**
