### PR TITLE
Updated to log when name is changed

### PR DESCRIPTION
**Pull request by SeriousKen**
Enhancement that logs when a CMS object has been renamed but the content is unchanged

### CODE REVIEW

**Comment by LukeTowers** [comment]
Not sure what the purpose of this is exactly.

**Comment by SeriousKen** [comment]
@LukeTowers when logging changes to themes renaming a page/partial doesn't get logged unless the content also changes. I think it would make sense to log when theme elements are renamed and who and when it happend.

**Comment by LukeTowers** [comment]
@SeriousKen so this changes the ThemeLogging to also log whenever a page's template is changed?

**Comment by SeriousKen** [comment]
@LukeTowers it changes ThemeLogging to log when the filename changes. So, for example, if I change `home.htm` to `index.htm` that is not currently logged.

**Pull request merged**
