### PR TITLE
fix issue 4185

### PR DESCRIPTION
**Pull request by gaabora**
This fixes wrong parameter value in php section of page template if it's value equals '0'
https://github.com/octobercms/october/issues/4185

### CODE REVIEW

**Comment by bennothommo** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the `develop` branch.

I'll fix it for you this time, but please ensure you make any future PRs to the `develop` branch, not the `master` branch.

**Comment by bennothommo** [comment]
@gaabora It might be better to keep the original line there, but instead of doing an `!empty` check, just simply check to see that the parameter is not an empty string, `false` or `null`. This should help to minimise any unintended side effects with this change.

**Comment by LukeTowers** [comment]
@bennothommo github actions bot still in develop?

**Comment by LukeTowers** [comment]
@bennothommo to expand on your suggestion, what are "empty" values that are actually acceptable? We could just explicitly allow those values before falling back to the !empty() check. I think I would prefer that tbh.

**Comment by bennothommo** [comment]
@LukeTowers TBH I'm not sure. From what I've seen, the only two values I think would be valid that are "empty" values are 0, and an empty string, but I can't say with any certainty whether others are in use, ie. an empty array.

**Comment by LukeTowers** [comment]
@bennothommo how about 0 as a string? `"0"` Not sure 100% but I think empty() considers that to be falsey.

**Comment by bennothommo** [comment]
@LukeTowers you're right, it does. So I would assume that needs to be valid too.

**Comment by gaabora** [comment]
So should I change it to
`if (array_key_exists($name, $this->parameters) && ($this->parameters[$name] !=='' || $this->parameters[$name] !== null)) {`

**Comment by bennothommo** [comment]
@gaabora I'd try the following:
```php
if (isset($this->parameters[$name]) && !in_array($this->parameters[$name], ['', 0, '0'])) {
```

**Comment by gaabora** [comment]
> 
> 
> @gaabora I'd try the following:
> 
> ```
> if (isset($this->parameters[$name]) && (in_array($this->parameters[$name], ['', 0, '0']) || !empty($this->parameters[$name]))) {
> ```
`in_array` needs 3rd parameter to be `true` for strict check, otherwise there's no point,
also strict comparing with `or` condition will work faster than `in_array`

**Comment by bennothommo** [comment]
@gaabora It would only be microseconds difference, so I'm happy with `in_array` because it's more readable. You're correct though in that we'd need the strict check, so feel free to add that in too.

**Comment by LukeTowers** [comment]
@gaabora Isn't `0` by itself an acceptable value?

**Comment by gaabora** [comment]
> @gaabora Isn't `0` by itself an acceptable value?

Did you mean integer `0` value? Then there's no way in this function for $this->parameters[$name] to be === `0`, only `'0'`, cause it produces from string parsing.

**Pull request merged**
