### PR TITLE
Improve the System Status dashboard widget

### PR DESCRIPTION
**Pull request by gergo85**
Add notification, when the events log or request log are disabled:
widget

The log settings in this case:
img2

The warning icon is clickable (/system/settings/update/october/system/log_settings) and has tooltip:
hover

### CODE REVIEW

**Comment by gergo85** [comment]
@LukeTowers Any suggestion for this idea?

**Comment by w20k** [comment]
Hi @gergo85, don't mind if add my 50 cents. From the UX perspective, it's better to use yellow color, because logging, in some cases, is not mandatory and not critical at all :) 
For the icon would use bubble with 'i' (information), but there is already a bubble icon - 'icon-exclamation' or 'icon-info', would do the trick.

**Comment by gergo85** [comment]
This is the suggested version:
widgetv2

**Comment by LukeTowers** [comment]
I'm fine with the triangle warning sign coloured yellow

**Comment by gergo85** [comment]
I can't modify this repository :(

**Comment by LukeTowers** [comment]
@gergo85 feel free to resubmit

**Comment by gergo85** [comment]
@LukeTowers Alright. I created a new PR (#3866).

**Pull request closed without merging**
