### PR TITLE
Update French Translation

### PR DESCRIPTION
**Pull request by Sicklou**
Add missing translations based on the english file translation.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@w20k another one with the hasManyModelTest failing

**Comment by w20k** [comment]
@LukeTowers It's because of the latest changes with HasMany...either it's a bug (one more), or just a test that's failing ^^

**Comment by LukeTowers** [comment]
@w20k could you find out which and maybe poke the contributors to those changes to get the issue resolved?

**Comment by w20k** [comment]
@LukeTowers this should be good to go. Will poke few guys about this test, but for now, skipped it.

**Pull request merged**
