### PR TITLE
Fire beforeDelete on pivot models

### PR DESCRIPTION
**Pull request by meysammahfouzi**
This commit tries to fix https://github.com/octobercms/october/issues/2747

I am not sure though if this is the best possible solution!

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by meysammahfouzi** [comment]
@LukeTowers Thanks

**Comment by LukeTowers** [comment]
@meysammahfouzi I've sent this to @daftspunk for review as he's more familiar with this piece than I am.

**Comment by LukeTowers** [comment]
@meysammahfouzi is there a way that we can fire the deleting model event on the pivot model instead as that would then allow the beforeDelete method, the deleting laravel model event and the model.beforeDelete event to be fired?

**Comment by meysammahfouzi** [comment]
@LukeTowers Well, I tried to find a way to do that, but unfortunately could not. So just tried to simulate it. Could @daftspunk take a look at it?

**Comment by LukeTowers** [comment]
I can assign it to his project but whether or not he's actually going to look at it is a completely different issue.

**Comment by daftspunk** [comment]
This is one of those cases where it would be too magical to include in the core, with too many different possibilities. So instead you may want to try hooking up the event yourself. Here is an example:

```
    public $belongsToMany = [
        'roles_pivot_model' => [
            'October\Test\Models\Role',
            'table' => 'october_test_users_roles',
            'pivot' => ['clearance_level', 'is_executive'],
            'timestamps' => true,
            'pivotModel' => 'October\Test\Models\UserRolePivot',
        ],
    ];

    public function afterFetch()
    {
        $this->bindEvent('model.relation.beforeDetach', function($relation, $ids) {
            if ($relation == 'roles_pivot_model') {
                $this->roles_pivot_model()->whereIn('id', $ids)->get()->each(function($model) {
                    $model->pivot->beforeDelete();
                });
            }
        });
    }
```

**Pull request closed without merging**
