### PR TITLE
Update the Modernizr library - from 2.8.3 to 3.6.0

### PR DESCRIPTION
**Pull request by ayumihamsaki**
This Pull Request has the following Update information:

1. Modernizr 2.8.3 upgraded to 3.6.0 (custom build)

2. As per request to not have a minified version, so after the build process I put it through a Javascript Beautifier

3. I have included at the top of the file the custom build URI and the version number for easy future updates

4. Yepnope has been dropped from the update file as per request

> For these reasons, we're also not going to include yepnope in the next version of Modernizr as Modernizr.load. And for the new version of Modernizr it's not even needed!

5. This PR is separate from other library updates as per request also

All this follows on from PR: https://github.com/octobercms/october/pull/3868 which will now be closed down and linked.

For the following people to review and check:

@LukeTowers @w20k

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Also link this PR to issue: https://github.com/octobercms/october/issues/3867

**Comment by LukeTowers** [comment]
@ayumihamsaki the "beautified" version is just as opaque as the minified version, could you just commit the minified version instead?

**Comment by ayumihamsaki** [comment]
@LukeTowers done

**Comment by LukeTowers** [comment]
Awesome. @w20k @Teranode could you test this?

**Comment by Teranode** [comment]
All good for me here

**Comment by w20k** [comment]
Same here ;) Tested!

**Pull request merged**
