### PR TITLE
Dashboard Updates (Improving the Down-Scaling Aspect and Styling)

### PR DESCRIPTION
**Pull request by ayumihamasaki2**
The CSS and LESS is finished and I have done the easy Javascript.

But the `reportcontainer.js` needs a lot of work done to it. **_I request help with regards to updating that file!_**

The `reportcontainer.js` has been temporary turned off in the `ReportContainer.php` to show that the present code does work! See code line: https://github.com/ayumihamasaki2/october/blob/b259ebdcb0b93473478406e0d010555f3c34305d/modules/backend/widgets/ReportContainer.php#L128

However, the javascript in `reportcontainer.js` when turned on messes everything up and gives poor results.

For now you can test this first commit and see it working and report any small issues! However, I request help to finish this PR off as I feel updating the `reportcontainer.js` is going to require a lot of work and not so easy to do.

This PR relates to the issue found here: https://github.com/octobercms/october/issues/3958

### CODE REVIEW

**Comment by ayumihamasaki2** [comment]
Below, demo's this PR and shows the down-scaling, updated styling to improve WCAG 2.0 AA Web Standards making the styling, contrasts and font sizing easier to read and much less blurry. Also added CSS code to cut the words and force the writing into the boxes. Made the images responsive and lots of other general tidy up's:

ezgif-2-4362dc6d7a0a

* The only thing not working is the drag and drop due to the `reportcontainer.js` being turned off.

**Comment by ayumihamasaki2** [comment]
Below, demo's this PR and shows the down-scaling, updated styling to improve WCAG 2.0 AA Web Standards making the styling, contrasts and font sizing easier to read and much less blurry. Also added CSS code to cut the words and force the writing into the boxes. Made the images responsive and lots of other general tidy up's:

aaaaaaa

* The only thing not working is the drag and drop due to the `reportcontainer.js` being turned off.

**Comment by LukeTowers** [comment]
@ayumihamasaki2 to resolve the conflicts you need to use the latest dev branch of the library repo and run `october:util compile assets`

**Comment by LukeTowers** [comment]
@Teranode are you interested in helping fix the reportcontainer.js issues with this?

**Comment by w20k** [comment]
@ayumihamasaki2, would really love to help ;) but I'm on vacation till 5th Jan. If @Teranode have a free time - would be awesome 😉!

**Comment by ayumihamsaki** [comment]
@LukeTowers I will wait until next year for the reply, I have tried your method and did the following:

Run php artisan october:util compile assets

Says error and need to run Composer install

I do that and re-run the php artisan october:util compile assets

It works then, but generates 2121 changed files.

Removing most of the files and updating only the folder: modules/backend/assets/* I get 61 files changed.

Should I push all those files or not? Or will it not create an error just to extract only the 5 files being changed in this pr.

Link for my notes: https://octobercms.com/docs/console/commands#october-util-command

------------

I was thinking and have a question to ask?

Now that Luke has re-complied the following files:

- october.min.css
- storm.min.css

They are semi-compressed now and I find it actually harder to fix bugs in the css.

I wanted to ask the following: Would it be better to have the master branch fully complied and compressed (non-readable) for every release. Then the developer branch to be periodically complied, but always completely uncompressed and (fully readable) - making it easy to big fix css etc.

**Comment by LukeTowers** [comment]
@ayumihamasaki2 I think we just need to revert the change to the minification that removes newlines from the library repo.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by ayumihamsaki** [comment]
@LukeTowers Dasftpunk recently updated the dashboard pr I did of the 10 to 12, so this pr could be worked on now. Though I would still request help to process the javascript side of things as it seems a bit of a mess.

I would personally leave this open, because the dashboard has many bugs due to it not being responsive and this issue should be addressed sometime in the near future.

**Comment by w20k** [comment]
@ayumihamsaki could you revise your PR, if you have time and if it's still valid would help with JS part ;)

**Comment by ayumihamsaki** [comment]
ok I will try and do that within the next 24 hours.

**Comment by ayumihamsaki** [comment]
@w20k Have tested it, code still looks valid, just need to finish off the javascript side.

**Comment by ayumihamsaki** [comment]
@w20k if it's ok with you, would you like to add this to your To Do List (just a suggestion - totally up to you)

**Comment by w20k** [comment]
@ayumihamsaki I think you'd have to resubmit this PR once again :) Ping me on a new one!

**Comment by ayumihamsaki** [comment]
moved to here: https://github.com/octobercms/october/pull/4329

**Pull request closed without merging**
