### PR TITLE
Unescaped quote fix

### PR DESCRIPTION
**Pull request by tschallacka**
Fixes an unescaped quote in ukrain language file.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@daftspunk Is there any way that we could create unit tests for language files to validate that syntax issues like this don't happen again?

**Comment by daftspunk** [comment]
@LukeTowers we have one already, not sure how this made it through: https://github.com/octobercms/october/blob/master/tests/unit/system/classes/CoreLangTest.php

**Comment by tschallacka** [comment]
Well, maybe the locale isnt in the list of locales being tested? It seems to pull a list of locales at https://github.com/octobercms/october/blob/master/tests/unit/system/classes/CoreLangTest.php#L30 if its not in there, it wont get tested.

I only noticed it because eclipse threw a hissy fit

**Comment by daftspunk** [comment]
So you're saying `uk` wasn't in the list?

**Comment by tschallacka** [comment]
Well, i just looked at a possible explanation on mobile why uk is skipped in the unit test...

**Comment by LukeTowers** [comment]
@tschallacka Why is that?

**Pull request merged**
