### PR TITLE
Update Modernizr V3.6.0 to V3.7.1

### PR DESCRIPTION
**Pull request by ayumihamasaki2**
Note: There is no official build on the website yet, so I downloaded the files and did a manual build myself. Please test for any errors.

Github Issue: https://github.com/octobercms/october/issues/3867

### CODE REVIEW

**Comment by ayumihamasaki2** [comment]
If there are errors, will just wait for them to fix this issue: https://github.com/Modernizr/Modernizr/issues/2440

**Comment by LukeTowers** [comment]
What are the benefits of this update?

**Comment by ayumihamsaki** [comment]
Their website doesn't say it's stuck on [V3.5.0](https://modernizr.com/news) but I will try and give a brief overview of the updates:

- There 14 commits since 3.6.0
- Google Chrome V70+ have changed the touch event detection https://bugs.chromium.org/p/chromium/issues/detail?id=36415
- Many bug fixes in the code (basic errors) that have been fixed
- Updated and bug fixed several components October uses
- Added new API's
- Updated their package list dependencies for their Core code
- Google Chrome V73+ have changed their pointer events also (last week I had to fix one of my github repo's with regards to this as well) - Can see here for more details: https://developers.google.com/web/updates/2019/02/scrolling-intervention

p.s. Not really happy to merge with this PR right now. I would be happy to leave it open and when they update their website I can update this PR with their code (just to make sure I haven't created any mistakes by manually building it myself).

But in the mean time please decide whether this is a good one to update or not? ~If it is then I will update this PR and tag you when they update their website builder.

**Comment by w20k** [comment]
@ayumihamsaki could you also list all the plugins that you've included into this build?

**Comment by ayumihamsaki** [comment]
@w20k already have - see line 2 of the code, I used all of them.

**Comment by w20k** [comment]
Thanks, totally missed that, will double check!

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers 

Just going through and creating the custom json file to do an automatic build process, I would like to add the following extra things:

```json
    "css/flexwrap", <-- Part of the flexbox attributes
    "css/fontdisplay", <-- This is a new standard for loading fonts (I want to add this to October in a different pr)
    "img/sizes", <-- This is very common and should be included
    "img/srcset", <-- This is very common and should be included
    "img/webp", <-- Webp is the most common image standard and should be included
    "img/webp-alpha", <-- Webp is the most common image standard and should be included
    "img/webp-animation", <-- Webp is the most common image standard and should be included
    "img/webp-lossless", <-- Webp is the most common image standard and should be included
    "css/cssgrid", <-- We have Flexbox included, I think we should also include css grids
    "css/boxsizing", <-- We use this in the css backend in css files
    "css/calc", <-- We use this in the css backend in javascript files
```

The custom file I have created is here: https://github.com/ayumihamsaki/october-modernizr/blob/master/modernizr-config.json

Please can you go through it and double check things. If you are happy I will re-build the Modernizr commit.

Also I think it would be a good idea to create a folder and store it in the repo: https://github.com/octoberrain/meta/modernizr-config.md

Also a big ask. Is it possible to move that repo over here to have a url of:

https://github.com/octobercms/meta

Because it just took me 30 mins trying to find that repo! Be easier to have everything in one place.

**Comment by ayumihamasaki2** [comment]
I need to close this and re-up a new pr. Because github has done something stupid to my account and I had to update the settings. Will link this pr to the new one with the updated commit.

**Comment by ayumihamasaki2** [comment]
Moved to here: https://github.com/octobercms/october/pull/4316

**Pull request closed without merging**
