### PR TITLE
add makeCacheId Event

### PR DESCRIPTION
**Pull request by christianWilling**
adds event so plugins can modify the cacheId

### CODE REVIEW

**Comment by christianWilling** [comment]
#1778

**Comment by daftspunk** [comment]
Please include example code of how this is used, i.e the code that contains `Event::listen`

**Comment by daftspunk** [comment]
Still not sure what this is for and how it is used. This feature requires documentation and example code. Please resubmit when you are ready to provide more details.

**Comment by christianWilling** [comment]
Im sry I was on hollday.


And I'm sry again  this pull request is useless I made an mistake makeChaheId is the wrong function.


The problem I won't to fix is if I have a page with with an include less or scss and in the this file I have included some other file if I change something in this file and reload the page it won't change because the caching only effects the file wichbis included in the layout.

I will create an new pull request for this.

I think the problem is that the assets for the assetsCache class don't have filter because in filter you can add an filter cache hash wich includes the included files for example.

**Pull request closed without merging**
