### PR TITLE
Add method to easily extend filter scopes

### PR DESCRIPTION
**Pull request by CSNWEB**
Hello,

I thought an interface similar to the one provided for extending list columns would be useful for filter scopes as well. At least I need that feature currently to add some dynamic filters.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please provide your real-world example of how you will be using this. We need that for peer review. Also, why doesn't `listExtendQuery` work for you?

**Comment by LukeTowers** [comment]
After discussion and further examination this merely provides a similar method to access `backend.filter.extendScopes` as `listExtendColumns` and `extendListColumns` does for `backend.list.extendColumns`. Will merge it when the Travis build completes.

**Comment by CSNWEB** [comment]
Just in case anybody is interested here is a simple real world exmaple:

```PHP
public function filterExtendScopes($filter) {
        $id = last(Request::segments());
        $account =  Account::find($id);
        $filter->addScopes([
          'hasSameGender' => [
            'label' => 'Has Same Gender',
            'type' => 'checkbox',
            'conditions' => 'gender like \''.$account->gender.'\''
          ]
        ]);
}
```

Or as a static extension:

```PHP
Buddys::extendFilterScopes(function($filter){
        $filter->addScopes([
          'filter' => [
            'label' => 'label',
            'type' => 'checkbox',
            'conditions' => 'condition'
          ]
        ]);
});
```

**Comment by iboved** [comment]
This does not work if you try to add a list filter to the controller and this controller does not have any filters before. It seems that the filter widget is not bind to the controller.

This works only if the controller has at least one filter.

Maybe you know how to add list filter to the controller if this controller does not have any filters?
Thank you in advance.

**Comment by CSNWEB** [comment]
Why not add an empty filter to config?

**Comment by iboved** [comment]
I am extending an external plugin. I don't want to edit this plugin directly.
There is `addViewPath()` method to override controller views. But I cannot override `$configPath` property, because this propery is protected.

**Comment by CSNWEB** [comment]
I think you should be able to extend the controller and add the filter widget

**Comment by iboved** [comment]
Ok, thanks for the answers. I will ask on Slack.

**Comment by CSNWEB** [comment]
@iboved you can try to overwrite listGetConfig: https://github.com/octobercms/october/blob/a3b93f1a0b84c14b238c464a1eb93801efea06d6/modules/backend/behaviors/ListController.php#L435

Toghether with this: http://octobercms.com/docs/backend/lists#overriding-action
and this:
http://octobercms.com/docs/services/behaviors

```PHP
ControllerThatShouldBeExtended::extend(function($controller) {
    $controller->addDynamicMethod('listGetConfig', function() use ($controller) {
        $config = $controller->asExtension('ListController')->listGetConfig();
      //add filter to config 
      return $config
    });
});
```
No clue if that would actually work though

**Comment by iboved** [comment]
It would be amazing if it worked. But for some reason my dynamic `listGetConfig` method is not called. I just checked it.
Thank you very much for your advice.

**Comment by iboved** [comment]
@CSNWEB I have found the solution.
In my Plugin.php file in the `boot()` method I specified the full path to the `config_list.yaml` file:

```
        ControllerThatShouldBeExtended::extend(function ($controller) {
            $controller->listConfig = '$/acme/demo/controllers/mycontroller/config_list.yaml';
        });
```

And in the `config_list.yaml` file I pecified the full path to the `config_filter.yaml` file:

```
filter: $/acme/demo/controllers/mycontroller/config_filter.yaml
```

**Comment by LukeTowers** [comment]
@iboved @CSNWEB you can use the `mergeConfig()` method to merge two configs, so do:
```php
ControllerThatShouldBeExtended::extend(function ($controller) {
    $controller->listConfig = $controller->mergeConfig('/original/config.yaml', 'overriding/config.yaml');
});
```

**Comment by iboved** [comment]
@LukeTowers thanks! It works really cool.

**Comment by LukeTowers** [comment]
@iboved, no problem, happy to help! Are you able to suggest any improvements to the documentation in the form of a PR to octobercms/docs?

**Pull request merged**
