### PR TITLE
Jquery ready

### PR DESCRIPTION
**Pull request by ayumihamsaki**
As per: https://github.com/octobercms/october/pull/4461

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Finished.

**Comment by w20k** [comment]
Needs a quick smoke test and ready for merge.

**Comment by ayumihamsaki** [comment]
@w20k smoking is bad for you 😆

**Comment by ayumihamsaki** [comment]
Closed please see the main jQuery update PR.

**Pull request closed without merging**
