### PR TITLE
Add getters for relation widgets

### PR DESCRIPTION
**Pull request by alxy**
These are available for the ``FormController`` as well, so this is just consistent and usefull in some cases.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Could you provide an example of these being used in an actual use case and also provide documentation for these methods?

**Comment by alxy** [comment]
It is very hard to clearly desribe the actual use case (I obviously have one, otherwise I would not post this PR),a s it is rather complex indeed. But sometimes you just need access to these widgets from your controller, for example to get the fields array or some form data. I know that there are quite a few events that can be used as well, but for some reason ``formGetWidget`` does exist as well. I don't think that this need to be in the docs (again, I think ``formGetWidget`` isn't documented either), as it is really an advanced feature here and it is enough to have the API docs in this case.

**Comment by LukeTowers** [comment]
I'm not opposed to this change, but out of curiosity why doesn't the events approach to accessing those widgets work for you? I would assume that would be more reliable as the widgets would always be available in the events but are not always going to be available at any point during the cycle when someone could call these methods.

**Comment by alxy** [comment]
@LukeTowers I can describe this in detail on IRC if you like :)

**Comment by LukeTowers** [comment]
How about on Slack @alxy? :)

**Pull request merged**
