### PR TITLE
[WIP] Relation manage filters

### PR DESCRIPTION
**Pull request by alxy**
**This PR is a WIP**

It aims at making [list filters](https://octobercms.com/docs/backend/lists#list-filters) available for the RelationController, specifically the manage widget.

Example usage in `config_relation.yaml`:
```
posts:
    label: Posts
    list: ~/plugins/october/test/models/post/columns.yaml
    form: ~/plugins/october/test/models/post/fields_simple.yaml
    manage:
        showSearch: true
        filter:
            scopes:
                published_at:
                    label: Date
                    type: daterange
                    conditions: created_at >= ':after' AND created_at <= ':before'
                username:
                    label: Name
                    type: text
                    conditions: name = :value
                    size: 2
                status:
                    label: Status
                    modelClass: October\Test\Models\Attribute
                    conditions: status_id in (:filtered)
                    nameFrom: name
```

Peek 2019-03-20 11-29

It does work, however there are some issues that need to be fixed. These are mostly interface/javascript based:
- [x]  The `date` and `daterange` pickers appear to open behind the modal
- [x] Clicking apply/clear on a filter popup triggers a JS error
- [x] Figure out why the positioning of the popups is a bit off when using a container element

I debugged the JS errors a bit and they do happen if the modal is opened a second time without a har refresh of the page. It appears, in this case the filter is not correctly re-initialized. Here are the errors I am getting in the console once I clear the Apply/Clear buttons on a filter widget popover:

```
storm-min.js?v447:31699 Uncaught TypeError: Cannot read property 'find' of null
    at FilterWidget.updateScopeDateSetting (storm-min.js?v447:31699)
    at FilterWidget.filterByDate (storm-min.js?v447:31765)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31498)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
FilterWidget.updateScopeDateSetting @ storm-min.js?v447:31699
FilterWidget.filterByDate @ storm-min.js?v447:31765
(anonymous) @ storm-min.js?v447:31498
dispatch @ jquery.min.js?v447:5201
elemData.handle @ jquery.min.js?v447:5009
3storm-min.js?v447:31699 Uncaught TypeError: Cannot read property 'find' of null
    at FilterWidget.updateScopeDateSetting (storm-min.js?v447:31699)
    at FilterWidget.filterByDate (storm-min.js?v447:31765)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31505)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
FilterWidget.updateScopeDateSetting @ storm-min.js?v447:31699
FilterWidget.filterByDate @ storm-min.js?v447:31765
(anonymous) @ storm-min.js?v447:31505
dispatch @ jquery.min.js?v447:5201
elemData.handle @ jquery.min.js?v447:5009
storm-min.js?v447:31347 Uncaught TypeError: Cannot read property 'data' of null
    at FilterWidget.filterScope (storm-min.js?v447:31347)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31052)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
```

### CODE REVIEW

**Comment by bennothommo** [comment]
Sample JS error reported by @alxy on Slack, for reference:

```
storm-min.js?v447:31699 Uncaught TypeError: Cannot read property 'find' of null
    at FilterWidget.updateScopeDateSetting (storm-min.js?v447:31699)
    at FilterWidget.filterByDate (storm-min.js?v447:31765)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31498)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
FilterWidget.updateScopeDateSetting @ storm-min.js?v447:31699
FilterWidget.filterByDate @ storm-min.js?v447:31765
(anonymous) @ storm-min.js?v447:31498
dispatch @ jquery.min.js?v447:5201
elemData.handle @ jquery.min.js?v447:5009
3storm-min.js?v447:31699 Uncaught TypeError: Cannot read property 'find' of null
    at FilterWidget.updateScopeDateSetting (storm-min.js?v447:31699)
    at FilterWidget.filterByDate (storm-min.js?v447:31765)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31505)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
FilterWidget.updateScopeDateSetting @ storm-min.js?v447:31699
FilterWidget.filterByDate @ storm-min.js?v447:31765
(anonymous) @ storm-min.js?v447:31505
dispatch @ jquery.min.js?v447:5201
elemData.handle @ jquery.min.js?v447:5009
storm-min.js?v447:31347 Uncaught TypeError: Cannot read property 'data' of null
    at FilterWidget.filterScope (storm-min.js?v447:31347)
    at HTMLButtonElement.<anonymous> (storm-min.js?v447:31052)
    at HTMLDocument.dispatch (jquery.min.js?v447:5201)
    at HTMLDocument.elemData.handle (jquery.min.js?v447:5009)
```

**Comment by alxy** [comment]
I have debugged this case and it appears to be becasue the filter.js widget is not disposable (it does not unbind its event handlers). The init method gets called whenever the modal with the filter wigets opens and rebinds [all these handlers here](https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/filter.js#L103-L157). This in turn leads to only the first handlers beeing executed, as they contain references to old variables - which lead to errors and break the process.

**Comment by alxy** [comment]
I have addressed the JS issues by a major rework of the filter JS library. Before binding any event handlers to the filter scopes (elements), the old handlers are unbound. Like this, the filter mechanism works as expected in the reopened modal.

Please test.

**Comment by bennothommo** [comment]
Looks awesome @alxy. Well done on getting it all figured out too :)

**Comment by w20k** [comment]
Looks awesome @alxy. Testing is done - works fine, though `text field` got me off guard.

@LukeTowers could be merged ;) 
Status - ✅

**Comment by alxy** [comment]
I will recreate this PR, as a few things have already been fixed in develop in the mean time

**Comment by w20k** [comment]
Sure - @alxy. Ping me on a new one. Will re-run tests.

**Comment by LukeTowers** [comment]
What else would need to be done to add support for filters in the `view` context?

**Comment by w20k** [comment]
@LukeTowers I guess it was about this one: https://github.com/octobercms/october/pull/4235

**Comment by alxy** [comment]
@w20k I think Luke was referring to the fact that this PR only adds support for filters on the manage view, i.e. in the modal/popup list to select the related records. The `view` context on the other hand is the list of already attached records, which may also benefit from having filters available.

**Pull request closed without merging**
