### PR TITLE
Fixed bug caused by not existing use statement

### PR DESCRIPTION
**Pull request by tschallacka**
Caused an error on line 95 where this class was used

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by tschallacka** [comment]
steps to reproduce:

Open the october as provided by installer in eclipse without any folders marked as library folders.

it will complain about the not existing class in the use statement. The class is not present anywhere in the library folders, also it's nowhere used in the class itself.

**Comment by LukeTowers** [comment]
Can you trigger PHP itself complaining about the class not existing rather than just your IDE? I understand how it wouldn't work in theory, but I'm curious as to what needs to happen to actually trigger that code path.

**Comment by tschallacka** [comment]
This script checks for unused statements. Maybe you could use something like that? 

https://stackoverflow.com/questions/9895502/easiest-way-to-detect-remove-unused-use-statements-from-php-codebase#9896557

then one could use something like:

    $unused = collect($sanitizer->getUnused());
    if($unused->count()) {
        throw new Exception("Unused use statements :".$unused->implode(', ');
    }

**Comment by LukeTowers** [comment]
That comment only makes sense when removing `use` statements that aren't actually used. This PR is *adding* a `use Twig_Template;` statement, I'd like to know why.

**Comment by tschallacka** [comment]
Sorry, I got commits mixed up in my head. sorry for that.

I added the use because of https://github.com/tschallacka/october/blob/dd769e3688fd7324dcae4006e186ec7f7261a405/modules/cms/twig/DebugExtension.php#L96

**Pull request merged**
