### PR TITLE
Add filter of type text in backend list

### PR DESCRIPTION
**Pull request by ChVuagniaux**
A text filter that you can setup to choose what filter : one column, multi columns or scope.

See https://github.com/octobercms/october/issues/3048

## usage 
```
    id:
        label: "ID"
        type: text
        conditions: id = :value
        size: 2

    username:
        label: "Username"
        type: text
        conditions: username = :value
```

## demo 
ezgif-4-abbe9dde75

### CODE REVIEW

**Comment by pvullioud** [comment]
asked by @LukeTowers
Could you move the `case: text` statements after the `case: numberrange` statements? I'm not really a fan of the `case: number` and `case: numberrange` statements being separated by a completely different type of filter

**Comment by ChVuagniaux** [comment]
@LukeTowers change done, it's ok for you ?

**Comment by LukeTowers** [comment]
Works for me, could someone else please review and test on their own setup and let me know if it works well for them? Perhaps you @pvullioud?

**Comment by pvullioud** [comment]
@LukeTowers I already use it on a dev site with success. @ChVuagniaux and I are on the same team.

**Comment by LukeTowers** [comment]
Awesome, thanks @ChVuagniaux and @pvullioud!

**Comment by pvullioud** [comment]
Thanks @LukeTowers for all you work

**Comment by danielbruni** [comment]
Thanks was looking for this feature.

**Pull request merged**
