### PR TITLE
Fix popup loading indicator

### PR DESCRIPTION
**Pull request by drmzio**
Fixes issue #4168

### CODE REVIEW

**Comment by w20k** [comment]
@drmzio could you provide a simple example to reproduce your issue?

**Comment by LukeTowers** [comment]
JS will need to be compiled too I believe. Also @drmzio could you make the zindex of the loader indicator higher than the popup modal itself? It would make the issue more apparent if it happens again, as well as solve the issue of opening nested popups not showing the loading indicator beyond the first popup.

**Comment by drmzio** [comment]
@LukeTowers Wouldn't compiling JS have marge conflicts with other PRs?

@w20k Here's the steps to reproduce:

1. Install OctoberCMS
2. Add this code to the home page __markup__ section:
```twig
{% put styles %}
    <link rel="stylesheet" href="{{ 'modules/system/assets/ui/storm.css'|app }}">
{% endput %}
{% put scripts %}
    <script src="{{ 'modules/system/assets/ui/storm-min.js'|app }}"></script>
    <script>
        var newPopup = $('<a />');
        newPopup.popup({ handler: 'onLoadContent' });
    </script>
{% endput %}
```
3. Add AJAX handler function to home page __code__ section:
```php
function onLoadContent()
{
    return 'Loaded';
}
```

Video demo: https://cl.ly/5b456d5319b4

**Comment by LukeTowers** [comment]
@drmzio nope, whoever gets in first makes the rest of the PRs that would affect the same file have to rebase. Rarely happens though that we've got multiple active PRs touching the same file.

**Comment by drmzio** [comment]
@LukeTowers Ok I added the compiled JS

**Comment by w20k** [comment]
> **@LukeTowers commet** 
>@drmzio could you make the zindex of the loader indicator higher than the popup modal itself

@drmzio could you push changes for z-index and should be read!
Status - ✅

**Comment by drmzio** [comment]
@w20k Hi, I don't think that is possible because the loading indicator is inside the modal backdrop. (See screenshot)

Test demo: https://octobercms.site000.com/

**Comment by LukeTowers** [comment]
@drmzio if the loading indicator switched to a different position stack (i.e. fixed) than the modal backdrop wouldn't that work? Or would it cause other issues?

**Comment by LukeTowers** [comment]
Actually, maybe it's the modal backdrop that needs to be bumped up when a nested popup gets opened?

**Comment by drmzio** [comment]
Hi @LukeTowers this would require changing the default behavior of the popup library and dynamically updating the backdrop z-index on nested modal windows. For now, I think this should be fine. The only issue I was having was with the loading indicator still showing after AJAX completes.

**Comment by LukeTowers** [comment]
Fair enough. @w20k can you test that this resolves the original issue?

**Comment by techstationpro** [comment]
Bro please give index.html....

**Comment by LukeTowers** [comment]
@techstationpro sounds like a spammer to me

**Comment by w20k** [comment]
@LukeTowers couldn't reproduce the described issue, even with the provided steps, but I guess, fix should be an issue for other users or use cases.

**Pull request merged**
