### PR TITLE
Richeditor modifications

### PR DESCRIPTION
**Pull request by Klaasie**
This PR modifies two things:

The form field attributes (as set by the fields.yaml) are added Richeditor div.
I've modified the styling of the disabled / readonly state of the richeditor to give a better visual representation that it's in disabled / readonly mode.
These changes include counteracting hover effects to give the "greyed out disabled" feeling to both the toolbar and the editor content. These changes are the same as changes I made for the  Markdown formwidget (https://github.com/octobercms/october/pull/5004) and use the same colors.

P.S. Although I'm aware the styling changes to the markdown editor haven't been approved I found myself with some spare time and went ahead and made these changes for the Richeditor anyway. They're all in 1 commit and can easily be reverted.

P.P.S The Richeditor is protected by a DRM. I've made the modifications in the LESS file but someone with the DRM file will need to actually compile it to the .css file. I've tested my code by using an online compiler. I'll add the css below. To test this PR without the froala drm you will need to add this css to `modules/backend/formwidgets/richeditor/assets/css/richeditor.css`

```
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command {
    cursor: not-allowed;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:hover,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:focus {
    color: #bdbdbd;
    -webkit-box-shadow: none;
    box-shadow: none;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:hover::after,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:focus::after {
    border-top-color: #bdbdbd!important;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn-hover {
    color: #bdbdbd;
    background: transparent;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn-hover::after {
    border-top-color: #bdbdbd !important;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options:hover,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options:focus {
    border-left: solid 1px transparent;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options.fr-btn-hover {
    border-left: solid 1px transparent;
}

.fr-box.fr-basic .fr-element.fr-disabled {
    color: #bdbdbd;
    cursor: not-allowed;
}
```

Before:
image

After:
image

### CODE REVIEW

**Comment by LukeTowers** [comment]
@Klaasie I prefer that the editor content styling itself doesn't get changed, the toolbar being disabled should be enough. The content is very difficult to read greyed out like that and is an accessibility concern with that low of contrast.

**Comment by Klaasie** [comment]
@LukeTowers I've removed that part from the less file. The color is back to it's default black now.

The additional css that will be added by compiling the less will translate to this:
```
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command {
	cursor: not-allowed;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:hover,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:focus {
	color: #bdbdbd;
	-webkit-box-shadow: none;
	box-shadow: none;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:hover::after,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command:focus::after {
	border-top-color: #bdbdbd!important;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn-hover {
	color: #bdbdbd;
	background: transparent;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn-hover::after {
	border-top-color: #bdbdbd !important;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options:hover,
.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options:focus {
	border-left: solid 1px transparent;
}

.fr-box.fr-basic .fr-toolbar.fr-disabled .fr-command.fr-btn.fr-options.fr-btn-hover {
	border-left: solid 1px transparent;
}

.fr-box.fr-basic .fr-element.fr-disabled {
	cursor: not-allowed;
}
```

Again, before merging someone with the froala_drm file should run the compile less command :)

**Comment by LukeTowers** [comment]
@Klaasie can you add the CSS to the compiled CSS file manually?

**Comment by Klaasie** [comment]
@LukeTowers Sure thing! I've added it to the file.

**Comment by LukeTowers** [comment]
@Klaasie can you include it in the same minified format as the rest of the file?

**Comment by Klaasie** [comment]
@LukeTowers Done.

**Pull request merged**
