### PR TITLE
Add Number Range Filter

### PR DESCRIPTION
**Pull request by purposebuiltscott**
Hi, 

This PR adds a number range scope type to OctoberCMS List filters.  In filtering lists, it can be useful to filter the list on a numeric attribute, using a range from min to max.

The number range scope displays a form for two numbers to be selected as the number range.  The conditions parameters are passed as :min and :max.

numberrange1

numberrange2

numberrange3

### CODE REVIEW

**Comment by LukeTowers** [comment]
Out of curiosity, why did this require a whole new JS and LESS file? Why couldn't the existing stuff from the daterange filter widget be used as a base?

**Comment by purposebuiltscott** [comment]
@LukeTowers being perfectly honest, I don't have the best front end skills and did my best to match the current conventions.  If there is a more elegant way to implement the js and less portions, let me know, and I'll do my best to refactor them.

**Comment by LukeTowers** [comment]
I'll try to take a closer look soon, I'm not super familiar with the implementation of the date range filter right now but I'll look closer and see if I can make some recommendations. If I don't respond within a week that means I've gotten distracted from it by other stuff so you'll need to ping me again :)

**Comment by daftspunk** [comment]
Looks good. Needs a supporting PR to the docs repo.

**Comment by purposebuiltscott** [comment]
Just added a PR for the docs

**Comment by LukeTowers** [comment]
Thanks! We'll hold off on merging this just yet, we want to have a super stable version as the last version that supports PHP 5.5.9 and before we bump the Laravel version to 5.5 LTS

**Comment by CSNWEB** [comment]
@LukeTowers now that 5.5 is merged can this be merged as well?

**Comment by LukeTowers** [comment]
@CSNWEB I'll do some testing of it and then merge it once I'm done. There are some minor things that I'd like to change (such as max int being set to an arbitrary 9999 number by default, want to make that a bit more realistic first), so I'll test it and then merge it and make the necessary minor changes.

**Comment by LukeTowers** [comment]
@CSNWEB @purposebuiltscott I've merged this into develop and finished implementing it, this PR was missing some key things like support for a number filter by itself and the templates to render the numberrange filter, along with the `numbersFromAJAX` method. 

It should be all good to go now, if you both could test it, that would be fantastic. Thanks for your initial work on this @purposebuiltscott!

**Pull request merged**
