### PR TITLE
Markdown parse markdown formwidget preview

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
Added markdown parse function to the markdown formwidget preview mode.

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
Pending testing by @w20k

**Comment by SebastiaanKloos** [comment]
@LukeTowers Ahh my bad. I'll make sure I make a pull request to the develop branch.

**Comment by LukeTowers** [comment]
Waiting on testing from the fantastic @w20k

**Comment by w20k** [comment]
Never ever used previewMode in My projects 😄 Might take a while to find a proper example. Or maybe @SebastiaanKloos could you provide an example?

**Comment by SebastiaanKloos** [comment]
@w20k Well I can only provide you a screenshot at this time. Maybe I can add an example to the test plugin later.

cleanshot 2019-03-01 at 13 00 16 2x

**Comment by w20k** [comment]
Tested - ✅ 
@LukeTowers also - done!

**Pull request merged**
