### PR TITLE
Remove composer.lock from .gitignore

### PR DESCRIPTION
**Pull request by ostark**
Here is why:
https://ilikekillnerds.com/2014/09/should-you-commit-composer-lock-into-your-git-repository/

### CODE REVIEW

**Comment by LukeTowers** [comment]
Wow, what a lot of back and forth on this topic.

#922 for the initial issue
#1438 composer.lock was removed from .gitignore

Composer.lock was re-added in https://github.com/octobercms/october/commit/73d6ff2324f0827d6ed1c62273357edb695457ad *and* https://github.com/octobercms/october/commit/8c689d63ea5d580d9e0981da273cf5cae061220b without any explanation.

@daftspunk could we get a final work on the topic?

**Comment by LukeTowers** [comment]
@ostark Also, for future reference, don't create PRs to the master branch, only to the develop branch

**Comment by ostark** [comment]
Okay, did know

**Comment by ostark** [comment]
Did NOT know

**Comment by daftspunk** [comment]
If desired, you should remove this on your own. We kept getting people including composer.lock with their PRs and it became too much effort to tell them to stop. The October gateway will deliver the same version to everyone with or without the composer.lock file.

**Pull request closed without merging**
