### PR TITLE
Field dependencies on 3 levels supported.

### PR DESCRIPTION
**Pull request by meesiris**
# Field dependencies on 3 levels supported.

### Example:

**Fields formular**
**Level 1**: field_a + field_b = field_c   **and**   field_d + field_e = field_f
**Level 2**: (field_c * 2)+(field_f * 2) = field_total
**Level 3**: field_total * 2 = field_all_total

And original dependsOn for make sure everything works fine.
**Level 1**: field_g + field_h = field_i

**fields.yaml**

    fields:
        # Level 1: field_a + field_b = field_c
        field_a:
            label: field_a
            span: left
            type: number
        field_b:
            label: field_b
            span: left
            type: number
        field_c:
            label: field_c
            span: left
            type: number
            dependsOn:
                - field_a
                - field_b
            readOnly: true

        # Level 1: field_e + field_e = field_f
        field_d:
            label: field_d
            span: left
            type: number
        field_e:
            label: field_e
            span: left
            type: number
        field_f:
            label: field_f
            span: left
            type: number
            dependsOn:
                - field_d
                - field_e
            readOnly: true

        # Level 2: (field_c*2)+(field_f*2) = field_total
        field_total:
            label: field_total
            span: left
            type: number
            dependsOn:
                - field_c
                - field_f
            readOnly: true

        # Level 3: field_total*2 = field_all_total
        field_all_total:
            label: field_all_total
            span: left
            type: number
            dependsOn:
                - field_total
            readOnly: true

        # Level 1: field_g + field_h = field_i
        field_g:
            label: field_g
            span: left
            type: number
        field_h:
            label: field_h
            span: left
            type: number
        field_i:
            label: field_i
            span: left
            type: number
            dependsOn:
                - field_g
                - field_h
            readOnly: true

**Model.php**

    public function getFieldCAttribute()
    {
        $result = $this->field_a + $this->field_b;
        return ($result == 0 ? '' : $result);
    }

    public function getFieldFAttribute()
    {
        $result = $this->field_d + $this->field_e;
        return ($result == 0 ? '' : $result);
    }

    public function getFieldIAttribute()
    {
        $result = $this->field_g + $this->field_h;
        return ($result == 0 ? '' : $result);
    }

    public function getFieldTotalAttribute()
    {
        if(is_numeric($this->field_c)==false) {
            $field_c=0;
        }else{
            $field_c=$this->field_c;
        }

        if(is_numeric($this->field_f)==false) {
            $field_f=0;
        }else{
            $field_f=$this->field_f;
        }

        $result = ($field_c*2) + ($field_f*2);

        return ($result == 0 ? '' : $result);
    }

    public function getFieldAllTotalAttribute()
    {
        if(is_numeric($this->field_total)==false) {
            $field_total=0;
        }else{
            $field_total=$this->field_total;
        }

        $result =  $field_total*2;

        return ($result == 0 ? '' : $result);
    }

**Image**
image

Result will calculated when update field_a, field_b, field_d, field_e, field_g and field_h.

### CODE REVIEW

**Comment by bennothommo** [comment]
@meesiris would you mind explaining what this PR is intending to solve in more detail?

The way this is implemented, I am concerned that there is the potential for infinite loops if fields depend on one another. Also, 3 levels seems rather arbitrary.

**Comment by meesiris** [comment]
You can imagin if Level 1 have fields more than 100 fields. I need to add all into dependsOn of field_total and field_all_total. If I change something on Level 1. I also need to change it to all level. 

Example

If I change formular.

From
Level 1: field_a + field_b = field_c

To
Level 1: field_a + field_b + field_z= field_c

This is original YAML before implement. 

    fields:
        # Level 1: field_a + field_b + field_z= field_c
        field_a:
            label: field_a
            span: left
            type: number
        field_b:
            label: field_b
            span: left
            type: number
        field_z:
            label: field_z
            span: left
            type: number
        field_c:
            label: field_c
            span: left
            type: number
            dependsOn:
                - field_a
                - field_b
                - field_z
            readOnly: true

        # Level 1: field_e + field_e = field_f
        field_d:
            label: field_d
            span: left
            type: number
        field_e:
            label: field_e
            span: left
            type: number
        field_f:
            label: field_f
            span: left
            type: number
            dependsOn:
                - field_d
                - field_e
            readOnly: true

        # Level 2: (field_c*2)+(field_f*2) = field_total
        field_total:
            label: field_total
            span: left
            type: number
            dependsOn:
                - field_a
                - field_b
                - field_z
                - field_d
                - field_e
            readOnly: true

        # Level 3: field_total*2 = field_all_total
        field_all_total:
            label: field_all_total
            span: left
            type: number
            dependsOn:
                - field_a
                - field_b
                - field_z
                - field_d
                - field_e
            readOnly: true


After implement, I just add field_z to fields and add field_z into dependsOn of field_c. No need to add it into field_total and field_all_total. Please review YAML.

    fields:
        # Level 1: field_a + field_b + field_z= field_c
        field_a:
            label: field_a
            span: left
            type: number
        field_b:
            label: field_b
            span: left
            type: number
        field_z:
            label: field_z
            span: left
            type: number
        field_c:
            label: field_c
            span: left
            type: number
            dependsOn:
                - field_a
                - field_b
                - field_z
            readOnly: true

        # Level 1: field_e + field_e = field_f
        field_d:
            label: field_d
            span: left
            type: number
        field_e:
            label: field_e
            span: left
            type: number
        field_f:
            label: field_f
            span: left
            type: number
            dependsOn:
                - field_d
                - field_e
            readOnly: true

        # Level 2: (field_c*2)+(field_f*2) = field_total
        field_total:
            label: field_total
            span: left
            type: number
            dependsOn:
                - field_c
                - field_f
            readOnly: true

        # Level 3: field_total*2 = field_all_total
        field_all_total:
            label: field_all_total
            span: left
            type: number
            dependsOn:
                - field_total
            readOnly: true


I develop web application about Accounting, Tax and Financial planning. I have income and outcome per day/week/month/year, Investment etc. to caculate. I think it easier after implement 3 levels. 



In october.form.js. 

Prepare fieldmap, add next fields

        $.each(fieldMap, function(index, depend){
            if(fieldMap[index].hasOwnProperty('fields')) {
                if(fieldMap[depend.fields[0]]) {
                    fieldMap[index].fieldsNext = [],
                    fieldMap[index].fieldsNext.push(fieldMap[fieldMap[index].fields[0]])
                }

            }
        })



I have condition to check on Level 2 existed before go next to Level 3

Prepare variable

        if(toRefresh.hasOwnProperty('fieldsNext')) {
            var fieldNameLv2 = toRefresh.fieldsNext[0].fields[0],
            toRefreshLv2 = toRefresh.fieldsNext[0]

                if(toRefresh.fieldsNext[0].hasOwnProperty('fieldsNext')) {
                    var fieldNameLv3 = toRefresh.fieldsNext[0].fieldsNext[0].fields[0],
                    toRefreshLv3 = toRefresh.fieldsNext[0].fieldsNext[0]
                }
        }

Apply

        if(fieldNameLv2) {
            if (this.dependantUpdateTimers[fieldNameLv2] !== undefined) {
               window.clearTimeout(this.dependantUpdateTimers[fieldNameLv2])
            }

            this.dependantUpdateTimers[fieldNameLv2] = window.setTimeout(function() {
                var refreshData = $.extend({},
                    toRefreshLv2,
                    paramToObj('data-refresh-data', self.options.refreshData)
                )

                formEl.request(self.options.refreshHandler, {
                    data: refreshData
                }).success(function() {
                    self.toggleEmptyTabs()
                })
            }, this.dependantUpdateInterval)

            if(fieldNameLv3) {
                if (this.dependantUpdateTimers[fieldNameLv3] !== undefined) {
                    window.clearTimeout(this.dependantUpdateTimers[fieldNameLv3])
                 }

                this.dependantUpdateTimers[fieldNameLv3] = window.setTimeout(function() {
                    var refreshData = $.extend({},
                        toRefreshLv3,
                        paramToObj('data-refresh-data', self.options.refreshData)
                    )

                    formEl.request(self.options.refreshHandler, {
                        data: refreshData
                    }).success(function() {
                        self.toggleEmptyTabs()
                    })
                }, this.dependantUpdateInterval)
            }
        }

Loading indicator

        if(toRefreshLv2) {
            $.each(toRefreshLv2.fields, function(index, field) {
                fieldElements.filter('[data-field-name="'+field+'"]:visible')
                    .addClass('loading-indicator-container size-form-field')
                    .loadIndicator()
            })

            if(toRefreshLv3) {
                $.each(toRefreshLv3.fields, function(index, field) {
                    fieldElements.filter('[data-field-name="'+field+'"]:visible')
                        .addClass('loading-indicator-container size-form-field')
                        .loadIndicator()
                })
            }
        }


I think should not infinite loops.

**Comment by LukeTowers** [comment]
I feel like the correct way of handling this rather than this arbitrary 3 levels terminology and duplicated code is to just make sure that a change event is triggered on dependent fields when they're updated

**Comment by daftspunk** [comment]
This should be easy enough to fix, however, this is a complex case and will require some preparation on your side. Please submit a Pull Request to the [test plugin for investigation](https://github.com/octoberrain/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions on how to replicate it *using the test plugin*.

**Comment by meesiris** [comment]
Thank you @LukeTowers  for advice about triggered. I revert code to original and add trigger after updated field in this commit. https://github.com/octobercms/october/pull/5519/commits/b04363ead7acfdb6cb549f5a17992eadd122393d. It work like a charm.

I have test with following information .

Command list
```
php artisan create:plugin Meesiris.Plan
php artisan create:model Meesiris.Plan Dependency
php artisan create:controller Meesiris.Plan Dependencies
```
create_dependencies_table.php
```
<?php namespace Meesiris\Plan\Updates;

use Schema;
use October\Rain\Database\Schema\Blueprint;
use October\Rain\Database\Updates\Migration;

class CreateDependenciesTable extends Migration
{
    public function up()
    {
        Schema::create('meesiris_plan_dependencies', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->string('cus_name');
            $table->integer('per_income_per_day');
            $table->integer('per_income_per_month');
            $table->integer('per_income_per_year');
            $table->integer('per_income_total');
            $table->integer('per_expense_per_day');
            $table->integer('per_expense_per_month');
            $table->integer('per_expense_per_year');
            $table->integer('per_expense_total');
            $table->integer('per_balance_total');
            $table->integer('fam_income_per_day');
            $table->integer('fam_income_per_month');
            $table->integer('fam_income_per_year');
            $table->integer('fam_income_total');
            $table->integer('fam_expense_per_day');
            $table->integer('fam_expense_per_month');
            $table->integer('fam_expense_per_year');
            $table->integer('fam_expense_total');
            $table->integer('fam_balance_total');
            $table->integer('all_balance_total');
            $table->timestamps();
        });
    }

    public function down()
    {
        Schema::dropIfExists('meesiris_plan_dependencies');
    }
}
```

Model: Dependency.php

```
<?php namespace Meesiris\Plan\Models;

use Model;

/**
 * Dependency Model
 */
class Dependency extends Model
{
    use \October\Rain\Database\Traits\Validation;

    /**
     * @var array Validation rules for attributes
     */
    public $rules = [];

    /**
     * @var string The database table used by the model.
     */
    public $table = 'meesiris_plan_dependencies';

    /**
     * @var array Attributes to be cast to Argon (Carbon) instances
     */
    protected $dates = [
        'created_at',
        'updated_at'
    ];

    public function getPerIncomeTotalAttribute()
    {
        $result = ($this->per_income_per_day*365)
                +($this->per_income_per_week*52)
                +($this->per_income_per_month*12)
                +($this->per_income_per_year*1);
        return  $result;
    }

    public function getPerExpenseTotalAttribute()
    {
        $result = ($this->per_expense_per_day*365)
                +($this->per_expense_per_week*52)
                +($this->per_expense_per_month*12)
                +($this->per_expense_per_year*1);
        return  $result;
    }

    public function getPerBalanceTotalAttribute()
    {
        return  $this->per_income_total-$this->per_expense_total;
    }

    public function getFamIncomeTotalAttribute()
    {
        $result = ($this->fam_income_per_day*365)
                +($this->fam_income_per_week*52)
                +($this->fam_income_per_month*12)
                +($this->fam_income_per_year*1);
        return  $result;
    }

    public function getFamExpenseTotalAttribute()
    {
        $result = ($this->fam_expense_per_day*365)
                +($this->fam_expense_per_week*52)
                +($this->fam_expense_per_month*12)
                +($this->fam_expense_per_year*1);
        return  $result;
    }

    public function getFamBalanceTotalAttribute()
    {
        return  $this->fam_income_total-$this->fam_expense_total;
    }

    public function getAllBalanceTotalAttribute()
    {
        return   $this->per_balance_total+$this->fam_balance_total;
    }


}

```

columns.yaml

```
columns:
    cus_name:
        label: cus_name
        type: text
    all_balance_total:
        label: all_balance_total
        type: number
```
fields.yaml

```
# ===================================
#  Form Field Definitions
# ===================================

fields:
    cus_name:
        label: Customer Name
        type: text
        span: left
    per_income_per_day:
        label: Personal income per day
        type: number
        span: left
    per_income_per_month:
        label: Personal income per month
        type: number
        span: left
    per_income_per_year:
        label: Personal income per year
        type: number
        span: left
    per_income_total:
        label: Personal income total
        type: number
        span: left
        dependsOn:
            - per_income_per_day
            - per_income_per_month
            - per_income_per_year
        readOnly: true
    per_expense_per_day:
        label: Personal expense per day
        type: number
        span: left
    per_expense_per_month:
        label: Personal expense per month
        type: number
        span: left
    per_expense_per_year:
        label: Personal expense per year
        type: number
        span: left
    per_expense_total:
        label: Personal expense total
        type: number
        span: left
        dependsOn:
            - per_expense_per_day
            - per_expense_per_month
            - per_expense_per_year
        readOnly: true
    per_balance_total:
        label: Personal balance total
        type: number
        span: left
        dependsOn:
            - per_income_total
            - per_expense_total
        readOnly: true
    fam_income_per_day:
        label: Family income per day
        type: number
        span: left
    fam_income_per_month:
        label: Family income per month
        type: number
        span: left
    fam_income_per_year:
        label: Family income per year
        type: number
        span: left
    fam_income_total:
        label: Family income total
        type: number
        span: left
        dependsOn:
            - fam_income_per_day
            - fam_income_per_month
            - fam_income_per_year
        readOnly: true
    fam_expense_per_day:
        label: Family expense per day
        type: number
        span: left
    fam_expense_per_month:
        label: Family expense per month
        type: number
        span: left
    fam_expense_per_year:
        label: Family expense per year
        type: number
        span: left
    fam_expense_total:
        label: Family expense total
        type: number
        span: left
        dependsOn:
            - fam_expense_per_day
            - fam_expense_per_month
            - fam_expense_per_year
        readOnly: true
    fam_balance_total:
        label: Family balance total
        type: number
        span: left
        dependsOn:
            - fam_income_total
            - fam_expense_total
        readOnly: true
    all_balance_total:
        label: All balance total
        type: number
        span: left
        dependsOn:
            - per_balance_total
            - fam_balance_total
        readOnly: true
```

Thank you @daftspunk . https://github.com/octoberrain/oc-test-plugin is a perfect learning center for me.

**Comment by meesiris** [comment]
Remove ; after trigger.

**Comment by daftspunk** [comment]
Glad to hear you got it sorted. Thanks for using October CMS!

**Pull request closed without merging**
