### PR TITLE
use regex to hide files under media manger

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please explain why this is necessary.

**Comment by ctf0** [comment]
under media manager u have to specify each new file in order to ignore it, which with regex all the dot files will be ignored by default

**Comment by daftspunk** [comment]
I like ignoring dot files, can't think of any reason why the config might be needed. An event hook might be better but that can be omitted for now.

**Comment by daftspunk** [comment]
Wasn't aware config already existed, my bad. This looks good.

**Pull request merged**
