### PR TITLE
Fix reset search button issues

### PR DESCRIPTION
**Pull request by vosco88**
Fix for #4067.

- pulled reset search button css out of the toolbar css
- height and padding adjusted

### CODE REVIEW

**Comment by w20k** [comment]
@Rike-cz, could you test this fix, and ping @LukeTowers if everything is fine.
Please, add screenshots. 
Thanks!

**Comment by vosco88** [comment]
I can do some screenshots tommorow

**Comment by Rike-cz** [comment]
**List widget** is good.
list

**Relation list** has padding only 5px, as you can see here: https://github.com/octobercms/october/blob/2dbc56aead2ef2355135349b83860457f48f6235/modules/backend/behaviors/relationcontroller/assets/less/relation.less#L20-L23
So result is little different.
relation

**Relation manager/Record finder** still missing.
record-finder

**Comment by vosco88** [comment]
@Rike-cz strange, because also the relation manager was working for me. Will check it in the evening, but it was definitely working :)

**Comment by Rike-cz** [comment]
Sorry, my bad! You removed also `.control-toolbar`. A will edit post above.

**Comment by vosco88** [comment]
I've tinkered with it a bit more here are the results:

Regular list:
image

Relation list:
image

Record Finder:
image

Feel free to comment and test @Rike-cz :)

**Comment by Rike-cz** [comment]
Now it's ok for me, thank you!

**Comment by vosco88** [comment]
@w20k @LukeTowers seems to be working fine for me and also @Rike-cz

**Pull request merged**
