### PR TITLE
Update AuthManager.php

### PR DESCRIPTION
**Pull request by marschiaan**
Get translated string of permission->tab to make it sortable in correct order in Backend\FormWidgets\PermissionEditor

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why is this change required?

As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by LukeTowers** [comment]
Also, please do not submit PRs to the master branch, only to the develop branch. I've changed it this time for you but please keep that in mind next time.

**Comment by marschiaan** [comment]
Sorry for that, i still have to learn how github is working.

**Bug Summary:** Permission-Tabs and related permissions get not displayed in correct order

**Request location:** backend/backend/usergroups/update/2 (inside the Permissionseditor)

**Expected behavior:** The Permission Tabs and related permissions in Permissioneditor should get displayed in alphabetic sorted order.

Steps to reproduce: Go to `File Modules\Backend\FormWidgets\Permissioneditor.php` inside `function prepareVars()` and make a dump on `BackendAuth::listTabbedPermissions();`

it will give back an array like this:
```
array:7 [▼
  "cms::lang.permissions.name" => array:7 [▶]
  "rainlab.pages::lang.page.tab" => array:4 [▶]
  "rainlab.user::lang.plugin.tab" => array:29 [▶]
  "system::lang.permissions.name" => array:9 [▶]
  "rainlab.builder::lang.plugin.name" => array:1 [▶]
  "rainlab.location::lang.plugin.name" => array:1 [▶]
  "rainlab.translate::lang.plugin.tab" => array:2 [▶]
]
```

By the required change in `Modules\Backendend\Classes\AuthManager.php`, the dump gives back an array like this:

```
array:7 [▼
  "CMS" => array:7 [▶]
  "Pages" => array:4 [▶]
  "Users" => array:29 [▶]
  "System" => array:9 [▶]
  "Builder" => array:1 [▶]
  "Location" => array:1 [▶]
  "Translation" => array:2 [▶]
]
```

Now i have in `File Modules\Backend\FormWidgets\Permissioneditor.php` function `preparevars()` an array with readable names for tabs and related permission which can get sorted now in expected order by adding following code to function `preparevars()`.

```
$tabbedPermissions = BackendAuth::listTabbedPermissions();
 ksort($tabbedPermissions);

 foreach($tabbedPermissions as $permission => $obj)
{
     usort($obj, function($a, $b)
     {
       return strcmp(Lang::get($a->label), Lang::get($b->label));
     });
     $permissions[$permission] = $obj;
}

$this->vars['permissions'] = $permissions;
```

**Comment by daftspunk** [comment]
Language strings should be parsed as late as possible (close to the view as possible). The array is supposed to show language keys if they are used. This PR means the language string is parsed twice. Not sure why this is needed. Please explain at a high level, this explanation is too low level.

Eg: I have these permissions: X, Y, Z
They should be in this order: Z, Y, X
Instead they are in this order: Y, Z, X

**Pull request closed without merging**
