### PR TITLE
Update RelationController.php

### PR DESCRIPTION
**Pull request by FrancescoPassanti**
If I have a external key that is not Integer, i have this javascript error:

`create:1 Uncaught ReferenceError: YSL31661 is not defined`

YSL31661 is a VARCHAR reference key.

I have not tried the other methods like 'clickManagePivotListRecord'

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
@FrancescoPassanti could you test it with the other methods to make sure we fix the issues all at once?

**Comment by FrancescoPassanti** [comment]
Hi Luke,
Sorry for my mistake. The next time i will be more accurate.
Tomorrow i will simulate the other methods.

F

Inviato da iPhone

**Comment by FrancescoPassanti** [comment]
Good Morning Luke,
I confirm that all methods do not work.

$defaultOnClick = sprintf(
    "$.oc.relationBehavior.clickViewListRecord(:%s, '%s', '%s')",
    $this->relationModel->getKeyName(),
    $this->relationGetId(),
    $this->relationGetSessionKey()
);

if ($this->viewMode == 'single') {
    $config->showCheckboxes = false;
    $config->recordOnClick = sprintf(
        "$.oc.relationBehavior.clickManageListRecord(:%s, '%s', '%s')",
        $this->relationModel->getKeyName(),
        $this->relationGetId(),
        $this->relationGetSessionKey()
    );
}
elseif ($isPivot) {
    $config->recordOnClick = sprintf(
        "$.oc.relationBehavior.clickManagePivotListRecord(:%s, '%s', '%s')",
        $this->relationModel->getKeyName(),
        $this->relationGetId(),
        $this->relationGetSessionKey()
    );
}

All :%s Should be ':%s'

Thanks for your work and was a pleasure to meet you.

F

**Comment by LukeTowers** [comment]
@FrancescoPassanti could you make the fixes to the other methods as well in this PR then?

**Comment by w20k** [comment]
@LukeTowers, did a quick check, couldn't find any other spots 👍

**Comment by LukeTowers** [comment]
@w20k same with me, hence why I merged it :) Thanks for double checking though, I always appreciate that!

**Pull request merged**
