### PR TITLE
Remove composer.lock from .gitignore

### PR DESCRIPTION
**Pull request by MatissJanis**
This file should be included in the codebase so that all developers get exact copies of libraries and their corresponding versions.

Explained in more detail [here](https://blog.engineyard.com/2014/composer-its-all-about-the-lock-file).

### CODE REVIEW

**Comment by daftspunk** [comment]
[This has been discussed before](https://github.com/octobercms/october/issues/922), still unsure why other projects don't include composer.lock. There hasn't been any issues with packages not respecting semantic versions in the past. This fixes a problem that doesn't really exist at this point in time. Although it is good to know we have this solution if we need it some day.

**Comment by MatissJanis** [comment]
October is based on Laravel. Since Laravel does not ignore the `composer.lock` file, neither should we ignore it. 

https://github.com/laravel/laravel/commit/3c9d67ad657290c889969c85867677f35e6ae8f1

**Comment by daftspunk** [comment]
I don't see it in the repo: https://github.com/laravel/laravel

**Comment by MatissJanis** [comment]
Yes, they do not ignore it, but at the same time they do not commit it either.

They do not commit it because this would introduce unneccessary clutter in the codebase, **but** at the same time it is not ignored because other developers (those who do not contribute to the Laravel repo) may have multiple servers/machines on which this code is running on. The lock file helps all of these machines have the same exact version of Laravel.

So esentially - contributors must ignore this file locally, but everyone else should commit the lock file up to their private repositories.

I'd suggest that October takes the same approach.

**Comment by mplodowski** [comment]
I also think October should not ignore composer.lock file.

I had an issue with memory limit error on my production machine when I didn't push composer.lock file and run "composer update" command. Composer use that way a lot of memory, sometimes over 1GB.

Solution for this problem is to have composer.lock file on server and run "composer install" command.

I deploy my October apps from git repositiories, so for default composer.lock file is not present there.

I always end up with copying composer.lock file by hand.

**Comment by daftspunk** [comment]
If this results in PRs trying to commit a composer.lock file then we will have to put it back.

**Pull request merged**
