### PR TITLE
Add option for Richeditor to upload files as attachmany relation

### PR DESCRIPTION
**Pull request by joakimbo**
This will add the option for users to define a relation for files uploaded through the richeditor.

Implemented:
- Users can upload files as relation through the richeditor
- Users can delete uploaded relational files through the browse popup
- Users can select(insert) attached files through the browse popup

Known issues:
- Width of row in popup makes table too wide

### CODE REVIEW

**Comment by joakimbo** [comment]
@LukeTowers I'm unsure if it would work in the case of the richeditor but I saw that the Froala options could be [edited after init](https://github.com/froala/wysiwyg-editor/issues/778#issuecomment-142609365) would it be better to add a new js with something the following
```
+function ($) { "use strict";
    $(document).render(function() {
        if ($.FroalaEditor) {
            $('.field-richeditor textarea').on('froalaEditor.initialized', function (e, editor) {
                editor.opts.someParam = someValue;

            });
        }
    })
}(window.jQuery);
```
rather than needing to rebuild the build.min.js?

**Comment by LukeTowers** [comment]
@joakimbo @daftspunk would need to run the build process to rebuild build.min.js, which would probably work the best.

**Comment by joakimbo** [comment]
@LukeTowers What do you think about moving this:
```
// richeditor.js
// File upload
froalaOptions.imageUploadURL = froalaOptions.fileUploadURL = window.location
froalaOptions.imageUploadParam = froalaOptions.fileUploadParam = 'file_data'
froalaOptions.imageUploadParams = froalaOptions.fileUploadParams = { X_OCTOBER_MEDIA_MANAGER_QUICK_UPLOAD: 1 }
```
into the mediamanager.js plugin (editing the froala .opts directly), say in its _init func or a private func which then gets called from the init?
The "upload as relation" could then be moved into a plugin which would be included in the build.min and we simply check which mode is activated in richeditor.js and turn off the other plugin?

**Comment by joakimbo** [comment]
I can see that the imageManager froala plugin is omitted from the build.js, any specific reason for this? It would be beneficial if the relationUploader could make use of this for managing images. instead of writing a new manager.

**Comment by LukeTowers** [comment]
@joakimbo could the options be the following:
```
mode: [relation | medialibrary] Method of storing uploaded images
relation: Name of relation (use relation instead of relationName since that's what's use elsewhere in October already, relation also needs to be an attachmany relationship)
```
Also it would be nice if you wrote the code leaving it open enough for the addition of other parameters in the future (perhaps `mediaPath` and `mediaDisk` as well?) Those wouldn't need to be implemented right away though.

**Comment by joakimbo** [comment]
@LukeTowers Sure, I'll see about changing the options part later, a bit curious what you would want to achieve with mediaPath and mediaDisk though, the media manager is handled through config files and my thought is that the relation would handle the disk and path for relations.

**Comment by LukeTowers** [comment]
@joakimbo say you wanted to store and manage all the files uploaded through a specific richeditor field through it's own mediamanager disk and/or folder

**Comment by joakimbo** [comment]
@LukeTowers That would require some changes to the MediaManager widget and MediaLibrary class right? Since the MediaLibrary acts as singleton, we would need to either temporarily override the disk/folder or we need to be able to create several medialibraries. If this is done we could however use the mediamanager to handle relational files aswell?

**Comment by LukeTowers** [comment]
@joakimbo basically the way to do it right now is to dynamically set the config values for the media library before instantiating it, although to properly implement such a feature in the future we may need to make changes to the MediaLibrary class to make it easier. 

And yes, the path options would only be available for the mediamanager, the fileupload is it's own set of functionality.

**Comment by joakimbo** [comment]
@LukeTowers The basic functionality should now be available, I'm sure there are places where some optimization could be good but a more direct problem is that the content (table data) in the popup modal overflows outside of the modal, where would be the best place to put css to remedy this problem?

**Comment by LukeTowers** [comment]
@joakimbo let me know when it's ready to review. Also, screenshots of the new functionality would be greatly appreciated! :)

**Comment by joakimbo** [comment]
@LukeTowers I think it's ready for a first review now.
New functionality is basically just a record list of attachMany files.
image
This opens in the same way the mediaManager does by clicking the browse (folder icon) in the image or file insert of the richeditor.

**Comment by LukeTowers** [comment]
@joakimbo would it make sense to instantiate a FileUpload form widget directly attached to the RichEditor widget instead to handle that part of the upload so that the UX is more consistent?

**Comment by joakimbo** [comment]
@LukeTowers Hmm, I do agree that it would make sense, my starting point was simply to try and mimic how the mediaManager handled the uploads for the richeditor. The only thing to figure out would be how to "properly" instantiate and attach it but also to hook into insert and delete to be able to pull information necessary about the files for textarea.

**Comment by LukeTowers** [comment]
Awesome @joakimbo, I appreciate all your work on this!

**Comment by joakimbo** [comment]
@LukeTowers So I've gotten the widget to work however if we want to capture selections in the widget we would need to create a new fileupload.php (could inherit from original) and its respective js and partials right?

**Comment by LukeTowers** [comment]
@joakimbo not necessarily, if you can bind / initialize it as a widget attached to the richeditor widget instance it should in theory work correctly without having to do too much custom work.

**Comment by joakimbo** [comment]
@LukeTowers Hi, sorry not updating this. I have been busy for some time now but if this has yet to be solved by some other means then I am still interested. I would however need to re-acquaint myself with the code and most likely wont have time until closer to the holidays.

**Pull request closed without merging**
