### PR TITLE
Improved exception beautifier plugin

### PR DESCRIPTION
**Pull request by gabsource**
Improves the backend event preview page : 
- Keep the raw message in another tab
- Added a button to show/hide the stacktrace
- Fixes Windows paths parsing
- Translate the page title

#### Initial state
image

#### Mouse hover
image

#### Deployed
image

#### Raw
image

### CODE REVIEW

**Comment by daftspunk** [comment]
Did you notice the [Select the source code editor to use] popup appears twice when you click on a file path? One on top of the other.

**Comment by gabsource** [comment]
Seems like I can't reproduce. Does a produce a duplicate in the DOM ? I have only one in mine, even if I click fast.

But I get a strange nesting though 
image

**Comment by daftspunk** [comment]
Watch the animation and see the double box shadow. It is more than likely caused by the double up on `modal-content > modal-dialog > modal-content > modal dialog`

It should be `modal-content > modal-dialog`

**Comment by gabsource** [comment]
Yes I added the `modal-dialog` in the content provided to `$.popup`, it should only start with `modal-content`. I open the PR to fix it.

**Pull request merged**
