### PR TITLE
Hide any blank menu items in the top navigation

### PR DESCRIPTION
**Pull request by ayumihamsaki**
See github issue: https://github.com/octobercms/october/issues/4491

p.s. I inlined the javascript so it can happen straight away and not show a delay.

### CODE REVIEW

**Comment by Samuell1** [comment]
This should be fixed in menu parser code not in js.

**Comment by ayumihamsaki** [comment]
> This should be fixed in menu parser code not in js.

Yah totally agree with you!

**Comment by ayumihamsaki** [comment]
@Samuell1 

> This should be fixed in menu parser code not in js.

Yah totally agree with you!

Do you want to create a pr to patch the parser side for that and I will close this one.

**Comment by bennothommo** [comment]
@ayumihamsaki I agree with @Samuell1 - this should happen in the PHP side. I'll put details of where to begin in the original issue and close this PR.

**Comment by ayumihamsaki** [comment]
Thanks

**Pull request closed without merging**
