### PR TITLE
Add additional test cases for PluginManager

### PR DESCRIPTION
**Pull request by bennothommo**
- Add dependency tests
- Add tests that check wrong casing in requirements
- Clean up current tests
- Provides test case for https://github.com/octobercms/october/pull/4337

### CODE REVIEW

**Review by LukeTowers — APPROVED** [review]
LGTM. Could you add the explicit `void` return types (if that's supported on the current PHPUnit version) to the setUp and tearDown methods as required by the latest PHPUnit?

**Comment by bennothommo** [comment]
No worries, done @LukeTowers

**Comment by w20k** [comment]
LGTM @bennothommo! Awesome as always 👍

**Review by w20k — APPROVED** [review]

**Comment by bennothommo** [comment]
Cheers guys :D

**Pull request merged**
