### PR TITLE
fix bug:the 'width' style in backend columns.yaml won't work when use…

### PR DESCRIPTION
**Pull request by matthew188**
…  chrome

### CODE REVIEW

**Comment by w20k** [comment]
Could you provide screenshots before/after ?

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
@matthew188 as @w20k said, please post before and after screenshots.

**Comment by LukeTowers** [comment]
Also you aren't supposed to directly edit the compiled files, make the changes in the appropriate LESS file and then run `php artisan october:util compile less`

**Comment by matthew188** [comment]
ok ，thanks for remind，i will close the request and give an appropriate one。

**Pull request closed without merging**
