### PR TITLE
Check user permission for Mediafinder

### PR DESCRIPTION
**Pull request by gergo85**
Issue: #4216

### CODE REVIEW

**Comment by mjauvin** [comment]
Looks like a decent fix to me.

**Comment by LukeTowers** [comment]
@mjauvin were you able to test it?

**Comment by mjauvin** [comment]
@LukeTowers Yes, tested and works fine.

I think this is a good approach as it only makes the field "readonly" when user does not have permission to edit.

**Comment by LukeTowers** [comment]
Fixed in https://github.com/octobercms/october/commit/85fadbfef32b08a30b82d7a12a5b2a70e3c63cfc

**Pull request closed without merging**
