### PR TITLE
Update the Moments and TimeZone Library from 2.13.0 to 2.22.2

### PR DESCRIPTION
**Pull request by ayumihamsaki**
## Moments.js

(Old Version) 2.13.0 on 18 Apr 2016

(New Version) 2.22.2 on 1 Jun 2018

(Used non-min version as per request)

## Moments with TimeZones

(Old Version) 0.5.3 on 24 Mar 2016

(New Version) 0.5.23 on 29 Oct 2018

(Used non-min version as per request)

## Moments.js Locale

(Old) There were 100 Files

(New) There are now 123 Files

*Ready to sent to testers for checking now.

### CODE REVIEW

**Comment by w20k** [comment]
@ayumihamsaki could you, if 'github' supports, add PR patch to the ticket (create patch from commit). Would be much more easier to test ;)

**Comment by LukeTowers** [comment]
@w20k what are you talking about?

**Comment by w20k** [comment]
@LukeTowers, I mean, what is the best way to pull PR to your local machine? 

Easiest would be -> going to @ayumihamsaki forked rep, adding it to your local dev. and testing
And to create Patch from commits (in PhpStrom it's easy). For example: [$ git format-patch a_big_feature_branch -o patches
](https://mijingo.com/blog/creating-and-applying-patch-files-in-git)

**Comment by ayumihamsaki** [comment]
@w20k Hi is this ok ?

**Comment by w20k** [comment]
@ayumihamsaki Thank you very much! That helps ;) But I guess, shouldn't be a part of commit, try to attach it to ticket next time!

PS: Started writing smoke tests (not on PHP, JS cypress.io, for simple smoke tests works like charm 👍)

**Comment by ayumihamsaki** [comment]
Next time I will put the patch on the cloud and add the link to it on the pr for you.

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers 

Should I not update the lang files at the same time? I notice they contain moments.js locales inside them?

See folder: https://github.com/octobercms/october/tree/master/modules/system/assets/js/lang

**Comment by LukeTowers** [comment]
@ayumihamsaki update anything related at the same time. Remove the patch file though please.

**Comment by w20k** [comment]
@ayumihamsaki, I agree with @LukeTowers - update everything related to the JS module.

@ayumihamsaki , once again, thank you for adding Patch! Helps a lot!

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers Sorry I was tired last night and didn't finish writing my comment in full. I wanted to ask before updating those files.

Basically, October seems to have the exact same code in two places which doesn't make sense to me! There are the moments locales in one place and then the file is copied in the lang files. Before I go ahead and update these things I wanted to ask, would it not be better to remove the code from the lang files and just replace it with something like this:

```require('moment/locale/ar.js');```

e.g. like this:

untitled

Just updating those "compiled" files manually.

Then the code is not repeated twice and wasting space! Also in future updates, people only need to replace the moments library files and not have to update the lang files each time.

What do you think?

**Comment by LukeTowers** [comment]
@ayumihamsaki if we go the require route then it needs to be in the uncompiled source files, or brought in during compilation. I don't want the compiled files including a `require` statement in them.

**Comment by ayumihamsaki** [comment]
@LukeTowers @w20k 

Ok, updated everything and ready for testing now, sorry about that.

Have updated the lang files in relation to issue:  https://github.com/octobercms/october/issues/3808

Also the patches files I have made a separate repo, you can find them here for testing: https://github.com/ayumihamsaki/patches/tree/master/moments

**Comment by w20k** [comment]
Sorry, @ayumihamsaki  took me a while ;) Will finish it today!

**Comment by ayumihamsaki** [comment]
@w20k thanks, looks ready @LukeTowers to complete now.

**Pull request merged**
