### PR TITLE
Correctly display HTML entities in event log

### LINKED ISSUE #4558: Log output is parsed, not raw
If I do `Log::info('&amp;')`, I expect to see `&amp;` in `/admin/system/eventlogs`. However, I see `&`. Even if I look in the 'Raw' tab.

### PR DESCRIPTION
**Pull request by bennothommo**
Fixes #4558.

This changes the event log to use a partial for the log message which double-encodes the entity data. When using formatted view in the log viewer widget, the HTML entities are allowed by decoding back a step. When in raw view, the HTML entities are kept double-encoded.

This should still be safe from XSS vulnerabilities.

image

image

### CODE REVIEW

**Comment by w20k** [comment]
Had a fun evening of testing 😄 

Screenshot:
Screenshot 2019-09-05 at 19 26 21

Found one `odd` behavior:
Original line which was logged: `&lt;/C&gt;&lt;/X&gt;&lt;/xml&gt;&lt;SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML&gt;&lt;/SPAN&gt;`

_List view (last line):_
Screenshot 2019-09-05 at 19 27 08

_Item View:_
Screenshot 2019-09-05 at 19 27 14
Screenshot 2019-09-05 at 19 27 19

**Comment by bennothommo** [comment]
Cheers for that @w20k. Will have a look at that odd one. :)

**Comment by bennothommo** [comment]
@w20k Finally got around to fixing that tricky one. Should now be good to test and merge.

**Comment by w20k** [comment]
Formatted is shown in the list in here:
Screenshot 2019-10-10 at 11 36 06
Screenshot 2019-10-10 at 11 36 09
Screenshot 2019-10-10 at 11 36 13

But in this example vice versa:
Screenshot 2019-10-10 at 11 36 21
Screenshot 2019-10-10 at 11 36 36
Screenshot 2019-10-10 at 11 36 32

And why there is a `j` in the beginning of the formatted string 😄

**Comment by bennothommo** [comment]
@w20k Hmmm, interesting. Will take a look.

**Comment by bennothommo** [comment]
@w20k Would you mind pasting those two test strings here so I can test them?

**Comment by w20k** [comment]
Sure @bennothommo.
``

`&lt;/C&gt;&lt;/X&gt;&lt;/xml&gt;&lt;SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML&gt;&lt;/SPAN&gt;`
If you need could get you a MySQL dump ;)

**Comment by w20k** [comment]
@bennothommo ping me if anything else needed!

**Comment by bennothommo** [comment]
@w20k I've deployed a fix that should resolve the issue where the formatted version of the `` tag example was displaying incorrectly. As for the formatted string appearing in the event log for the `</C>` example, I think that's fine. As the string is already HTML-encoded, it is displaying the characters in the list in a safe way. The Lists widget - I assume - is using `htmlentities()` to sanitise the log messages, but because they're already entities, it's leaving them as is.

**Comment by w20k** [comment]
LGTM, @bennothommo I need to make one more test run and it's good for merging!

**Comment by w20k** [comment]
@bennothommo re-test, LGTM ;) I think it's better to move to release v461.

**Comment by mjauvin** [comment]
@bennothommo don't forget to add `completed` status

**Pull request merged**
