### PR TITLE
replace jquery-sortable with SortableJS

### PR DESCRIPTION
**Pull request by mjauvin**
test PR to allow testing this through OctoDock instance.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mjauvin did you run `compile assets` or `compile js`?

**Comment by mjauvin** [comment]
both, yes

--
Marc

**Comment by LukeTowers** [comment]
@mjauvin just run `compile js` please, `assets` recompiles the language files too

**Comment by LukeTowers** [comment]
Replaces #4777, fixes #3755

**Comment by LukeTowers** [comment]
@mjauvin I added the Pages plugin to the Octodock instance: https://e7995be26aa9.octodock.com:8443/backend/rainlab/pages

It looks like it's not supporting the nested sorting that's supposed to be supported for pages & menu items

**Comment by LukeTowers** [comment]
Also added the blog plugin and on https://e7995be26aa9.octodock.com:8443/backend/rainlab/blog/posts/import it lets you drag more than one database field to a given import file column:

Screen Shot 2019-11-27 at 4 42 55 PM

**Comment by daftspunk** [comment]
Just a heads up, this 566f138eabd8032aefc9aed84fe67ab4f8e6011f appears to fix the existing library so we may not need to go to the effort of replacing it

**Comment by mjauvin** [comment]
I confirm that @daftspunk work obsoletes this PR.

**Pull request closed without merging**
