### PR TITLE
remove wildcards as it shouldnt be listed under public

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by LukeTowers** [comment]
You've just broken the entire purpose of the `october:mirror public` command. This will not be accepted unless you can clearly explain why.

**Comment by ctf0** [comment]
all it does is that it doesnt sym-link the `plugin/module/theme` folders to public folder anymore because the outside world shouldnt get access to any of those.

also this doesnt break any of the cms functionality, u can still do everything as normal.

**Comment by LukeTowers** [comment]
It does break that functionality, because it's not linking `plugin/module/theme` folders, it's linking the `assets/resources` directories within those folders, which contain client assets like fonts, images, JS, and CSS. Without linking those directories, a blacklist approach will block access to those resources.

**Comment by ctf0** [comment]
in the matter of fact i have made a theme with some assets already and i call it through
```twig
<link href="{{ 'assets/css/app.css'|theme }}" rel="stylesheet">
```

**Comment by daftspunk** [comment]
@ctf0 Please take the time to familiarize yourself with the platform before submitting any more PRs. Not to discourage your enthusiasm because it's great!

**Pull request closed without merging**
