### PR TITLE
Add events for sign in and out backend user.

### PR DESCRIPTION
**Pull request by mplodowski**
Add events for sign in and out backend user.

Remove unused import.

### CODE REVIEW

**Comment by mplodowski** [comment]
I am afraid this alone is not enough.

This events cannot be listened in Plugin boot method. Any idea how to use those events in Plugin development?

The idea is to have a way to add custom functionality after user sign in and sign out.

**Comment by daftspunk** [comment]
Can you give more detail on you are trying to achieve?

**Comment by mplodowski** [comment]
In my plugin I created some session variables and I want to forget them when user is sign out. In Laravel Auth class there is an event for this and for sign in as well.

There is core module which logs when user sign in to backend. I would like to extend this with my plugin, add action column and log some other backend events along with sign in.

I think developers should be able to modify how CMS works with event handlers and not modify code itself and create PRs.

Currently this PR is no good, because this events are not fired when I bind them in plugin boot method or init.php.

**Comment by daftspunk** [comment]
You may want to set the `$elevated` property in your plugin base class to `true`, this will allow the event to work.

**Comment by daftspunk** [comment]
Perhaps fixed by #1796

**Pull request closed without merging**
