### PR TITLE
Replace old selenium functional testing for the new Laravel Dusk

### PR DESCRIPTION
**Pull request by arzola**
Hi OctoBros! 👊

I have updated the functional tests to meet the new Laravel dusk features and be able to test the CMS features and also provide to the users a powerful and easy way to test their plugins.

I added a `dusk` folder inside the config directory to be able to config the default service provider used by dusk and be able to easily integrate in any continuous integration platform.

I think this is a huge advantage to avoid the selenium nightmare, and provide to the users a super easy and natural functional testing.

The user only have to setup the enviroment to `APP_ENV=dusk` and done

image

### CODE REVIEW

**Comment by surahmans** [comment]
Wow, I loved your work!

**Comment by arzola** [comment]
Thanks bro 🤙

**Comment by arzola** [comment]
@LukeTowers i rebased the branch and now it's clean ;)

**Comment by LukeTowers** [comment]
This looks pretty interesting @arzola, I wish I had more time to review it! Perhaps @daftspunk can take a look?

**Comment by arzola** [comment]
Hey brother @daftspunk I think this is a good way to incentive more testing, maybe you will find this PR interesting 🤙🏻

**Comment by fuzzybaird** [comment]
I would love for this to get revisited. And make sure that it works when testing plugins.

**Comment by arzola** [comment]
@fuzzybaird works great with plugins :) it's the way that i do on my production enviroments

**Comment by LukeTowers** [comment]
@arzola could you add a PR to the documentation explaining how to use this for testing October and plugins?

**Comment by LukeTowers** [comment]
@arzola ping! ;)

**Comment by viamage** [comment]
@arzola do you plan on proceeding with it anytime soon? Merging this would allow us to proceed with https://github.com/octobercms/october/issues/3532 and thus resolve this https://github.com/octobercms/october/issues/3360

**Comment by LukeTowers** [comment]
@viamage this isn't necessarily a blocking PR, I would just like to move to using dusk over selenium but I'm not overly familiar with dusk so I'd need the documentation to be added.

**Comment by arzola** [comment]
Hello, This Saturday I can work on this :)

**Comment by viamage** [comment]
Cool! Yea you are right not really a blocker, but it's between upgrading phpunit to 7 with it, or to 6 without it - and as implementing dusk would be cool enhancement, I would wait for this with phpunit upgrade and make it 7.

**Comment by LukeTowers** [comment]
Awesome @viamage, look forward to hearing your thoughts!

**Comment by viamage** [comment]
Phew that took long. Basically and unfortunately I wouldn't advise to merge this PR as it is.

img

A lot of stuff changed since then. it's using Laravel Dusk 1.1, which is throwing errors with latest chrome :
```
unknown error: call function result missing 'value'
```

upgraded to ~2.0 in composer.json per googled tips (it's official stable version for larvel5.5) and it totally stopped working

hang <- after LONG time, results for each test were:

```
1) Tests\Browser\ExampleTest::testBasicExample
Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY"}}

Operation timed out after 30001 milliseconds with 0 bytes received
```

I disabled default headless mode, still, browser didn't even open and that didn't change a thing, seeing:

```
jin: ~ ➜ ps aux|grep chrome 
jin       1861  1.5  0.1 140452 15364 pts/3    Sl+  11:11   0:00 /home/jin/web/cleanocto/arzola/vendor/laravel/dusk/bin/chromedriver-linux
jin       1873  0.5  0.0      0     0 pts/3    Z+   11:11   0:00 [chrome] <defunct>
```
^this is google-chrome 65

Tried to upgrade chromedriver to latest version, nothing, looks like it's somehow huge issue
with some tickets open https://github.com/laravel/dusk/issues/10
and some closed, but with some crazy hacks around https://github.com/laravel/dusk/issues/440

Maybe it's my distro thing, but this problem happens on so many other distros that I doubt, rather latest chrome. Maybe it's fixable with proper DuskTest class but I don't have any more time today for this, will try to work some more on this later.

Would be cool if @arzola could update his branch so other people could pull it and test without manually updating composer.json to switch from "dev-develop" to "1.x" etc if no time I will try to prepare proper branch for this when I have some time later.

**Comment by arzola** [comment]
Yeah, on the weekend I'm going to update the branch and upgrade dusk

**Comment by jimcottrell** [comment]
@LukeTowers @daftspunk  Do you think that Dusk is the way forward? I was looking into October's functional testing the other day with the idea of submitting a test to verify some functionality, and I had some trouble getting set up with the existing code. After some research, updating the tests for Selenium WebDriver isn't too big a deal and fixes the issues I was having, so I don't know that there's a "Selenium nightmare" as described, but it seems like we do either need to update the existing tests or move to Dusk.

From what I understand Dusk runs by default directly via ChromeDriver but it can also use Selenium if needed. My concern with this PR would be that it seems to provide no way to use that functionality and limits testing to Chrome.

If Dusk is worth it and what we want to use it, I can lend some help to this PR, or I can submit a PR to update the Selenium usage of the existing tests. Ultimately, I would like to unblock the PHPUnit version bump, and either of these options would work. I personally lean towards sticking with Selenium, but I'm open to whatever the consensus is.

**Comment by LukeTowers** [comment]
@jimcottrell thanks for your interest! I would say for now we'll stick to selenium. I don't really use either of them enough to make a decision so I'd rather stick with what we have currently and just fix it up to resolve the issues. We can then look at integrating Dusk later when we have more interest in it.

**Comment by LukeTowers** [comment]
@jimcottrell are you still interested in getting the Selenium tests fixed up so we can bump the PHP Unit version?

**Comment by jimcottrell** [comment]
@LukeTowers I am still interested in that, yes. I haven't had a chance to dig into too much lately, but I should have some time coming up.

**Comment by LukeTowers** [comment]
Perfect, looking forwards to that @jimcottrell

**Comment by LukeTowers** [comment]
@jimcottrell has there been any progress on this?

**Comment by jimcottrell** [comment]
@LukeTowers Some, but I have to dig that up. I remember there were some decisions to make, and I wasn't sure which way I thought we should go on a couple of them.

**Comment by joejoe2010** [comment]
Hi everybody,
I'm new to octobercms and I've been following this pull request. In the following are some questions that I have:
- As far as I can see people are unsure whether to stay with phpunits/Selenium or to go with Lavarel Dusk. Would it be possible to offer both? (I'm tending a bit more towards Lavarel Dusk)
- Is it necessary to adapt the existing test cases when switching to Lavarel dusk?
- Does the change to Lavarel dusk only affect phpunit-Selenium tests or also unit tests?

Greetings
joejoe

**Comment by bennothommo** [comment]
@joejoe2010 To answer your questions:

- There are some changes that Laravel Dusk brings into the functionality tests that will make it incompatible with the current PHPUnit/Selenium setup, as seen in this PR's changes. So it would have to be a clean switch.
- Yes, any move would need to make sure that our current test coverage is still applied.
- I believe unit tests are still run through PHPUnit as before.

**Comment by arzola** [comment]
I will work on this to update dusk and testcases, I hope this time could be merged

**Comment by LukeTowers** [comment]
@arzola feel free to work on it off of the 5.9 branch

**Comment by joejoe2016** [comment]
Hi,
are there any news about this?
If I start a new october project: Should I use selenium or Laravel Dusk for setting up my test environment? Will it be possible to port Selenium tests to Laravel Dusk or will I have to rewrite my tests once this issue is solved?
Thanks

**Comment by bennothommo** [comment]
@joejoe2016 I know @arzola [stated](https://github.com/octobercms/october/pull/3051#issuecomment-501375683) that they were looking to do some more work on it, however, there's hasn't been any update since.

One thing I will mention is that we have done front-end tests in another way - using NPM and JSDOM as per [this PR](https://github.com/octobercms/october/pull/4576), so that's covering some of the front-end testing, which may make the need for Dusk less so.

**Comment by tobias-kuendig** [comment]
There's this plugin by inetis, that looks very promising:

https://github.com/inetis-ch/oc-testing-plugin

**Comment by joejoe2016** [comment]
Thanks for your feedback, I'll give it a try.

**Comment by LukeTowers** [comment]
Replaced by #4919

**Pull request closed without merging**
