### PR TITLE
move static menu item order btn to left

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by LukeTowers** [comment]
First problem, don't edit compiled files, edit the LESS source. Secondly, I'm going to auto-close any PRs without descriptions from now on.

**Comment by ctf0** [comment]
i didnt add desc as the title define the purpose, also u can keep it open and will push the less edits later

**Comment by LukeTowers** [comment]
You haven't explained why it is necessary.

**Comment by ctf0** [comment]
necessary because if u tried to reorder the menu item on wide screen u will feel lost between checking and re-checking if it is the right item to move , while now u have the icon right next to the item name which will make ur work much easir

**Comment by daftspunk** [comment]
This issue lacks enough detail or the replication instructions cannot be actioned easily. As per [the contribution guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#reporting-a-bug-with-octobercms), please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

Here is an example of a **bug summary**:

> The CMS page URL is not being set automatically from the title value.

Here is an example of some **reproduce steps**:

> 1. In the back-end, open the CMS > Pages section
> 1. Click the "Add" button
> 1. Enter [Hello] for the Title field
> 1. Click the Save button 

Here is an example of **expected behavior**:

> - The Title should be set to [Hello]
> - The URL should be set to [/hello]

Here is an example of **actual behavior**:

> - The Title is set to [Hello] correctly
> - The URL is left empty

**Pull request closed without merging**
