### PR TITLE
Added morphTo to list of singular relations

### PR DESCRIPTION
**Pull request by SeriousKen**
You can now use proxy fields in backend forms with morphTo relations.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Can you post a link to the original issue? Also could you submit a PR to the docs for the morphOne relationship?

**Comment by SeriousKen** [comment]
Fixes https://github.com/octobercms/october/issues/3807

**Comment by SeriousKen** [comment]
I'll have a look at the documentation, I'll see what's in Laravel's docs.

**Comment by SeriousKen** [comment]
There's an open ticket on Laravel's docs requesting missing docs for morphOne https://github.com/laravel/docs/issues/4696, I'll see if anything comes of that.

**Comment by LukeTowers** [comment]
@SeriousKen whatever Laravel adds we'll still need to have a section in the OctoberCMS docs on it anyways

**Comment by LukeTowers** [comment]
@SeriousKen would you be willing to write up an example for October's docs yourself?

**Comment by SeriousKen** [comment]
@LukeTowers I've got a bit of time to look at it, so I'll put something together.

**Comment by SeriousKen** [comment]
Ok @LukeTowers, that's done. Feel free to suggest any changes/corrections. Thanks to @driesvints who provided the update to Laravel docs. https://github.com/octobercms/docs/pull/337

**Pull request merged**
