### PR TITLE
Modified popup documentation

### PR DESCRIPTION
**Pull request by tschallacka**
Modfied popup documentation to have the proper data-request-handler in documentation.

Also added popup property content javascript api samples

### CODE REVIEW

**Comment by tschallacka** [comment]
https://github.com/octobercms/october/issues/1685#issuecomment-241560238

**Comment by daftspunk** [comment]
I thought we fixed `data-extra-data`?

**Comment by tschallacka** [comment]
You asked me to modify the documentation...

**Comment by daftspunk** [comment]
> https://octobercms.com/docs/ui/popup needs updating too

It was to explain this statement. All good!

**Pull request closed without merging**
