### PR TITLE
Update mustache.js from 2.0.0 to 2.3.2

### PR DESCRIPTION
**Pull request by ayumihamasaki2019**
See github issue: https://github.com/octobercms/october/issues/4643

Please can you merge this asap!

The hack is here: https://snyk.io/vuln/npm:mustache:20151207#snyk-patches

Attention: @LukeTowers @daftspunk as you may want to write a blog post telling people to do an update after it's merged.

### CODE REVIEW

**Comment by LukeTowers** [comment]
> Attention: @LukeTowers @daftspunk as you may want to write a blog post telling people to do an update after it's merged.

Please do your research before raising the hue & cry (see  https://github.com/octobercms/october/issues/4643#issuecomment-536059019), and please also follow our documented security policy when doing so: https://github.com/octobercms/october/security/policy

**Comment by ayumihamasaki2019** [comment]
@LukeTowers sorry Luke but I contacted October support about this issue two days ago and never got a response, so I posted it here to get some action. Thanks for merging it.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019 I never received any email from you so I suggest you take a closer look at the security policy. Also note that hello@octobercms.com is only monitored by @daftspunk and @alekseybobkov, both of which have minimal daily interactions with the project and have their own full time jobs so waiting a mere two days is not likely to get you a response. I would expect at least a week to get a response from that email.

**Comment by ayumihamasaki2019** [comment]
@LukeTowers not being a mind reader, would it be possible to tell people that the response times take over a week, see here (no mention):

image

**Comment by ayumihamasaki2019** [comment]
@LukeTowers @daftspunk @alekseybobkov 

Can I make a suggestion, having all default and security emails go to `hello@octobercms.com` is not too clever.

Surely it would make more sense to setup the following:

Security Issues: `security@octobercms.com` (response time 2 days)

General Issues: `hello@octobercms.com` (response time 7 days)

Also why not use a `security.txt` file?

For more information if you don't know, you can find here: https://securitytxt.org/

You basically add the txt file in this location: `https://octobercms.com/security.txt`

It contains basic infomation for pen testers and white hat hackers to contact you with security issues.

This is the normal way to handle security issues.

**Comment by LukeTowers** [comment]
@ayumihamasaki2019 that would not make sense to have a security.txt for octobercms.com as that would describe the security policy for the marketplace. The security policy for the OctoberCMS project itself is on GitHub, where it belongs. The response time issue is also already handled by asking people to send to both listed addresses, which was not followed in this case. Also, @daftspunk said that he did not see any security emails in that inbox.

**Comment by drmzio** [comment]
Probably off-topic but @ayumihamasaki2019 brings up an interesting point. There's also a possibility of the Marketplace having security issues as well. I suggest, if possible, have a dedicated email just for this case (e.g. `security@octobercms.com`) and have it automatically forward to @LukeTowers email address. Think of this new email address as a "catch-all" for any security issue with octobercms.com or the October source code. Just a suggestion.

cc: @alekseybobkov @daftspunk

**Comment by LukeTowers** [comment]
@drmzio I think the hello@octobercms.com email is fine for now for reporting anything related to the marketplace. Unfortunately I don't have any access or control over the marketplace codebase at all so sending it to me wouldn't really help besides having a more vocal presence to bug @daftspunk until he looks into it.

**Pull request merged**
