### PR TITLE
Add support for filters in pivot mode

### PR DESCRIPTION
**Pull request by mplodowski**
A little improvement to PR https://github.com/octobercms/october/pull/4241

### CODE REVIEW

**Comment by LukeTowers** [comment]
@alxy Could you test this?

**Comment by alxy** [comment]
@LukeTowers May be able to test this out next week.

**Comment by mplodowski** [comment]
I found two bugs at the moment, but I was unable to fix them.

The first seems to be related to original commit, when you try to search inside filter, it throws an error:

```
"A widget with class name 'relationProductsManageFilter' has not been bound to the controller" on line 598 of /modules/backend/Classes/Controller.php
```

The second is related to `number` and `numberrange` filter types. If the relation manager is opened inside popup window, you cannot set value of those inputs, it looks like they are disabled.

**Comment by alxy** [comment]
@mplodowski Do you get the first behavior even if not in pivot mode? These issues would need to be resolved, before this can be merge, however I won't be able to do this anytime soon.

The second issue seems to be javascript related - I remember having simlar issues as well.

**Comment by mplodowski** [comment]
@alxy Yes, the first behavior occurs even without pivot.

I will try to take a closer look into this soon.

**Comment by alxy** [comment]
@mplodowski You would probably apply this to the numberfilter js code as well: https://github.com/octobercms/october/pull/4204/commits/2cf7fbef27c166ff5a50f965dcb24432b1b3f5b7

**Comment by mplodowski** [comment]
@alxy I don't know what I should apply exactly? 

Can you help me to make it work?

**Comment by alxy** [comment]
Sorry, the number filter has been fixed by me, at least for the normal case, where the relation controller is opened on a regular page. (In the initial implementation the filters opened behing the manage popup. If there are now multiple popups which overlay each other, things get more complex....)

For the other error I have no idea what is happening there....

**Pull request closed without merging**
