### PR TITLE
Seperate proprietary and ocms js asset bundles

### PR DESCRIPTION
**Pull request by mjauvin**
Proposed change to seperate the proprietary asset files from the non-proprietary ones so that we can more easily maintain the non-proprietary asset files:

- register a new bundle
- add the new bundle target asset
- remove the non-proprietary source file from the proprietary bundle definition
- create a new build target for the non-proprietary asset files
- remove the non-proprietary code from the compiled proprietary asset

### CODE REVIEW

**Comment by mjauvin** [comment]
This will help greatly in properly test the proposed changes in #4059

**Comment by w20k** [comment]
@LukeTowers, works fine compiled and added to the `head`.

screenshot 2019-01-21 at 16 29 05

**Comment by LukeTowers** [comment]
I'll deal with this when I get to updating Froala

**Comment by mjauvin** [comment]
Hey guys, what's holding this from being merged?

**Comment by w20k** [comment]
@mjauvin my guess @LukeTowers should get back and update Froala first (when he has time to deal with that), then we could merge.

**Comment by LukeTowers** [comment]
@mjauvin @w20k is correct, I need to update Froala first. More accurately I need to find the time and motivation to do so. Feel free to keep reminding us until then though :)

**Comment by mjauvin** [comment]
Hey Luke, @daftspunk updated Froala (https://github.com/octobercms/october/commit/463008450b627864cb3906b29cb1690e7e4517fc), do you think you can merge this one? ;)

**Comment by LukeTowers** [comment]
@mjauvin rebuild it and sure :)

**Comment by mjauvin** [comment]
Looks like I still don't know how to properly bring an old PR up2date with its origin without all those commits to show up in my PR... is there a written procedure for this?! :roll_eyes:

**Comment by w20k** [comment]
Just merge dev into your branch or rebase :) As simple as that!

**Comment by mjauvin** [comment]
I did a merge and look what happened above... I should have done a rebase

**Comment by w20k** [comment]
Don't worry @mjauvin "squash and merge" will do the trick 😄

**Comment by mjauvin** [comment]
What do you mean @w20k ?

**Comment by w20k** [comment]
Screenshot 2019-03-31 at 21 20 21

**Comment by mjauvin** [comment]
Ok, you mean this is an option when merging the PR?

**Comment by w20k** [comment]
It's an option when merging PR :) So, if there weren't any conflicts with dev, the merge will show only your commits in the branch. And it will be always only single merge commit. 
_Sorry, haven't slept today)_

**Comment by mjauvin** [comment]
The only file I am not comfortable with is the "build-min.js" which I created manually by removing the build-ocms-min.js content from... but I have no other mean to rebuild it (@daftspunk would probably have to do this after/before the merge)

**Comment by LukeTowers** [comment]
Fixed the diff issue by changing the base branch to master and back to develop to force github to reevaluate the diff.

**Comment by LukeTowers** [comment]
@mjauvin can you rename the build-ocms.js file to build-oc-plugins.js?

**Comment by LukeTowers** [comment]
@w20k is this ready to merge?

**Comment by w20k** [comment]
@LukeTowers will run a few regression tests today, and good to be merged.

**Comment by mjauvin** [comment]
@w20k did you havet time to test this?

**Comment by w20k** [comment]
@mjauvin sorry for the delay was a bit busy at work for the past two days!

**Comment by w20k** [comment]
@mjauvin testing is done.
@LukeTowers someone with `froala_drm` should re-run the assets compiler.

Status - ✅

**Comment by mjauvin** [comment]
This commit (aeeb791899b4bbbddf114dfb24d01581022ec695) will require minified asset build-oc-plugins-min.js to be rebuilt in this PR

**Comment by mjauvin** [comment]
status update on this?

**Comment by LukeTowers** [comment]
Still waiting on @daftspunk

**Pull request merged**
