### PR TITLE
prevent from duplicate the backend url

### PR DESCRIPTION
**Pull request by panakour**
I did this on master branch because I have already open a pull request on develop branch #3277

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
What issue exactly is this PR solving?

**Comment by panakour** [comment]
If you create a page from the CMS wit the same url that the backoffice use, the system let you create it without any problem. The problem about this is that the page that has the same URL as the backend does not work and open the backend instead

**Comment by LukeTowers** [comment]
This isn't a robust enough solution to merge. This would only prevent assigning a page a URL that is exactly the Backend URL. A more robust solution is to get the full list of all registered routes and prevent assigning any of them, along with a more detailed error message letting people know why exactly they can't use a specific route.

**Comment by panakour** [comment]
@LukeTowers ok, I'll try to improve this.

**Comment by panakour** [comment]
@LukeTowers Now it's better approach for this problem. I have opened a new pull request for it.

**Pull request closed without merging**
