### PR TITLE
Added translation for pageTitle into MailBrandSettings

### PR DESCRIPTION
**Pull request by Samorai**
Resolving #3002

### CODE REVIEW

**Comment by jan-vince** [comment]
Hi, this is a good start - but there is a whole config file in ````/modules/system/models/mailbrandsetting/fields.yaml```` that needs to be translated.

And we also have to deal with ````/modules/system/models/mailbrandsetting/samle_template.html````. Texts inside should be translated with ````<?= e( trans(...) ) ?>````.

Have you time to include this in your PR?

**Comment by Samorai** [comment]
@jan-vince Hi, thanks.
I'll include that to my PR tonight. (EEST GMT +3)

**Comment by jan-vince** [comment]
It's not a race :) 

Thanks!

**Comment by LukeTowers** [comment]
I'll let @daftspunk review this since he's the one that has been putting a lot of work into the mail system recently

**Comment by jan-vince** [comment]
Hi @Samorai, I have tested this and it works form me. Great job!

*I just can not figure out how to align a 'Right-Aligned' cell to right side. It looks like MD table doesn't allow to change forced alignment. If so, we should probably change the text.*

**Comment by daftspunk** [comment]
Looks great! <3 you guys

**Pull request merged**
