### PR TITLE
Fixes broken richeditor z-index inside and outside of a popup

### PR DESCRIPTION
**Pull request by Fl0Cri**
Fixes both https://github.com/octobercms/october/issues/3098 and https://github.com/octobercms/october/issues/3111

By default Froala has a z-index of 1 (it's this setting that was raised to 1000 in a previous PR). Other components generated by the editor (including the popups) are rendered with an inline style computed based on this root z-index. For example, the popup is `[root z-index] + 4` but it doesn't directly needs the z-index of the editor itself.

Looking at what css rules are applied to the popup, we can see that there is a z-index of 9997 coming from here: https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/richeditor/assets/css/richeditor.css#L30

The problem is the inline z-index added by Froala that overrides the one in the css.
An `!important` should do the trick.

Note that I cannot build the richeditor assets because it needs a `froala_drm` directory in its vendors.
I tried to simulate the behaviour by tweaking the compiled files and I can confirm that it fixes both issues.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Awesome, thanks for doing this @Fl0Cri!

**Comment by TimFoerster** [comment]
Well it brakes  #3098 ...
screen shot 2017-10-23 at 02 28 57

**Comment by LukeTowers** [comment]
@TimFoerster is there a way that we can reset where the table popup gets it's z-index base from? I.e. make the richeditor position relative or something? This constant z-index fighting is getting ridiculous.

**Comment by Fl0Cri** [comment]
I have made a new PR that should fix the problem: https://github.com/octobercms/october/pull/3194
@TimFoerster can you have a try?

**Comment by TimFoerster** [comment]
@Fl0Cri I'll but I'm on the road right now. Will come back around Friday.

**Comment by TimFoerster** [comment]
nvm, i checked it quickly, looks good! thanks for your work
screen shot 2017-10-23 at 20 48 06

**Pull request merged**
