### PR TITLE
Update es-ar/lang.php

### PR DESCRIPTION
**Pull request by ezetojo**
Fix typos and linguistic usages.

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
You have a syntax error on line 6

**Comment by ezetojo** [comment]
Sorry @LukeTowers. I'm fairly new to github. I had't seen the documentation on the contributions.
Quote novice error on line 6.
I just wanted to make my small contribution to this great project.
Thank you!

**Comment by LukeTowers** [comment]
No worries @ezetojo, thanks for the effort! Please make sure you test all code changes locally before making proposing them in a PR, that would catch these sorts of errors fairly quickly. Fortunately the CI tool caught this one, but just keep it in mind for future contributions. Once the CI tool finishes it's second run through with your changes I'll merge this.

**Comment by LukeTowers** [comment]
... that was a long test run... 😉  whoops

**Pull request merged**
