### PR TITLE
Remove first item in taglist

### PR DESCRIPTION
**Pull request by jacobdekeizer**
Fix issue #3811 
First item in tag list can now be removed.

### CODE REVIEW

**Comment by daftspunk** [comment]
@jacobdekeizer thanks for your contribution!

This fix seemed to work better: ec0918e28458afce85905d89163ca7bf4b79044f 

Pls check that it works for you

**Comment by jacobdekeizer** [comment]
@daftspunk That doesn't work for me

**Comment by daftspunk** [comment]
To confirm when you navigate to Playground > Pages > Complex Page using the [Test plugin](https://github.com/octoberrain/test-plugin) and click the SEO tab and try to remove `OctoberCMS`, it doesn't work?

**Comment by jacobdekeizer** [comment]
@daftspunk Just tested it with the test plugin and your fix, but it doesn't work :(
The js is in the source code so it isn't a caching issue.
I remove the first item in the taglist on the update screen. When I click save the first item will come back.

**Comment by daftspunk** [comment]
@jacobdekeizer Try this one, seems to work better 8ce9525b44885a8d6b937420c9e3845d29e1687d

**Comment by jacobdekeizer** [comment]
@daftspunk That works :)

**Comment by jacobdekeizer** [comment]
@daftspunk I do get this javscript error when removing an taglist item:
`Uncaught TypeError: Cannot read property 'element' of undefined at DecoratedClass.SelectOnClose._handleSelectOnClose (storm-min.js?v=462:1509)`

**Comment by daftspunk** [comment]
@jacobdekeizer Third time's a charm d46accfc4f309f5f071cee41ac5bf58092559392

This should prevent the exception. Thanks!

**Comment by daftspunk** [comment]
Proposed fix sets `selectOnClose` to always false (feature only ever used by taglist) and disables key functionality for custom tags. An alternative fix is in place that appears to be working

**Pull request closed without merging**
