### PR TITLE
Slovenian language added

### PR DESCRIPTION
**Pull request by BlazOrazem**
I created new language files for Slovenian language, in which I translated english phrases. Afterwards I tested the CMS through and through with the Slovenian language, made some corrections and now everything looks great. I also translated Froala language file and system assets JS language file. Besides that I added Slovenian language to all other system language files and added a Slovenian language selection with an appropriate flag to the Preference model.

### CODE REVIEW

**Comment by LukeTowers** [comment]
Thanks for your contributions @BlazOrazem! As this is a large PR with a lot to review we'll hold off merging it until after we've finished Build 460.

**Comment by bennothommo** [comment]
@BlazOrazem With the language changes made for Froala, would you mind submitting a PR to their repo to have the Slovenian language file added: https://github.com/froala/wysiwyg-editor. If we decide to update Froala, we will more than likely use their language files.

**Comment by BlazOrazem** [comment]
> @BlazOrazem With the language changes made for Froala, would you mind submitting a PR to their repo to have the Slovenian language file added: https://github.com/froala/wysiwyg-editor. If we decide to update Froala, we will more than likely use their language files.

Good idea @bennothommo , I created a PR to their repo: https://github.com/froala/wysiwyg-editor/pull/3752

**Comment by bennothommo** [comment]
@BlazOrazem awesome!

**Comment by daftspunk** [comment]
Thanks @BlazOrazem!

**Pull request merged**
