### PR TITLE
Updated jQuery from V2 to V3.3.1 and added jQuery Migrate

### PR DESCRIPTION
**Pull request by ayumihamsaki**
https://github.com/octobercms/october/pull/3238

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
@LukeTowers Cant get the PR merged? I had it setup and to merge and clicked go and it created a new one. Can you move it?

**Comment by ayumihamsaki** [comment]
@LukeTowers Cant get the PR merged, due to deleting the forked github a while back. Could you merge it your end please.

**Comment by LukeTowers** [comment]
@ayumihamsaki it'll have to wait until I can get to my local development environment and set up a separate branch for both PRs to be merged to which can eventually be merged into develop. Keep this open for now though

**Comment by ayumihamsaki** [comment]
@LukeTowers Thank you!

**Comment by ayumihamsaki** [comment]
Moved to PR: https://github.com/octobercms/october/pull/3886

**Pull request closed without merging**
