### PR TITLE
Simplify Repeater Logic

### PR DESCRIPTION
**Pull request by LukeTowers**
Refs: #4230

### CODE REVIEW

**Comment by w20k** [comment]
@LukeTowers seems like that breaks Datatables they don't save the `value`. Will run few more :)

**Comment by LukeTowers** [comment]
@w20k @bennothommo issue should be fixed. Can we get rainlab/translate-plugin#466 tested too?

**Comment by bennothommo** [comment]
@LukeTowers Can confirm - all working now.

**Comment by w20k** [comment]
@LukeTowers done with testing, everything is fine now!

**Comment by seanthepottingshed** [comment]
@LukeTowers @bennothommo @w20k 

Excellent! I've just tested the Static Pages and Datatable Repeaters and they all work as expected. I've also tested the CMS pages and the validation / index issue still exists when deleting repeater groups:

* https://github.com/octobercms/october/issues/4175#issuecomment-469172078

**Pull request merged**
