### PR TITLE
Support for AJAX select2 options

### PR DESCRIPTION
**Pull request by LarBearrr**
Currently, [the select docs](https://octobercms.com/docs/ui/select) mention support for custom options returned by an AJAX handler. Unfortunately, the select.js plugin does not have support for parsing JSON responses, as required by select2. See [https://select2.org/data-sources/formats](https://select2.org/data-sources/formats) for details. 

This PR is based on [a Stackover flow question](https://stackoverflow.com/questions/44407559/how-to-provide-a-datasource-for-select2-with-october-cms-via-the-built-in-ajax-f?noredirect=1#comment75814469_44407559) involving a very similar issue. The author there added an additional method to the select2 plugin:

```
processResults: function (data,params) {
    return {
        // The JSON needs to be parsed before Select2 knows what to do with it.
        results: JSON.parse(data.result)
    };
},
```

In addition to this, the method returing results for the custom select field needs to encode the results in JSON format. An example is below:

```
$results = [
            [
                'id' => 1,
                'text' => 'Foobar'
            ],
            [
                'id' => 2,
                'text' => 'Bazbaz'
            ]
        ];

return ['result'=>json_encode($results)];
```

The desired effect is now produced:
image

This fixes [#2722](https://github.com/octobercms/october/issues/2722) by enabling the select2 plugin to handle JSON encoded results from backend handlers. 

Thanks to the following for listening to me complain and helping sort this out:
@alxy 
@DanHarrin
@LukeTowers

### CODE REVIEW

**Comment by DanHarrin** [comment]
PR made for the docs as well #4412

**Comment by DanHarrin** [comment]
@LarBearrr please remove the changes not related to this fix

**Comment by LukeTowers** [comment]
I feel like this is backwards to how this should be fixed. If it's not working as documented right now then we should fix it so that it works as documented, not change the documentation to use a different implementation.

**Comment by LarBearrr** [comment]
Closing as this PR includes irrelevant files. My apologies.

**Comment by DanHarrin** [comment]
Moved to #4413.

**Pull request closed without merging**
