### PR TITLE
Fix Sidebar and File Column bar in the code editor section

### PR DESCRIPTION
**Pull request by ayumihamsaki2**
See github Issue: #4005

### CODE REVIEW

**Comment by ayumihamsaki2** [comment]
I give up I don't understand why it is always saying conflict, there must be another reason causing this! There is nothing wrong with my code.

**Comment by LukeTowers** [comment]
@ayumihamsaki it's because your copy of october/library doesn't have the changes to the minifier that removes all newlines. Make a PR to revert that change in the library and I'll recompile the assets for the dev branch.

**Comment by ayumihamsaki** [comment]
@LukeTowers Sorry got the flu right now, my head spinning. Are you saying to reset the `october.css` so there are no changes in that file and you will compile the changed less files to generate a new `october.css` ?

**Comment by LukeTowers** [comment]
@ayumihamsaki sure, we also need to revert the changes made to the asset compiler in the library though.

**Comment by ayumihamsaki** [comment]
@LukeTowers Have done that, this pr has no conflicts now.
@w20k I think the github issue: https://github.com/octobercms/october/issues/4037 may need testing with this pr as well when you create the pr for that issue.

**Comment by ayumihamsaki** [comment]
@LukeTowers Any thoughts on this conflict, I have updated and added the new re-complied october.css (which you created yesterday) that passes [commit db2106d], but then try to add some edits and it doesn't want to pass it by saying conflict [commit 9ea3cb5].

**Comment by w20k** [comment]
@ayumihamsaki, sorry added new CSS minification rules, you'd have to pull new changes 😄

**Comment by LukeTowers** [comment]
@ayumihamsaki2 can you rebuild the assets please after pulling down the latest dev branch?

**Comment by ayumihamsaki** [comment]
bookmarked - just going though all my list of issues.

**Comment by ayumihamsaki2** [comment]
Closed as created a new pr

**Pull request closed without merging**
