### PR TITLE
Convert number field in repeater to float

### PR DESCRIPTION
**Pull request by BOOMER74**
This also fix [this](https://github.com/octobercms/october/issues/1578) issue.

### CODE REVIEW

**Comment by daftspunk** [comment]
Hmmm, I'm not sure if the `Form` class should really be concerned about `Repeater`, so this logic is in the wrong replace. It should live with the `Repeater` class and get pre-processed there.

**Comment by BOOMER74** [comment]
@daftspunk I move code from Form to Repeater. Maybe now checking for type is not necessary. About ajax: need to change framework.js:268. Sorry, its in one commit.

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
Closed due to lack of follow up from @BOOMER74

**Pull request closed without merging**
