### PR TITLE
Fix searching in non text fields under Postgres

### PR DESCRIPTION
**Pull request by CSNWEB**
When using postgres the List Widgets threw an error for non text fields (e.g. integer). With this fix searching for an id or in other numerical columns works.

Please let me know if my solutions suits you, I might add it for the relation columns above too. I didn't yet because I have no example and would have to create on to test it.

### CODE REVIEW

**Comment by daftspunk** [comment]
We should be using the [`\DbDongle`](https://github.com/octobercms/library/blob/develop/src/Database/Dongle.php) class for this.

**Comment by CSNWEB** [comment]
I decided to cast every field regardless of the type for Postgres. It doesn't hurt and the search works like  expected when using mysql.

**Comment by CSNWEB** [comment]
@daftspunk do you have any comments on the new version :)? As I'm using October with Postgres in several instances, it would help me a lot if this gets merged. Thanks

**Comment by mplodowski** [comment]
The same issue exists for date column type. @CSNWEB can you also apply fix for this?

I think we should cast date to year only "YYYY".

**Comment by CSNWEB** [comment]
@mplodowski the last commit already fix it for all types as everything is now casted to text. But I wouldn't cast any date to year only you can still search for -YYYY to find the year, but you could also be searching for an exact date when I leave it like it is now.

**Comment by mplodowski** [comment]
That's fine by me. Thanks for this PR.

**Comment by daftspunk** [comment]
Merged in 34bd318427135f8e3e19e7e1bc30d0629490f513
Thanks!

**Pull request closed without merging**
