### PR TITLE
Ability to add field after another field when extending a backend form

### PR DESCRIPTION
**Pull request by toughdeveloper**
Hi, 

This was posted a while ago on the forum - http://octobercms.com/forum/post/ability-to-add-field-after-another-field-when-extend-form

We regularly find ourselves removing many fields to re-add them (KurtJensen suggestion). So would like to see this as a built in feature.

My first pull request, please advise if I have done anything wrong.

Thanks,
Matt

### CODE REVIEW

**Comment by LukeTowers** [comment]
While I think that positioning of dynamic fields is a valuable tool to provide developers with, I don't think this particular implementation is the right way to go about it. I'd rather see something where the developer perhaps specifies an `order` property for their fields, similar to menu items. 

I'd like to get @daftspunk's input on it first though.

**Comment by toughdeveloper** [comment]
Thank for feedback. My rational for the approach was for it to be similar to how you may go about positioning a new column in a migration. However I'm open to feedback to get this inline with other areas of October. 

When you mention menu items, is this within the static pages plugin ? Could you send me a link to code if possible? Thanks

**Comment by LukeTowers** [comment]
I'm referring to the backend navigation menus: https://octobercms.com/docs/plugin/registration#navigation-menus

**Comment by daftspunk** [comment]
This is indeed a tricky one and probably why it hasn't been implemented already. Let's explore the interaction between both proposals. Consider I want `brother` to go in between father and sister. 

```
mother
father
sister
```

Using the `$order` approach, applying a incremental default of +100

- 100: mother
- 200: father
- 300: sister

Developer somehow needs to know the auto generated range of 200-300 and come up with

- 250: brother

Now let's say the definition is modified to include two new form fields, since the default ordering is malleable, we end up with

- 100: grandmother
- 200: grandfather
- 250: brother
- 300: mother
- 400: father
- 500: sister

Developer somehow needs to know the new auto generated range of 400-500 and modify order to 450. Now consider that **250** was produced by a third-party plugin, not so easy to change to the required 450. So explicit order definition will probably never exist when defining fields.

This proves, to me at least, that @toughdeveloper is on the right track by using an API that says:

- *Insert brother after father* or *Insert brother before sister*

However the implementation is a bit too dirty, we prefer code that can be understood easily at a glance (one of October's core values). So in psuedocode should read something like this

As `insertFieldBefore()` function with arguments `$fieldDefinition`, `$targetFieldName` and `$tolerance`
1. Declare `$tolerance` with a default value of `1`
1. Define `$targetFieldName` internal `sortOrder` property as `$targetSortOrder`
1. Define `$fieldDefinition` internal `sortOrder` property as (`$targetSortOrder` minus `$tolerance`)
1. Add `$fieldDefinition` to array of form fields

The above would require the inclusion of an internal sortOrder property, used only as an internal marker for managing the sort order, not available via the public API (at this stage). The system would use this marker to sort the fields before rendering.

Hope this helps!

**Comment by toughdeveloper** [comment]
Thanks for looking into this. I can have a look at making these changes. 

Just so I'm clear, where were you imaging `insertFieldBefore` being called from?

**Comment by daftspunk** [comment]
It would be called by [extending code as per the documentation](http://octobercms.com/docs/backend/forms#extend-form-fields).

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
