### PR TITLE
Fix: Filter type "group" does not work when 500+ options are available

### PR DESCRIPTION
**Pull request by Klaasie**
In relation to: https://github.com/octobercms/october/issues/3202.

This PR addresses the issue where the filter type group stops working due to surpassing the `max_input_vars` amount by preventing the available option types from being posted when filtering.
This is achieved by splitting the available and active options into 2 seperate variables in the javascript.

I've tested this code with all possible filter types to ensure they keep working.
I have set up a testing area in the october-test plugin here: https://github.com/Klaasie/test-plugin/tree/fix/filter
The users list view page has all the possible filters available for testing. A seeder has been made available that will seed the roles table with enough records to test the fix.

_P.S. I wasn't sure about including the minified version the changes, I vaguely remember I need to ignore that as it will be minified on release anyway. If you need it I can commit it._

### CODE REVIEW

**Comment by bennothommo** [comment]
@Klaasie does this theoretically only raise the limit from 500 to 1000, ie. if you have 500 available options, and 501 active options, 1 of those active options will be dropped? You could potentially send the data as a JSON object - we did a similar fix for the Static Menu data in the Static Pages plugin, which was also affected by `max_input_vars` (https://github.com/rainlab/pages-plugin/pull/439/files)

**Comment by Klaasie** [comment]
@bennothommo That's a clever solution to the problem. I've modified the code to post the values as a JSON string and handle the data properly at the php side. This is on top of the modifications that avoid the available options from being posted. I personally don't think they should be in the post data, none of the other filter options do.

**Comment by LukeTowers** [comment]
@Klaasie Can you recompile the js too?

**Comment by Klaasie** [comment]
@LukeTowers Done!

**Comment by bennothommo** [comment]
@github-actions run

<details>
<summary>✔ Ready for testing</summary>

```js
(async () => {
  // Get issue/PR number
  const number = context.issue.number;

  // Add Testing Needed label
  await githubClient.issues.addLabels({
    owner: context.repo.owner,
    repo: context.repo.repo,
    issue_number: number,
    labels: ['Testing Needed'],
  });

  // Comment body
  const commentBody = 'This pull request has been marked as **Ready for Testing**. To expedite this pull request being'
    + ' merged, we encourage members of the community to test the changes and confirm they are working. You may view our'
    + ' [Testing a Pull Request](https://github.com/octobercms/october/blob/develop/.github/CONTRIBUTING.md#testing-a-pull-request)'
    + ' section in the Contibution Guide to access the changes in your own copy of October CMS.'
    + '\n\n'
    + 'If you have [Docker](https://www.docker.com/), you can quickly run a copy of October CMS with this pull request\'s'
    + ' changes in place via the following command:'
    + '\n\n'
    + '```\n'
    + 'docker run --rm -p 80:80 -e GIT_MERGE_PR=' + number + ' aspendigital/octobercms:develop\n'
    + '```';

  // Add comment
  await postComment(commentBody);
})();
```

**Comment by bennothommo** [comment]
@Klaasie I've given this a test and it's working well. There's only one bug I encountered - when I use the "Clear" button with the group filter, it no longer allows me to apply that filter again. When I click the filter once more afterwards, and try and make changes to the filter, the "Apply" and "Clear" buttons no longer show up.

I've double checked the behaviour without your changes and those buttons appear, so it looks like there's something in your changes that prevents the buttons from appearing if you press the "Clear" button.

I'll message you the access details to a test instance on Slack.

**Comment by Klaasie** [comment]
@bennothommo 

The reason this broke is because available and selected options are now split in 2 different variables. Previously the one variable with both available and selected options would resolve to null so when the popover was opened it'd retrieve the data (through ajax) again and set all variables correctly. Now the available options would still be there while selected would resolve to null causing `if (!this.scopeValues[this.activeScopeName])` (line 285) to exit the function early.

To fix this issue I've modified the javascript to behave it would previously. Meaning hitting the "clear" button will clear both the selected and available options. When opening the popover data will be retrieved again (through ajax) and the popover will function properly again.

**Comment by bennothommo** [comment]
Great work @Klaasie. That fixed it.

Tested, and confirmed working.

**Comment by danielbidala** [comment]
@bennothommo This fix doesn't seem to work with build 468 and even with 469. I have about 1800 filter item (related record) for group filter. When I open group filter, I see the first 500 record. When I start type to search filter item (which is not in the first 500) I get the search results but I can't apply the filter (the apply button doesn't appear).

**Comment by LukeTowers** [comment]
@danielbidala did you try selecting the option and then clicking out of the filter box?

**Comment by danielbidala** [comment]
@LukeTowers Yes I've tried, the selected filter takes no effect:

Megrendelések _ Bright CRM

**Comment by bennothommo** [comment]
@danielbidala Make sure you don't have a cached version of the backend JS files. Try running `php artisan october:util compile js`, then flush your browser cache, and try again.

**Comment by msimkunas** [comment]
@danielbidala I'm experiencing the exact same issue on build 469. I have more than 500 items in the filter and initial testing suggests that 500 is the cut-off point after which the remaining items are not processed correctly. Selecting those items doesn't make the filter buttons appear and the active filter count is not incremented.

**Comment by msimkunas** [comment]
I believe that the issue must be related to the following limit of 500 records: https://github.com/octobercms/october/blob/517c588ef7224941af761ba4df4f329dd0a442db/modules/backend/widgets/Filter.php#L385-L395

**Comment by msimkunas** [comment]
Related: #3202

**Pull request merged**
