### PR TITLE
fix froala input hidden

### PR DESCRIPTION
**Pull request by tim0991**
i checked it in `insert link, insert image, insert video insert file, insert audio`, it's works file

### CODE REVIEW

**Comment by tim0991** [comment]
## Before
image

## After
image

**Comment by LukeTowers** [comment]
@tim0991 Don't edit compiled files, they won't be accepted as they will be overwritten whenever we next compile the assets. Please make your changes here instead: https://github.com/octobercms/october/blob/develop/modules/backend/formwidgets/richeditor/assets/less/_froala.less#L154.

**Comment by Lavrushin** [comment]
https://github.com/octobercms/october/pull/3993

**Comment by LukeTowers** [comment]
@w20k which one is better?

**Comment by w20k** [comment]
@LukeTowers, I don't like both. The issue is with background color of the label.
@Lavrushin, could you change your solution to:
`.fr-popup .fr-input-line input + label, .fr-popup .fr-input-line textarea + label { babckground: transparent} ` 
_I guess, should be !important_

**Comment by Lavrushin** [comment]
> @LukeTowers, I don't like both. The issue is with background color of the label.
> @Lavrushin, could you change your solution to:
> `.fr-popup .fr-input-line input + label, .fr-popup .fr-input-line textarea + label { babckground: transparent} `
> _I guess, should be !important_

Sure

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
