### PR TITLE
Updated Various Packages

### PR DESCRIPTION
**Pull request by ayumihamsaki**
Updated jsdiff from 3.2.0 to 3.5.0

See github issue: https://github.com/octobercms/october/issues/3867

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Updated a unknown version of dropzone dated from 2015 done by daftspunk. I think it is a V4 by guess as it is dated 2012.

From V4  to 5.5.1 (Added Version at the top of the file to check track in the future

See github Issue: #3867

**Comment by ayumihamsaki** [comment]
Updated jCrop (2013) v0.9.12 - (2018) v0.9.15

Updated jCrop (2013) v0.9.12 - (2018) v0.9.15

See Github Issue: #3867

**Comment by ayumihamsaki** [comment]
Updated Raphaël and Eve JS Library

Updated the Following:

Raphaël from 2.1.2 to 2.2.7
Eve from 0.4.2 (2013) to Eve 0.5.4 (2017)

Added Links where to download for future ref.

See github Issue: #3867

**Comment by w20k** [comment]
@LukeTowers is it a sort of standard in OctoberCMS to use non-minified js/css version? 

@ayumihamsaki could you change all the files to dev version (uncompress), if @LukeTowers say so? :) And one more thing change name of the file jquery.Jcrop.min.css -> jquery.Jcrop.css and correct 'import' line:3 in backend/assets/less/october.less.
Thanks! ;) Will continue testing after that.

**Comment by ayumihamsaki** [comment]
I was wondering that as well, everything is using non-min versions? I wait for Luke to confirm, if it is better to move over to min versions or not? I have been adding version numbers as well, it seems like there was no thought about future updates in files.

I think testing should wait until they update to jQuery V3, so many files that need to be updated are using jQuery.

**Comment by ayumihamsaki** [comment]
Going to break this PR up into separate issues and file updates, for now please leave it open and when I have finished updating each pacakage separately I will close this PR. (Just helps with file locations for me)

**Comment by ayumihamsaki** [comment]
Going to break this PR up into separate issues and file updates, so will close it.

**Pull request closed without merging**
