### PR TITLE
Fix line chart demo code example

### PR DESCRIPTION
**Pull request by ayumi-cloud**
See Github Issue: https://github.com/octobercms/october/issues/4792

### CODE REVIEW

**Comment by daftspunk** [comment]
I don't understand why this change is needed, these docs are intended to show the chart markup; how the chart works. This code appears to only introduce some basic PHP exception handling.

**Comment by ayumi-cloud** [comment]
> I don't understand why this change is needed, these docs are intended to show the chart markup; how the chart works.

Because it's missing the <div class="report-widget"> container.

> This code appears to only introduce some basic PHP exception handling.

No, it adds the correct div container to make it work. I will add an extra commit to remove the php, I thought it might be useful to show people a full working example.

**Comment by ayumi-cloud** [comment]
@daftspunk pls re-review this, thanks.

**Comment by daftspunk** [comment]
@ayumi-cloud Thanks for the clarification, will review this shortly

**Comment by daftspunk** [comment]
I have tested this code works fine without the proposed wrapper.

**Comment by ayumi-cloud** [comment]
@daftspunk possible issue with your testing, I just coded a test plugin in a brand new october install and can demo the issue, see below:



and

**Comment by ayumi-cloud** [comment]
@daftspunk I just noticed your code is saying `chart-pie` and this issue is with `chart-line`

**Comment by daftspunk** [comment]
You're right, the line chart control appears to ship with no CSS at all. The `.report-widget` class activates the `.height-200` class on the inner container to make it visible

The following code works just as well, and breaks the dependency on the report widget CSS:
```
<div
    data-control="chart-line"
    data-time-mode="weeks"
    data-chart-options="xaxis: {mode: 'time'}"
    style="height: 200px">
        <span
            data-chart="dataset"
            data-set-color="#008dc9"
            data-set-data="[1477857082000, 400], [1477943482000, 380], [1478029882000, 340], [1478116282000, 540], [1478202682000, 440], [1478289082000, 360], [1478375482000, 220]"
            data-set-name="Visits"></span>
</div>
```

Note the `style="height: 200px"` to replace the height class provided by the report widget styles

Fixed in ee4078ac44afb61848ed5973694282719ee6826e

Thanks @ayumi-cloud!

**Pull request closed without merging**
