### PR TITLE
Fixed grid widget breaking backend menu scrolling.

### PR DESCRIPTION
**Pull request by justin-lau**
The issue is described in rainlab/translate-plugin#5.

It was caused by a `mousewheel` jquery plugin living in the `jquery.handsontable.js` file, which broke the `jquery-mousewheel` plugin already included in the `vendor-min.js` file.

### CODE REVIEW

**Comment by daftspunk** [comment]
Well spotted. 

Just FYI - the handsontable (DataGrid) widget will be removed entirely soon, in favor of DataTable. It just needs some more features to become ready.

**Comment by daftspunk** [comment]
@alxy You might be pleased to know this is fixed...

**Comment by justin-lau** [comment]
Caused me quite a few hours digging..! But it was the last bone my client
can pick =)

**Comment by alxy** [comment]
Yeah. Thanks @justin-lau for the fix!

**Pull request merged**
