### PR TITLE
Fix the double-popup animation effect due to bad nesting

### PR DESCRIPTION
**Pull request by gabsource**
Reported in #2054 comments

### CODE REVIEW

**Comment by daftspunk** [comment]
I don't think `<div class="modal-content">` is needed either.

**Comment by gabsource** [comment]
I need a single root node content (that get disposed by the `$.popup`), I can remove the `class` and let the `<div>` alone if you prefer.

**Comment by gabsource** [comment]
I've changed the code to use the jQuery object directly instead of the generated html in order to only define the real content with no wrapping tag.

**Comment by daftspunk** [comment]
Uh oh, it looks to be functionally broken now - open the popup twice and the select dropdown fails. Perhaps it is being loaded twice?


            // Prevent duplicate loading
            if ($element.data('select2') != null) {
                return true; // Continue
            }

**Comment by gabsource** [comment]
`data('select2')` is always undefined ... better revert and stick with the raw HTML (with the dummy root required for calling `.html()`) instead of the jQuery object...

**Pull request merged**
