### PR TITLE
applying relation scope model in RelationController

### PR DESCRIPTION
**Pull request by cybear-d**
this will apply relation scope model in relation behavior

### CODE REVIEW

**Comment by daftspunk** [comment]
Can you provide a complete example (documentation) on how this is used?

Thanks

**Comment by cybear-d** [comment]
if relation have scope in definition, relation controller will not applying it because it will use new query from list event.  So for consistency scope in relation, applying scope after it querying the new query for list widget will be better.

Example:
```
class Post extends Model
{
    public $belongsToMany = [
        'categories' => [
            'Acme\Blog\Models\Category',
            'scope' => 'isActive'
        ]
    ];
}

class Category extends Model
{
    public function scopeIsActive($query)
    {
        return $query->where('is_active', 1)->orderBy('name', 'desc');
    }
}
```

it will display the list for relation list widget with the definition scope isActive

**Comment by daftspunk** [comment]
I had assumed this behavior is already applied as part of the Relation filter in the Model (`applyRelationFilters`). Can you prepare a sample plugin that demonstrates the issue?

**Comment by cybear-d** [comment]
sorry for late response.

Relation filter in the Model ( applyRelationFilters ) only applied when the relation object is called.
RelationController widget list only using Relation Model from the relation object, so it will not call the applyRelationFilters (the widget only using query from the Model itself, not from the Relation).

```
$config->model = $this->relationModel;  // only the model, not the relation
....
$widget = $this->makeWidget('Backend\Widgets\Lists', $config);
```

Example:
https://github.com/cybear-d/oc-test-plugin

i think this issue also affect #1133 

if you want i'll make pull request for the record finder too.

**Comment by daftspunk** [comment]
Installed the test plugin, thanks!

It would appear the List creates a new query and the basic constraints are being added, not those defined in the relationship. There should be a way to apply these "extra constraints" (`addDefinedConstraints`) in the model/relation API. This will result in some reorg of the Database package, so will have a look when I find some time.

**Comment by cybear-d** [comment]
thank you, will wait for your update

**Pull request closed without merging**
