### PR TITLE
Colorpicker: value input support in modals

### PR DESCRIPTION
**Pull request by toymaster**
**Issue**
When using colorpicker field in the relationship manager modal window it is impossible to set value manually in the colour input field because it is locked. This make the widget useless if you need to set a custom colour in the modal window.

**Background**
The modal container has the tabindex attribute set to "-1" to prevent access to items outside the model using tab. Colorpicker creates a parent container (.sp-container) to place custom colour selection code including colour value field. By default it is appended to body. _Since it is outside the modal window it cannot be edited because of tabindex value._
The issue is a part of Spectrum, which is sitting behind Colorpicker. [They recommend to use appendTo option when working with modal dialog.](https://bgrins.github.io/spectrum/#options-appendTo) However appenTo option is not configurable through October Colorpicker. 

Note: the issue has no relation to z-index definitions as in [992](https://github.com/octobercms/october/pull/992) or [1021](https://github.com/octobercms/october/issues/1021)

**Proposed Behavior**
By default Colorpicker container is appended to body. If relationship manager modal dialog is detected the container will be appended to the modal container. If more complicated modal structure involved developer may define appendTo option in the appropriate Colorpicker field of field.yaml.
```
fields:
	bg_colour:
		label: 'Select Colour'
		showAlpha: 1
		appendTo: '#mymodal'
		type: colorpicker
```
Setting appendTo is not required for standard October backend environment including relationship manager modal. It will be handled behind the scene.

**Solution**

1. Update colorpicker.js, ColorPicker.php and _colorpicker.htm to support appendTo option
2. Use a special function in colorpicker.js to set standard or custom parent container

**Testing**
It is pretty simple update. I have tested it on my stuff and it works reliably. The solution has no conflicts with my previous pull request [3940](https://github.com/octobercms/october/pull/3940). 
With both updates, the colorpicker is going to be finally usable in any backend context.

### CODE REVIEW

**Comment by w20k** [comment]
@toymaster, could you also provide either steps to reproduce or screenshots(gifs): before/after.

**Comment by toymaster** [comment]
If you want to reproduce the issue you need to take quite a few steps to build a working relation manager and colorpicker field in the form of the belonging model.

The nature of the issue between Spectrum and Bootsrap modals is discussed [here](https://github.com/bgrins/spectrum/issues/150) or [here](https://github.com/bgrins/spectrum/issues/161)
It was just overlooked when colorpicker was created.

I have attached a gif to show 2 colorpicker fields in the relation manager modal dialog. 

The left one is rendered inside the modal container after applying the fix and I can edit input value manually or with controls. 

The right one is rendered outside of the modal container (out of box behaviour) and I cannot manually edit input value. I still can edit it using controls but it is practically impossible to set a precise value in this way. It makes colorpicker hardly usable in modal windows.

colorpicker-resized-github

By the way, this gif shows as well that colorpicker saves rgba values as per [3940](https://github.com/octobercms/october/pull/3940). This does not happen out of box.

**Comment by w20k** [comment]
@toymaster, could you also rebuild JS assets.

**Comment by toymaster** [comment]
> @toymaster, could you also rebuild JS assets.

I made minimal necessary changes to colorpicker.js. Could you clarify what you mean by rebuilding JS assets?

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/pull/4199

**Pull request closed without merging**
