### PR TITLE
Lithuanian translation for system/lang

### PR DESCRIPTION
**Pull request by octolit**
First part of backend translation to Lithuanian. Complete system/lang.
backend/lang and cms/lang to follow

### CODE REVIEW

**Comment by LukeTowers** [comment]
Will wait for the rest before merging, thanks for the help!

**Comment by daftspunk** [comment]
Make sure this squashed before merging.

**Comment by LukeTowers** [comment]
@octolit Is this done?

**Comment by Doniz** [comment]
Oh and reset_error not translated yet.

**Pull request merged**
