### PR TITLE
Only clear cache when updates are applied

### PR DESCRIPTION
**Pull request by FranciscoMateo**
By default, when a user make login process the UpdateManager::update() method is lauched and the cache always is erased. With this way I make me sure that caché is remove it when some plugin is updated.

Beside I added 'clearCacheOnUpdateManeger' option on config/cache.php to allow us enable or not the erase cache on UpdateManager::update() method.

### CODE REVIEW

**Comment by LukeTowers** [comment]
I don't see the need for a config variable for this if we're detecting whether or not updates have actually been applied before clearing the cache.

Thoughts?

**Comment by LukeTowers** [comment]
@FranciscoMateo I don't understand what you mean by 
> Probably some pages have some big database and needs handle this kind of situation when their plugins are updated.

**Comment by mrbohnke** [comment]
Shall this help with #2659 and #3471

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
