### PR TITLE
Updated Ukrainian and Russian translations

### PR DESCRIPTION
**Pull request by PopcornPHP**

### CODE REVIEW

**Comment by daftspunk** [comment]
Please leave the trailing commas alone. 
Please do not include compiled code in the pull request.
Please squash all commits to a single (optional)

/cc @LukeTowers, some add them, some remove them, hence we never allow it and prefer to leave them as they are.

**Comment by LukeTowers** [comment]
@PopcornPHP no need to squash your commits, I will squash them for you when merging.

**Comment by PopcornPHP** [comment]
@daftspunk , I removed trailing commas and delete compiled code. Are there any more remarks?

**Comment by daftspunk** [comment]
Excellent

**Pull request merged**
