### PR TITLE
Add libwww-perl blocker

### PR DESCRIPTION
**Pull request by lesaff**
Block libwww-perl access user agent

### CODE REVIEW

**Comment by daftspunk** [comment]
Why?

**Comment by mrmlnc** [comment]
[It seems because of botnets](http://serverfault.com/questions/346540/how-to-create-htaccess-and-block-useragent-libwww-perl)

**Comment by daftspunk** [comment]
This will cause confusion for people with a genuine need to use this library.

**Comment by lesaff** [comment]
To prevent spammers and spam-bots. Also for security measure to prevent backdoor perl access.

**Pull request closed without merging**
