### PR TITLE
Add Slideable Tabs to Code Editor Screen

### PR DESCRIPTION
**Pull request by ayumihamsaki2**
This is a PR to allow slideable tabs in the code editor section, please see Github Issue for further details: https://github.com/octobercms/october/issues/3959

@LukeTowers @w20k if you both want to have a look at this, thanks.

### CODE REVIEW

**Comment by w20k** [comment]
Hi, @ayumihamsaki2, have you froget about non-minified script? Can't find it in your commits.

**Comment by ayumihamsaki** [comment]
@w20k I added both in the PR one for testing and one for running, when ok I will remove it. I added it there for temp.

**Comment by ayumihamsaki2** [comment]
@w20k thanks

**Comment by ayumihamsaki2** [comment]
I was having a think and if this PR goes ok, we may as well expand it into all the tabs in October's Backend, see here: https://octobercms.com/docs/ui/tab

This way it gives extra validity to adding all that extra code from jQuery UI.

**Comment by ayumihamsaki** [comment]
I was reading this [PR](https://github.com/octobercms/october/pull/3841) by chance and I think I need to change the PR here to add the same cloudflare fix, to the layout head file.

**Comment by ayumihamsaki** [comment]
I had a think and decide to expand this feature for all tabs in the backend. Because all the tabs are using the `control-tabs` class, see here: https://octobercms.com/docs/ui/tab

I just need to add that extra class to the javascript to make it work, have tested it and seems to ok.

**Comment by ayumihamsaki** [comment]
Ok, finished the code. I tested it and works fine. If you want to test it, please go ahead. It's ready for inspection now!

**Comment by w20k** [comment]
@ayumihamsaki, still can't see non-minified version of your init. script, only minified and packed version:  modules/backend/assets/js/october-min.js

**Comment by ayumihamsaki** [comment]
@w20k Ah, I understand what you are saying now (sorry I thought you were talking about a different file).

I was just reading the `modules/backend/assets/js/october.js` file seems to be a bundled version to create the `modules/backend/assets/js/october-min.js`

I'm going to move the code out of: `modules/backend/assets/js/october-min.js`

And place it in the `modules/backend/assets/js/backend.js` and also un-minify the js code - so easily to test.

Hopefully that should fix that issue (sorry about that).

**Comment by w20k** [comment]
@ayumihamsaki2, have a list of issues and a gif 😉

Workflow Gif:
dec-12-2018 14-33-17

Issues:
- You can drag tabs by Y ax. Not sticky.
- When you have multiple tabs opened, it doesn't let you scroll to the tab you want to change with. You have to drag the screen.
- It's a bit irritating when used with the hideable sidebar.
- Needs testing with mobile devices (touch screens).
- Doesn't swap tabs, nor show where it will place your tab (might be an option).

PS: And add compiled version of october.js -> october-min.js

**Comment by ayumihamsaki** [comment]
@w20k Thanks for feedback, What browser(s) did you test in? Also PC or MAC.

I didn't get any of those issues so I want to check down the route of a Polyfill.

**Comment by w20k** [comment]
@ayumihamsaki, Chrome latest and OSX latests; But I'll double check.

**Comment by ayumihamsaki** [comment]
@w20k What version of Chrome? Sorry I'm using Canary.

**Comment by w20k** [comment]
Chrome: Version 71.0.3578.80 (Official Build) (64-bit)

**Comment by ayumihamsaki** [comment]
Thanks!

Will test on a load of browsers and touch screen, my computer is touch screen and I got some tablets and smart phones here...

Will go through each of your issues and sort them out.

Thanks for feedback.

**Comment by ayumihamsaki** [comment]
@LukeTowers @w20k Today I tried to work on this PR. I have come to the following conclusion:

October CMS has a very old, dead project inside it, which needs a review. It can be found at the following location:

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/vendor/sortable/jquery-sortable.js

You can see the repo for this found here: https://github.com/johnny/jquery-sortable

Please note: It has not been updated since 2015.

When running some tests it is causing the tabs to scroll on the y-axis and all the other issues w20k has said.

I would suggest removing this code from October and switch to the custom Jquery UI custom build which is up to date and seems to work pretty good. Also this will future proof October and I am sure they will keep updating the code.

Therefore I request a review about this and then I can continue further into trying to develop this enhancement.

**Comment by w20k** [comment]
@ayumihamsaki2, have you tried replacing sortable.js with a new jQuery.UI version?

@ayumihamsaki2, maybe you could make a separate PR to test if custom jQuery.UI sortable won't break anything 😄

**Comment by ayumihamsaki** [comment]
@w20k I'm just running some tests on that right now, to see if fully working...

**Comment by ayumihamsaki** [comment]
Gonna run more tests ...

**Comment by ayumihamsaki** [comment]
> have you tried replacing sortable.js with a new jQuery.UI version?

Yes, got several errors due to some other files requiring that library e.g.

https://github.com/octobercms/october/blob/master/modules/backend/assets/js/october.simplelist.js

Seems like a lot of work needed to replace and update that library, several files are using it.

But it is really buggy and the drag is not smooth at all and all the issues are coming from that side.

So Not really sure what to do now?

**Comment by ayumihamsaki** [comment]
I leave some results anyway.

Using the jquery-sortable I got this:

ezgif-2-c4965d52048b

Using the jQuery UI I got this:

**Comment by w20k** [comment]
@ayumihamsaki2, I'd try to implement https://github.com/SortableJS/Sortable, which doesn't use .sortable(). Might be a best and the quickest option.

**Comment by w20k** [comment]
@ayumihamsaki, I don't like the idea of using init script inside the partial, but have to look at it tomorrow.

Also found few Css|UI bugs, will write them down - tomorrow. But for now will post few screenshots.

###Screenshots
_With hidden sidebar_:
screenshot_2018-12-19_at_23_56_30
_Small screens_:
screenshot 2018-12-19 at 23 58 32

**Comment by ayumihamsaki** [comment]
@w20k Thanks for the feedback.

I forgot to check small screens, I have just done a video and this is what I get on a Chrome V71, see youtube video:

https://youtu.be/_Q2wSkGjp_s

I think the problem is that October is a bit of a nightmare! It's CSS is really in bad shape, very old, no flexbox, css grids or any new things, mostly a ton of floats, no prefix's so everyone is seeing different screen issues on different browsers. Another issue I worry about is that October still uses px and not em or rem so mobile and tablets must have lots of issues.

Then the javascript files are mostly very old and using bugy scripts, that are 4-8 years old and some are dead projects. Most of the JS files loaded into storm.js seems to be in a bad way.

I feel this pr can't be done until october gets all its js and css files updated.

It's obvious that we are seeing different errors on different devices and that should not be the case.

**Comment by ayumihamsaki** [comment]
I ran some basic tests on some core CSS files in October and found 100's of bugs in there. This would explain why I am seeing different errors in various browsers. I think it would be a good idea to standardize the CSS before updating this pr and correcting some of the css/js issues.

**Comment by ayumihamsaki** [comment]
Working Notes (from feedback):

1. Screenshots - Fixed both errors.
2. First, doesn't play well with the sidebar, if it's hideable. I think you should release drag if it's over an element or doesn't let it go over - FIXED.
3. Second, pure madness with OctoberCMS scroll bar and drags - Trying to add a handler (only last issue left to do).

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers Hi, I need a quick review, before I continue, see gif demo below:

ezgif-2-c32a0af79b80

I've added a handler at the top of each tab. When the user hover's over the icon the cursor tells you it can move. Then the User can move the tab only from that area. The reason for doing this is because I want to leave the rest of the tab area not being able to scroll then it does not mess around with the scroll bar when you try to move the tabs outside the screen view into view.

Please let me know what you think of this idea?

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers Hi, I need a quick review, before I continue, see gif demo below:

ezgif-2-c32a0af79b80

I've added a handler at the top of each tab. When the user hover's over the icon the cursor tells you it can move. Then the User can move the tab only from that area. The reason for doing this is because I want to leave the rest of the tab area not being able to scroll then it does not mess around with the scroll bar when you try to move the tabs outside the screen view into view.

Please let me know what you think of this idea? Can adjust the CSS to bend it into the tabs more.

af

**Comment by ayumihamsaki** [comment]
There is only one last error left, which is shown in the below gif:

ezgif-2-aecf5bb169a6

I don't want the slideable handler to also drag the whole screen.

So need to turn off that function for `<i>..</i>` and only allow `<li>..</li>` then I will be finished on this pr.

**Comment by ayumihamsaki2** [comment]
Going to close this PR, I don't think it can be done. The overall tab scrolling script is fighting with this script and giving sub-par results. Not happy with the overall finish quality, the two scrolling at the same time is not good at all. The other scroll tabs would have to either be removed or re-coded to allow this update! I don't think it can be upgraded with the current code. I tried.

**Comment by w20k** [comment]
@ayumihamsaki, thanks for trying 😉

**Pull request closed without merging**
