### PR TITLE
Add support for html attributes in the section formfield

### PR DESCRIPTION
**Pull request by Klaasie**
This PR will modify the section formfield to add html attributes to its main html tag.

This will be particulary usefull for adding extra classes or data attributes to be handled by custom javascript.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@Klaasie can you provide an example of what you'd use this for on the section field? The section field is really meant to be a "section title", so I can't really think of any attributes that would actually serve a useful purpose.

**Comment by Klaasie** [comment]
Similar to the PR https://github.com/octobercms/october/pull/5003 I was also checking this form field.

For the attributes definition I can think of a (global) usecase however.
Similar to how OC handles intialization of javascript objects through data tags I like to do the same.
By consistently applying the attributes definition within form fields I will be able to initialise custom javascript objects through yaml definitions.

I don't have a particular usecase to the sections form field though.

I will be making more PRs in the future where the attributes will be applied to all form fields. The PRs of today are just how far I've gotten today :)

**Comment by LukeTowers** [comment]
@Klaasie if we don't have a specific use case for this field lets leave it alone for now then.

**Comment by Klaasie** [comment]
@LukeTowers Fair enough!

**Pull request closed without merging**
