### PR TITLE
Improve visibility of code editor buttons in the backend

### PR DESCRIPTION
**Pull request by ayumihamsaki**
PR for https://github.com/octobercms/october/issues/3947

Have tested it in various Browsers and Desktop, Tablet and Mobile all seem fine.

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Sorry forget my last comment, with regards to that screenshot - that would not work when you go into fullscreen mode.

Actually I have this PR running on a test website all day. If I want to see the first line of code, I just switch from normal mode to full screen and the code is located in a different place, due to the two different screensizes.

**Comment by ayumihamsaki** [comment]
Will experiment more for solution

**Comment by w20k** [comment]
One of the options would be to move 'editor-toolbar' on top of nav-bar using css (hacky solution: .editor-toolbar{top: -30px;right: 35px;} and color white for an anchor tag): 

screenshot 2018-11-30 at 01 58 04

**Comment by ayumihamsaki** [comment]
@LukeTowers @w20k I was thinking the exact same thing (but more of ripping out the HTML code and moving it properly) and also adding that grey bar to the top of the full screen mode. Giving Users more features like "Search" in full screen mode.

**Comment by ayumihamsaki** [comment]
Note: z-index in the LESS file is 10px + 3px so that is why I changed the CSS to 13px to match it correctly (mistake in original file).

**Comment by w20k** [comment]
@ayumihamsaki That would be awesome and logical to do. You could add PR for 'ace.js' and test it while you're dealing with this task, and make one more JS lib PR for me to speed up the process a bit.

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers I think Luke can just complete this issue and then I will open a fresh new PR for the ace update and update any issues there. Makes things easier completing each issue one at a time.

With regards to testing, what about testing DPI? I've been wondering how October handles high to low and vice vera resolution devices.

**Comment by w20k** [comment]
@ayumihamsaki Sounds good to me!

If you could write down steps, how could we test it or what's your idea behind - 'high DPI testing' (haven't done DPI testing myself. Don't have a knowledge on topic). I could try it out, or also add ideas ;)

**Comment by ayumihamsaki** [comment]
PLEASE DONT COMPLETE THIS PR YET - I AM RUNNING MORE TESTS ON IT.

**Comment by ayumihamsaki** [comment]
@w20k The reason for high DPI testing is that people say a normal computer has a 1 dpi and an ipad pro has a 2 dpi etc.

You can find a list here of all the sizes: http://screensiz.es/

For testing we use DPR see here for more details on testing:

https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports#optional_controls_eg_touch_media_queries_dpr

**Comment by LukeTowers** [comment]
What does it look like in full screen?

**Comment by ayumihamsaki** [comment]
I tested in various modes all looks fine to me. My full screen default I use for testing is 1920x1080 as I think that is the most common one.

**Comment by ayumihamsaki** [comment]
I was thinking, maybe add some rules for updating things such as leaving Version Numbers and/or where the update library location is for future people. For example, I got zero idea how to go ahead and update this file vendor inside the codeeditor found here:

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/vendor/emmet/emmet.js

**Comment by ayumihamsaki** [comment]
Still working on this pr .......

**Comment by ayumihamsaki** [comment]
@LukeTowers @w20k 

Ok I have done a combination of things:

1. Light background (non- main coding area) the icons are dark grey color:

pr-1

2. Main Coding area (place the icons in the grey area and also set the icons to a white color:

pr-2

3. Full screen mode (added my original idea):

pr-3

Will update the pr for more testing.

**Comment by w20k** [comment]
Perfect, for me @ayumihamsaki Lets wait for @LukeTowers opinion.

**Comment by LukeTowers** [comment]
@ayumihamsaki does the full screen mode block the top right if you're looking at a minified file which would have text all the way to the end?

Otherwise looking good to me!

**Comment by ayumihamsaki** [comment]
> does the full screen mode block the top right if you're looking at a minified file which would have text all the way to the end?

Yes it would block on the full screen mode at the top right.

I personally think the number of times that would cause a real world issue would be very small. It would only be an issue on the first line of code and if that was a problem, then just add an extra line or move the code down when editing and move it back up when finished.

Code is not the same as language in the sense code it is standardized using left to right (ltr) and language is left to right (ltr) and right to left (rtl). So that is why I think the problem would be very small (in fullscreen).

If you think its going to cause a big issue then maybe we should create a full icon bar above the fullscreen coding window at the top of the screen?

I leave you to decide on this.

**Comment by LukeTowers** [comment]
I'm fine with your comments on it. Thanks!

**Pull request merged**
