### PR TITLE
Bind auth check into page.beforeDisplay event 

### PR DESCRIPTION
**Pull request by tim0991**
in \Backend\Controllers\Users::__construct (#3215)

### CODE REVIEW

**Comment by LukeTowers** [comment]
Does this actually work? The __construct method runs before page.beforeDisplay and this code needs to be run before the list behavior is initialized.

**Comment by tim0991** [comment]
Yes, it works in my project
 After sign out, i view backend/backend/users/update/1 and backend/backend/userroles/update/1, they are get the same errors. 

If you don't do that,  in `Backend\Controllers\Users::__construct` will call `BackendAuth::getUser()` before sign, but  `BackendAuth::getUser()` return null, so it will be occur an error 

>Call to a member function isSuperUser() on null in modules/backend/controllers/users.php line 53

**Comment by munxar** [comment]
@tim0991 
I can see multiple things that go wrong:
1. call parent::_construct BEFORE you do anything else, because it already has the BackendAuth::getUser() implemented.
2. I don't think a constructor should execute this kind of complex logic, imho it should only initialize variables.
just listen to the 'backend.page.beforeDisplay' event, and implement you logic there.

**Comment by LukeTowers** [comment]
@tim0991 but does this code actually run and still accomplish it's original goal? i.e. removing the is_superuser list filter for backend users that aren't superusers?

**Comment by tim0991** [comment]
Ok, maybe we need another way to fix this

**Pull request closed without merging**
