### PR TITLE
Fixed the not exist variable issue

### PR DESCRIPTION
**Pull request by gergo85**
The new file hasn't got last modified value.

### CODE REVIEW

**Comment by LukeTowers** [comment]
> The new file hasn't got last modified value.
What do you mean?

**Comment by gergo85** [comment]
If I click on the Add button, I get the the following error message: "Undefined variable: lastModified"

**Comment by LukeTowers** [comment]
Submit this as a new PR with just those changes based off of the latest develop branch please.

**Comment by gergo85** [comment]
How to change my develop branch to the latest version?

**Comment by LukeTowers** [comment]
@gergo85 through github? Probably easiest to just delete your clone and refork it

**Comment by w20k** [comment]
Or use this approach: https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by LukeTowers** [comment]
Merged in #3885

**Pull request closed without merging**
