### PR TITLE
Fixes #2484, add missing `isCodeViewActive` method

### LINKED ISSUE #2484: Recent fix on the Pages plugin breaks Froala rich editor from loading properly
##### Expected behavior
The Froala rich editor should load fine.

##### Actual behavior
An error occurs when loading a page: `pages-snippets.js:22 Uncaught TypeError: richeditor.isCodeViewActive is not a function(…)`

##### Reproduce steps
Click on a page within the Pages plugin, the Froala rich editor should load fine.

##### October build
OctoberCMS `build 381`
Pages plugin `build 1.2.12`

[This](https://github.com/rainlab/pages-plugin/commit/a8c66bc048c6be6b1c8edca14d39a70af49970cd) recent commit fixing recursion on saving a page with snippets in code view introduces a bug where the Froala editor can't be loaded due to a missing `isCodeViewActive` function declaration in the `richeditor.js`.

I'm working on a pull request and i'll submit it as soon as i can test the code: since the Froala editor is protected by DRM, i'm going to manually inject a minified patch into my `build-min.js` to ensure it's working fine on my local copy.

### PR DESCRIPTION
**Pull request by manuelbua**

### CODE REVIEW

**Comment by daftspunk** [comment]
This code exists already in a2a0b207c611a4257c6d7c19365f4abb6d215f14

How are you updating October? It appears you may have a edge version of the Pages plugin, but stable version of October.

**Comment by manuelbua** [comment]
It looks like so, but i can confirm i set `cms.edgeUpdates` to `true` as stated [here](http://octobercms.com/docs/setup/configuration#edge-updates). Not sure why, but i can see the `develop` branch has the commit right there.. o_O

**Comment by daftspunk** [comment]
Not sure either, perhaps apply the patch manually for now until it reaches stable.

**Comment by manuelbua** [comment]
Yes, no problem, i did it already, thanks!

**Pull request closed without merging**
