### PR TITLE
Add last modified date to Pages, Partials, Layouts and Content

### PR DESCRIPTION
**Pull request by gergo85**
date

### CODE REVIEW

**Comment by LukeTowers** [comment]
@gergo85 please use `span` instead of `i`, `i` isn't an actual element.

**Comment by gergo85** [comment]
@LukeTowers I did it.

**Comment by LukeTowers** [comment]
@gergo85 thanks. What happens on mobile? Are users able to tap the icon to get the popup?

**Comment by gergo85** [comment]
@LukeTowers It works fine on mobile too (Chrome and Firefox).

**Comment by LukeTowers** [comment]
Awesome. Could you resolve the conflicts that Github says there are and then I should be able to merge it.

**Comment by gergo85** [comment]
I don't understand the Github again. I don't know what is the solution :( The Github doesn't allow to resolved this issue.

**Pull request merged**
