### PR TITLE
Disabled global AJAX events

### PR DESCRIPTION
**Pull request by VoroninWD**
Discussion: https://github.com/octobercms/october/issues/4278

### CODE REVIEW

**Comment by w20k** [comment]
@VoroninWD you've got me a bit wrong there :) It should be a configurable option, not global disable. So, make it true by default, and add option to specify option to override it. Via data-attribute and $.request. Thanks! Docs, plz!

**Comment by VoroninWD** [comment]
I'll do the documentation soon

**Comment by w20k** [comment]
Waiting for the next release to be merged ;)

**Comment by w20k** [comment]
@LukeTowers works as expected now and tested. What do we do with Docs?

**Comment by LukeTowers** [comment]
@w20k just merge his PR and then add a commit yourself to make the requested changes. Once that's done you can merge this one.

**Pull request merged**
