### PR TITLE
Add "onUpload" AJAX handler to FileUpload widget

### PR DESCRIPTION
**Pull request by alxy**
Potential fix for #4300

### CODE REVIEW

**Comment by mjauvin** [comment]
Tested in thr playground and it definitely fix all the issues I was having playing with this yesterday.

MUCH cleaner approach than what we started experimenting with.

**Comment by bennothommo** [comment]
@alxy Tested it and it works great. I've tried it in a few different configurations and didn't find any issues. Well done! Would you be up for applying the same fix to the MediaManager widget, as per @LukeTowers comment here: https://github.com/octobercms/october/issues/4300#issuecomment-487680319

**Comment by alxy** [comment]
> @alxy Tested it and it works great. I've tried it in a few different configurations and didn't find any issues. Well done! Would you be up for applying the same fix to the MediaManager widget, as per @LukeTowers comment here: [#4300 (comment)](https://github.com/octobercms/october/issues/4300#issuecomment-487680319)

I am not sure if I'd like to do this. The mediamanager is complex (just looked at it) and there are multiple ways to upload files (Via the widget itself, via `mediafinder`, via `richedtitor`) and currently there are no issues I am aware of. So why should we change it?

**Comment by w20k** [comment]
Later on today, will retest. Seems like it's ready.

**Comment by w20k** [comment]
@bennothommo looks good to me as well! Could be merged, I guess :)

**Pull request merged**
