### PR TITLE
Display active plugin count on updates page

### PR DESCRIPTION
**Pull request by Flynsarmy**
If you have disabled plugins, the plugin counter will now show `activeCount (totalCount)` like so:

### CODE REVIEW

**Comment by daftspunk** [comment]
I think this PR is missing a file? Scope should also be called `scopeIsEnabled`

**Comment by Flynsarmy** [comment]
Fixed. Sorry about that!

**Comment by daftspunk** [comment]
This is a weird feature, but ok.

**Comment by Flynsarmy** [comment]
Maybe it should say 54 (23 Active) ?

**Comment by Shahiem** [comment]
Or maybe you  can give it a green color

**Pull request merged**
