### PR TITLE
Update Ace Editor from 1.2.6 to 1.4.2

### PR DESCRIPTION
**Pull request by ayumihamsaki**
This PR relates to github Issue: https://github.com/octobercms/october/issues/3867

* Please note all the files have been updated.
* Files Changed and Updated 392 (big update - took me many hours to do!)
* I have added new files to update the features to allow the function of new API's in the code editor. (Since the previous update 3 years ago many new API's have been created).
* There was one file that has been dropped by ACE Editor and I have included it because I feel October CMS needs it. This file location can be found here: https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/vendor/ace/snippets/php-inline.js

There is one more issue (which I need to some help and advice about). The file `emmet.js` seems to be part of the ace editor, but I don't know where to update the new file? Why it is so big? As emmet now uses code splitting and that file has been broken up into smaller files (due to performance issues).

If anyone could help on `emmet.js` on any suggestions that would be great. I may create a separate PR for that - as the big is crazy big!

The file location is found here: https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/vendor/emmet/emmet.js

(Will add Patch in Comment below - for testing)

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Patch File Found here: https://github.com/ayumihamsaki/patches/blob/master/ace-editor/0001-Update-Ace-Editor-from-1.2.6-to-1.4.2.patch

@w20k Sorry so big at 11.3Mb

**Comment by ayumihamsaki** [comment]
> This update should fix issues and add many new features to October CMS with regards to the code editor. I manually had to edit every file and my head is spinning so will check back on this PR tomorrow!

**Comment by w20k** [comment]
It doesn't matter @ayumihamsaki, I'm using Intellij Idea 😉

I guess you have to build emmit.js (https://github.com/emmetio/emmet). 
`yarn && gulp all`
But I need to double check, what would be in the end 😄Is it the same file or not. Seems like...

**Comment by w20k** [comment]
@ayumihamsaki, could you look at the 'emmit.js'? I'd like to move on with upgrades. I hope we could finish a few more, before New Year 😉

I remember, that you've asked me to look at the `eval issue` before we finished with Ace.js update. Sadly, won't have time. Only in a new year.

**Comment by ayumihamsaki** [comment]
@w20k Yah, I am also keen to get the upgrades rolling. I was waiting for you to do the emmit.js I'm not sure how to build it (because I don't know where the gulp files are stored that were used to build it in the first place). Secondary I don't know where the correct repo is for this one. It has many repo's for emmit.js ?

Is it possible to just test the ace first and then we can do the emmit.js later, I will make a note of it.

That eval issue is at the top of my list, but I don't mind if it's gets done in jan 2019. I was going to ask you how it is going your side on that.

I am keen to try and upgrade the jquery cookie file. I feel that is a security risk right now as it is very old. So I want to update that file this year if possible.

**Comment by w20k** [comment]
@ayumihamsaki, let's do this way. Add emmit.js to your list of Todos. Will check Ace.js and let you know!
My bad didn't know you were waiting for me 😄

**Comment by w20k** [comment]
Should be this script, if I understood correctly from the Ace.js demos: https://github.com/ajaxorg/ace/blob/c3403f1fbdf22cfff2cb1dda584b8e04467cd372/demo/kitchen-sink/demo.js#L539

**Comment by ayumihamsaki** [comment]
@w20k So you are saying to replace this file:

https://raw.githubusercontent.com/octobercms/october/master/modules/backend/formwidgets/codeeditor/assets/vendor/emmet/emmet.js

With this code:

https://cloud9ide.github.io/emmet-core/emmet.js

**Comment by ayumihamsaki** [comment]
@w20k Ok I have updated that with the ace editor (kitchen-sink demo) build.

For future ref, I added the following comment tag (but I could NOT find the exact version number they used):

```
/*! This file has been taken from the ace editor Everything under the kitchen sink build
 *  which can be found at the following location: https://cloud9ide.github.io/emmet-core/emmet.js
 *  Could not find a version number but this version is after 2017 for future reference
 */
```

Please go ahead and test this oh I try to create a patch as well for you.

**Comment by ayumihamsaki** [comment]
Two patches for you, see folder:

https://github.com/ayumihamsaki/patches/tree/master/ace-editor-and-emmet

**Comment by w20k** [comment]
@ayumihamsaki, I have to look at it closer. There is an error with themes, for some reason. Will try to find the cause before Xmas 😄

**Comment by ayumihamsaki** [comment]
haha good luck

**Comment by w20k** [comment]
@ayumihamsaki, could you send me a link which version you used?

https://github.com/ajaxorg/ace-builds/tree/0d62c26de7b2e1922d8dd95ba587c9845c018c51 - this on? min-nonconflict/nonconflict?

**Comment by ayumihamsaki** [comment]
@w20k I took the files from here: https://cdnjs.com/libraries/ace

**Comment by w20k** [comment]
@ayumihamsaki, don't think so. You could reproduce it too. Just change the theme. It doesn't load themes-xx.js files at all. Or better to say they don't contain any css data.

**Comment by ayumihamsaki** [comment]
@w20k Yah I see it, I get the following error message:

"Uncaught ReferenceError: define is not defined at theme-twilight.js:2"

http://localhost/modules/backend/formwidgets/codeeditor/assets/vendor/ace/theme-twilight.js

Must not be connected, will have a look where it is getting referenced.

**Comment by ayumihamsaki** [comment]
@w20k Yah I see it, I get the following error message:

"Uncaught ReferenceError: define is not defined at theme-twilight.js:2"

http://localhost/modules/backend/formwidgets/codeeditor/assets/vendor/ace/theme-twilight.js

From researching the issue the solution is:

"You are getting this error because the RequireJS JavaScript library has not been included in your page.
To fix this either use an ace build or include RequireJS in your page".

> I'm going to rebuild it with the "[src concatenated but not minified version](https://github.com/ajaxorg/ace-builds/tree/master/src)".

**Comment by w20k** [comment]
@ayumihamsaki, 'using ace build' - sounds like a plan.

**Comment by w20k** [comment]
Don't worry about patched versions 😉Don't need it for now.

**Comment by ayumihamsaki** [comment]
Ok will do, give me a few hours. I want to manually comment in the version number in to all the files for easy future ref.

**Comment by ayumihamsaki** [comment]
@w20k I updated the build, exactly the same problem. Then I added `require.js` to the `_head.htm` then get a conflict with` storm-min.js` see here:

untitled

What do you want to do?

I can create a new commit and add the new build and the `require.js` with a patch to see where the storm conflict is happening?

**Comment by ayumihamsaki** [comment]
I used the "src-noconflict" build - which uses ace.require instead of require. Same issue as before, don't know what's wrong?

**Comment by w20k** [comment]
@ayumihamsaki, not yet, but I think there is a bug somewhere...trying to figure it out.

**Comment by ayumihamsaki** [comment]
@w20k 

ok, please ignore the 3758b59 commit and use the a07e27f.

**Comment by w20k** [comment]
Yep, @ayumihamsaki, "src-noconflict" build seems like doing the thing. But will ping @LukeTowers, after running a few more tests.

**Comment by LukeTowers** [comment]
@ayumihamsaki what's the status on this?

**Comment by LukeTowers** [comment]
Related: https://github.com/octobercms/october/issues/3443

**Comment by ayumihamsaki** [comment]
best to ask @w20k he said there is a bug on testing somewhere ? I was waiting for his reply to proceed on this pr.

**Comment by w20k** [comment]
@LukeTowers @ayumihamsaki will get back to this PR soon :)

**Comment by ayumihamsaki** [comment]
Closing this - please go to an updated version here: https://github.com/octobercms/october/pull/4585

p.s. It has a cleaner set of notes for future ref.

**Pull request closed without merging**
