### PR TITLE
$filePath in the media.file.upload e. by reference

### PR DESCRIPTION
**Pull request by pavelmgn**
Passing the $filePath variable in the media.file.upload event by reference
https://github.com/octobercms/october/issues/3124#issuecomment-529603481

### CODE REVIEW

**Comment by bennothommo** [comment]
@pavelmgn If you are working on a fork, you will need to make your changes on your own `develop` branch too. It looks like you are currently working on your fork's `master` branch, which means that it may be missing changes that have been made since the last update to the `master` branch nearly a month ago. This is why there is a merge conflict currently.

**Comment by pavelmgn** [comment]
@bennothommo sorry =( I`m trying sorry = (I'll try now to do everything right
https://github.com/octobercms/october/pull/4616

**Comment by bennothommo** [comment]
@pavelmgn no stress! Your latest PR is correctly submitted - I apologise for having to ask you to do it again, but it's simply to make it easier for us to review and merge. You're doing great :)

**Comment by pavelmgn** [comment]
@bennothommo thx =)

**Pull request closed without merging**
