### PR TITLE
hebrew lang

### PR DESCRIPTION
**Pull request by mhmdasli**
hebrew lang

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/.github/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
@mhmdasli this doesn't work. Firstly, the file needs to be named modules/backend/lang/he/lang.php, there are a few other files that need to be added too, and entries need to be made to the Language preferences array as well as a language key for the default language (English)

**Comment by w20k** [comment]
@mhmdasli take a look at the latest update for `tr` language. Just an example: https://github.com/octobercms/october/pull/4121/files

**Comment by LukeTowers** [comment]
@mhmdasli see https://github.com/octobercms/october/pull/3694 for an example of how to properly add a new language.

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Pull request closed without merging**
