### PR TITLE
Add keyboard navigation and focus ring for radio buttons , slider switches and list fields

### PR DESCRIPTION
**Pull request by ayumihamsaki**
Relates to this github issue: https://github.com/octobercms/october/issues/4454

and

This issue: #4473

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
This is a work in progress it's to give @w20k an idea what I've come up with so far, before he re-writes it all. 😄

**Comment by ayumihamsaki** [comment]
### How to use keyboard controls with radio buttons

- Use the '**Tab**' to select the radio button which is checked.

- Use the '**Arrow**' keys to select the un-checked radio buttons.

- Use '**Return/Enter**' to select the un-checked radio button into checked.

**Comment by ayumihamsaki** [comment]
### How to use keyboard controls with slider switches

- Use the '**Tab**' to select the slider switch.

- Use the '**Space bar**' to toggle between checked and unchecked.

aaa

**Comment by ayumihamsaki** [comment]
> Conflicting files
> modules/backend/assets/css/october.css

I 100% need to change this bit of code!

**Comment by ayumihamsaki** [comment]
> Conflicting files
> modules/backend/assets/css/october.css

**I need to 100% change this bit of code!**

**Comment by ayumihamsaki** [comment]
To do:

### Switch

1. I need to add the javascript code to update the `aria-checked` controls.

2. There is no focus ring setup on the switch, I will add it in via javascript.

### Record finder

3. I can't reproduce your error, I tested it on several plugins. Could you try doing a hard refresh on the browser. Also let me know if you change the standard record finder field in anyway. Just because I can't reproduce it doesn't mean I think there is not an error somewhere?

**Comment by Eoler** [comment]
> ### Record finder
> I can't reproduce your error, I tested it on several plugins. Could you try doing a hard refresh on the browser. Also let me know if you change the standard record finder field in anyway. Just because I can't reproduce it doesn't mean I think there is not an error somewhere?

Definitely seeing changes from this commit in inspector: https://github.com/octobercms/october/pull/4475/commits/18b9e9fab46eb4a9e9ec5f920f49a0c214b738b7
but there's still jumpity-jump as seen in screen-recording. It is possible that I didn't pick every required change for this fix...

**Comment by ayumihamsaki** [comment]
@Eoler 

This is what I get: https://www.youtube.com/watch?v=z7S0avgOUm8

Could you investigate it further and let me know. Also if you changed anything from the default setting fo the record finder from the one I tested.

**Comment by bennothommo** [comment]
@ayumihamsaki Would you mind reverting https://github.com/octobercms/october/pull/4494/commits/66b774b424e3760910c616db6b4388052e4067b0 for us? I'll make the change directly on the `master` branch and credit you for it.

**Comment by Eoler** [comment]
> This is what I get: https://www.youtube.com/watch?v=z7S0avgOUm8
> Could you investigate it further and let me know. Also if you changed anything from the default setting fo the record finder from the one I tested.

My record finders aren't customized in any way, but now I'm sure that I'm missing some of your changes.

**Comment by ayumihamsaki** [comment]
@Eoler I think I know what the problem might be:

sss

I think you missing this commit. Need to remove those two css things and then the `position: absolute` will work, if not then things will move around using `position: relative`

**Comment by ayumihamsaki** [comment]
Added focus ring - pretty happy with the result:

ezgif-2-3137c95b2bab

**Comment by Eoler** [comment]
> @Eoler I think I know what the problem might be:
> I think you missing this commit. Need to remove those two css things and then the `position: absolute` will work, if not then things will move around using `position: relative`
> Do it manually maybe, because that file has a conflict and maybe blocking adding it automatically.

Yep, cherry-picking that made it work like on your video!
But (I know, it's a complex widget ;) there's also focusable text element inside of it when record is selected - not highlighted at the moment.

**Comment by ayumihamsaki** [comment]
> there's also focusable text element inside of it when record is selected - not highlighted at the moment.

I do that next.

**Comment by ayumihamsaki** [comment]
Added keyboard navigation to all the list fields, see gif for example:

ezgif-2-e9d8b7c28745

**Comment by ayumihamsaki** [comment]
@LukeTowers @bennothommo @w20k 

Ok this PR is finished now.

It adds keyboard naivgation and focus ring support to the following:

- radio buttons
- slider switches
- list forms

Just need the https://github.com/octobercms/october/pull/4401 unmerged and I will fix that so this pr doesn't have a conflict.

Then hopefully testing passes ok.

**Comment by ayumihamsaki** [comment]
This pr is broken if you look at the commits they are not connected to my account, I have deleted my fork and created a fresh new fork and new branch, please go to here for new version: https://github.com/octobercms/october/pull/4501

**Pull request closed without merging**
