### PR TITLE
Many translations to pt-br

### PR DESCRIPTION
**Pull request by prhost**

### CODE REVIEW

**Comment by LukeTowers** [comment]
@bennothommo up to you if you want to include this in 457 or just wait for 458

**Comment by bennothommo** [comment]
@LukeTowers should be safe to include in 457 - it's just maintenance and shouldn't affect functionality.

@prhost Would you mind minifying your update lang object so that it's a one-liner like the other languages?

**Comment by LukeTowers** [comment]
@prhost note that you should run `php artisan october:util compile lang` to compile the client side language file.

**Comment by prhost** [comment]
a silly question, how do I download the dependencies of the composer? Because I run composer install, and it downloads fixed versions of the modules, I'm forced to commit those changes, do I change composer.json to "dev-develop" those packages?

**Comment by LukeTowers** [comment]
@prhost see the development version of composer.json here: https://octobercms.com/docs/console/commands#console-install-composer

**Comment by prhost** [comment]
compiled the langs and translated more that was missing from the other modules, Portuguese is complete 😍

**Comment by bennothommo** [comment]
Good work @prhost :)

**Pull request merged**
