### PR TITLE
Add Filter Buttons

### PR DESCRIPTION
**Pull request by Teranode**

### CODE REVIEW

**Comment by w20k** [comment]
Tested, works as expected ;) 
GIF [Clear/Apply]: oct-26-2018 13-00-40

**Comment by LukeTowers** [comment]
@Teranode @w20k Could we have the buttons only appear when options are selected to be able to Apply or Clear?

**Comment by Teranode** [comment]
@LukeTowers i would love to but wouldn't know how, I was able for it to only toggle via if items were selected, but the issue arises when you click out of the popover then back in.

**Comment by LukeTowers** [comment]
@Teranode trying to test it but it's not working on the groups filter: https://9e74b200410a.octodock.com/backend

**Comment by Teranode** [comment]
@LukeTowers what do you mean?

**Comment by w20k** [comment]
@LukeTowers @Teranode was so fast, that you've already got his latest fix to show button group, only if filter was selected.
Will double check this feature with mine setup as well.

oct-27-2018 13-59-01

**Comment by Teranode** [comment]
@LukeTowers need someone else to do it cause ive got previous work on those assets

**Comment by LukeTowers** [comment]
@Teranode thanks for your work on this!

**Pull request merged**
