### PR TITLE
tiny fix to css issue

### PR DESCRIPTION
**Pull request by Teranode**
In response to: https://github.com/octobercms/october/issues/3506
which might be connected to https://github.com/octobercms/october/issues/3745 and https://github.com/octobercms/october/issues/1698

### CODE REVIEW

**Comment by w20k** [comment]
Tested - works like charm ;)

Images:
overlay-zindex
menu-zindex

Gif:
oct252018163317

**Comment by Teranode** [comment]
@w20k thanks for showing me that mis-typed lang in the popup

**Comment by w20k** [comment]
@Teranode, and rebuild assets ;)

**Comment by Teranode** [comment]
@w20k ?

**Comment by w20k** [comment]
@Teranode -> 'php artisan october:util compile less' ? :) Or I'm just missing things out))

**Pull request merged**
