### PR TITLE
Respect database tables config.

### PR DESCRIPTION
**Pull request by sw-double**
This does not alter default behaviour and allows proper configuration

### CODE REVIEW

**Comment by LukeTowers** [comment]
@daftspunk Looks good to me. As a side note, should October introduce support for fully configurable system table names so that all of the table names (not just the few already supported) would support configured table names?

**Comment by sw-double** [comment]
LGTM? Otherwise what's the point of having configuration options that are actually unusable without hacking the core?

Laravel supports them, I don't see why october should not.

**Comment by LukeTowers** [comment]
Not sure if there's a bit of confusion here or not, just telling @daftspunk that your PR is easily mergeable.

I also added a comment about potential future improvements to core, which admittedly was poorly worded. Apologies for any confusion.

**Comment by sw-double** [comment]
Ready

**Comment by sw-double** [comment]
Fixed.

**Pull request merged**
