### PR TITLE
Fixed relation not being refreshed on dissociate (unlink) action

### LINKED ISSUE #3470: BelongsTo (HasMany) Relation Unlink and Display Issues
##### Reproduce steps
https://stackoverflow.com/questions/49492510/octobercms-belongsto-hasmany-relation-issues

##### October build
434

Following the description from linked Stackoverflow issue and by @LukeTowers suggestion I tried to reproduce the issue using  [test plugin](https://github.com/daftspunk/oc-test-plugin).

I slightly changed `Posts` `Status` field and got this:

image

So, the layout issue was not reproduced (probably it is connected with specific styles on RainLab/BlogPost page), but the unlinking issue is still there. Here's the demo video: https://youtu.be/Zz9oOCf3UN4

This is the only change that I made to oc-test-pugin in plugins/october/test/models/post/fields.yaml:

from 

```
status:
        label: Status
        type: partial
        path: $/october/test/controllers/posts/_status.htm
        span: auto
        commentAbove: Generic model filtered by relation conditions.
        context: [create, update, relation]
```

to

```
status:
        label: Status
        type: relation
        span: auto
        commentAbove: Generic model filtered by relation conditions.
        context: [create, update, relation]
```

### PR DESCRIPTION
**Pull request by GinoPane**
Fixed relation not being refreshed on dissociate (unlink) action for one-to-many relations.
Fixes #3470

### CODE REVIEW

**Comment by LukeTowers** [comment]
Can you push another commit to this PR to rerun the tests? They were broken because of a recent config change.

**Comment by GinoPane** [comment]
Yes, no problem, will do.

**Comment by LukeTowers** [comment]
@w20k could you test this?

**Comment by w20k** [comment]
Hi @LukeTowers in the current build, I can't reproduce this issue.

**Comment by LukeTowers** [comment]
Sounds like it's been fixed since this was opened then. @GinoPane if you still encounter this issue in the latest build or dev branch then please comment with a detailed list of instructions to replicate the issue in a clean copy of October.

**Comment by paishin** [comment]
I am on build 458 and this issue has not been resolved.

**Comment by bennothommo** [comment]
Replaced by #4741.

**Pull request closed without merging**
