### PR TITLE
add helper info for the util cmnd

### PR DESCRIPTION
**Pull request by ctf0**

### CODE REVIEW

**Comment by ctf0** [comment]
u mean like adding the available cmnds instead ?

**Comment by LukeTowers** [comment]
Yes, like `php artisan create` would do

**Comment by ctf0** [comment]
screen shot 2017-02-15 at 6 40 25 pm

**Comment by LukeTowers** [comment]
Instead of a hardcoded list, I'd like to see you get the methods in the class, and then based on the methods available starting with 'util' (which the fire method uses to figure out what command to actually call), generate the list of available commands dynamically from that instead.

For example:
```php
public function utilCompileLang() {}
public function utilPurgeThumbs() {}
```
Would generate the list:
```
Did you mean one of these?
    october:util compile lang
    october:util purge thumbs
```

**Comment by ctf0** [comment]
screen shot 2017-02-16 at 9 19 53 am

**Comment by LukeTowers** [comment]
One last change and it should be good to go, please prefix the listed commands with the previous `october:` so that they follow the format `october:util compile lang`.

Thanks again for your work on this!

**Comment by ctf0** [comment]
to confirm
> note that some methods are still un-finished ex.`purge uploads`

**Comment by LukeTowers** [comment]
@ctf0 That's fine with me. If you want, you can add a list of stub methods that aren't finished yet in order to ignore and have those hardcoded, but I'm perfectly fine with leaving it as it is right now.

As a note, just noticed now, you have made the PR to the master branch, you need to make it to the develop branch instead. Please change that and then hopefully we can get this merged.

**Comment by LukeTowers** [comment]
As soon as the check completes, I'll merge this.

**Pull request merged**
