### PR TITLE
Fix csrf in framework js

### PR DESCRIPTION
**Pull request by keiosweb**
Related to: octobercms/library#105, extracts XSRF token from cookie and injects it into AJAX request as a X-XSRF-TOKEN header (works exactly the same as in angular.js).

Upgraded previous PR by implementing $.ajaxPrefilter. This will allow requests not using $.request syntax ($.ajax, $.get) to get X-XSRF-TOKEN header too.

### CODE REVIEW

**Comment by keiosweb** [comment]
Twin PR: https://github.com/octobercms/library/pull/116

**Comment by daftspunk** [comment]
Still thinking about the best way to tackle this -- see https://github.com/octobercms/library/issues/105#issuecomment-113749344 for notes.

**Comment by LukeTowers** [comment]
@daftspunk Please copy content from linked issue as the library repository no longer supports issues.

**Comment by daftspunk** [comment]
Let's leave this for now. We can to keep the front-end open and free. We need a non intrusive way to approach it, perhaps CSRF can be implemented as a plugin.

**Pull request closed without merging**
