### PR TITLE
Fixes richeditor bug where cursor position is lost when in adding an image in media finder

### PR DESCRIPTION
**Pull request by rejuvenatedigital**
Fixes richeditor bug where when in the Froala editor and adding an image part way through content the cursor position is lost and the image is added to the top of the editor.

This only happens when creating a new folder in the media manager as the cursor is in the folder name field in the media finder.

### CODE REVIEW

**Comment by w20k** [comment]
@rejuvenatedigital before/after image would be helpful! ;) Thanks!

**Comment by rejuvenatedigital** [comment]
> @rejuvenatedigital before/after image would be helpful! ;) Thanks!

Sorry I'm not quite sure what you mean here?

**Comment by w20k** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by rejuvenatedigital** [comment]
Ah sorry, I'll make sure to do that next time thank you, also just an FYI your link to the contributing guidlines doesn't work.

**Comment by w20k** [comment]
@rejuvenatedigital will rephrase a bit, could you provide a gif or a screenshot of your issue, before and after you apply a fix. 
It's a copy past, link was changed - thanks ;)

**Comment by rejuvenatedigital** [comment]
@w20k please find attached screenshots of before and after pull request changes were applied
before 1
before 2
after

**Comment by w20k** [comment]
@rejuvenatedigital why did you close your PR, is there a reason, or misclick ? :)

**Comment by rejuvenatedigital** [comment]
@w20k sorry I haven't used github much before and have closed it by mistake

**Comment by w20k** [comment]
@rejuvenatedigital could you also recompile the assets: `php artisan october:util compile js`. Will test this out!

**Comment by rejuvenatedigital** [comment]
@w20k assets have been re-compiled. Cheers

**Comment by w20k** [comment]
@rejuvenatedigital  Looks good!
@LukeTowers - done.

Status - ✅

**Pull request merged**
