### PR TITLE
Translation catalan

### PR DESCRIPTION
**Pull request by mariavilaro**
This is the translation to catalan language.

There's a problem when adding the locale to the preferences locale select: in the flags png there are no flags for languages that are not equivalent to countries. Catalan is spoken mainly in Spain but also in France and the flag is this one: https://en.wikipedia.org/wiki/Senyera

How could we add this flag? (and I suspect in a future there will be more cases like this one)

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mariavilaro for new flags we could look at integrating https://github.com/lipis/flag-icon-css instead of a single image file, but I don't have time to do that so someone else would need to make a PR to do it.

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by mariavilaro** [comment]
Ouch sorry my mistake! thanks!

**Comment by LukeTowers** [comment]
@mariavilaro No worries 😄 What do you think about the flag CSS library I linked?

**Comment by mariavilaro** [comment]
It looks good! I will try to get on it when I'm done with my current project.

**Pull request merged**
