### PR TITLE
Files in the media library can now contain two dots

### PR DESCRIPTION
**Pull request by JoelESvensson**
The previous if-statement checked if the path contained two dots. This ment that that valid file names containing two dots where considered invalid

### CODE REVIEW

**Comment by daftspunk** [comment]
This check is for security reasons, so we need to approach this carefully. Have you checked that the Windows syntax doesn't slide past? Eg:

```
somefile\..\..\..\config\app.php
```

**Comment by JoelESvensson** [comment]
You are absolutely right. I did not think of other file systems. Also, it is valid for files to start with two dots. This pull request doesn't cover that

**Comment by JoelESvensson** [comment]
I just updated the commit to cover all cases I can think of

**Comment by JoelESvensson** [comment]
@daftspunk Is the PR okay now?

**Comment by daftspunk** [comment]
Will take a look soon, thanks!

**Comment by daftspunk** [comment]
Would you mind fixing #1681 as part of this too?

**Comment by JoelESvensson** [comment]
Sure i'll take a look at it. Right now I don't know where the @-sign gets stripped though

**Comment by opterons** [comment]
here is the fix for the @ symbol in file name bug:

file: modules/cms/widgets/MediaManager.php
line: 1004
function: validateFileName
dependant functions: onApplyName, onCreateFolder, checkUploadPostback
from: if (!preg_match('/^[0-9a-z\.\s_\-]+$/i', $name)) {
to: if (!preg_match('/^[0-9a-z@\.\s_\-]+$/i', $name)) {
comment: added a @ into the regular expression to allow the @ symbol in file names when renaming/moving/creating/uploading.

**Comment by JoelESvensson** [comment]
Thanks @opterons! Do you mind if I make the changes or would you like to do it yourself?

**Comment by JoelESvensson** [comment]
Line 976 is the line that replaces the file name
```
            if (!$this->validateFileName($fileName)) {
                $fileNameSlug = Str::slug(File::name($fileName), '-'); // Line 976
                $fileName = $fileNameSlug.'.'.$extension;
            }
```

This requires us to replace Str::slug with our own function. It shouldn't be too hard. I'll push a commit for it soon

**Comment by opterons** [comment]
@JoelESvensson you can go ahead man. I'm really new to Git when it comes to pushing changes and shit. I had literally just installed OC and had been playing around with it for a few hours before I checked the Issues. Damn fine CMS you guys have put together! I've been a web developer for going on 14 years and a lot of the functionality is exactly how I put my own CMS together. If you guys want any help I'll lend a hand when I can. 

Just curious what is the reasoning behind replacing the Str::slug function with a new one? Also keep in mind this bug does not only affecting when you upload a file but also when you move or rename a file in the Media Manager. That's why I targeted the validateFileName function since it was a self contained function for the Media Manager.

**Comment by jwilson8767** [comment]
@opterons welcome to the team. If you're not already in the #october irc channel it's pretty active/useful. Also, of course we'd like help. Usually just addressing/patching issues is a huge thing, but even just building plugins is a great way to contribute to the community.

**Comment by JoelESvensson** [comment]
@opterons `Str::slug` is the function that strips the `@`-signs which is what #1681 is about.

Also, welcome! I really hope you'll make more contributions.

**Comment by JoelESvensson** [comment]
@daftspunk #1681 is also fixed now

**Comment by daftspunk** [comment]
Thanks for this

**Pull request merged**
