### PR TITLE
Hiding empty block, if there are no buttons

### PR DESCRIPTION
**Pull request by PopcornPHP**

### CODE REVIEW

**Comment by daftspunk** [comment]
It is possible for a toolbar to have search with no buttons. This would cause it to break?

**Comment by PopcornPHP** [comment]
If no buttons - displays an empty block above the table. This change - solely visual effect. I doubt that this can break system

**Comment by daftspunk** [comment]
Is this relation controller? We can't accept this PR because it will break the toolbar search (no buttons + search).

It's difficult to discuss a solution without first understanding the problem. Please, explain the problem itself and not the solution that you have in mind. For more info on presenting your problem see http://mywiki.wooledge.org/XyProblem. Thanks!

**Comment by daftspunk** [comment]
If using `ListController` you can set this in the config_list.yaml and will do the same thing:

```
toolbar: null
```

If you are using `RelationController` you can use a similar solution:

```
myrelation:
    view:
        showSearch: false
        toolbarButtons: false
```

**Pull request closed without merging**
