### PR TITLE
Update Raphaël 2.1.2 to 2.2.7 and Eve 0.4.2 to Eve 0.5.4 (Combined File)

### PR DESCRIPTION
**Pull request by ayumihamsaki**
This updates a single file with the following package updates:

Update Raphaël 2.1.2 (Aug 26, 2013) to 2.2.7 (Nov 12, 2016)
Eve from 0.4.2 (2013) to Eve 0.5.4 (2017)

> WORD OF WARNING - I think Raphaël is a dead project and hasn't been updated in a very long time! It would be better and safer if maybe October moved over to using the [D3.js](https://d3js.org/) library. (To future proof October CMS - however would require a lot of work and updates to remove and update everything). Or October CMS could expand its current features using: https://github.com/nhnent/tui.chart which is a JavaScript data visualization library which makes uses of Raphaël.js to create a wide variety of charts & graphs using SVG. Examples can be found here: https://nhnent.github.io/tui.chart/latest/tutorial-example01-01-bar-chart-basic.html

## File Locations for Testing

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/chart.pie.js
https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/chart.bar.js
https://github.com/octobercms/october/blob/master/modules/system/assets/ui/storm.js

## Patch for Testing

https://github.com/ayumihamsaki/patches/tree/master/raphael-eve

## Related to Github Issue

Found here: https://github.com/octobercms/october/issues/3867

### CODE REVIEW

**Comment by LukeTowers** [comment]
@ayumihamsaki do you think you could do up a PR to the test plugin showcasing some examples of how these libraries get used in October to more easily test them? Or perhaps @w20k or @Teranode would be willing to?

**Comment by w20k** [comment]
@LukeTowers If @ayumihamsaki  or @Teranode would have time to deal with showcases - would be awesome! 

While testing myself I'd also have to play around with OCMS components, to see if upgrade didn't break anything 👍

**Comment by ayumihamsaki** [comment]
Would it be worth using something like https://github.com/marketplace/dependabot to try and speed up this process?

**Comment by LukeTowers** [comment]
@ayumihamsaki perhaps, but does it handle dependencies that aren't managed by package manager files, i.e. all of October's JS dependencies?

**Comment by w20k** [comment]
@ayumihamsaki , I haven't used it also, but we could play with it on forked repos, I think :)

**Comment by ayumihamsaki** [comment]
@LukeTowers @w20k 

- I came across it last week and thought it might be useful to October CMS? (I not played around with it yet)
- I was suggesting it as a long term use case - to make things easier in the future, for keeping things up to date and easier to manage.
- Yes agree it would require a lot of work to change and modify things in October, I was thinking it maybe a good long term strategy to make things easier.
- Agree best to create a test repo for it and see what the benefits - if any for October.

(I just think updating these things manually is not the best long-term solution)

**Comment by ayumihamsaki** [comment]
Also I want to mention with regards to using `tui.chart` currently October has I think three visual displays:

- Pie chart
- Line chart
- Bar chart

As per webpage: https://octobercms.com/docs/ui/chart

With tui.chart we could give October these charting features:

- Area Chart
- Bar Chart
- Box Plot Chart
- Bubble Chart
- Bullet Chart
- Column Chart
- Column Line Combo Chart
- Heatmap Chart
- Line Area Combo Chart
- Line Chart
- Line Scatter Combo Chart
- Map Chart
- Pie Chart
- Pie Donut Combo Chart
- Radial Chart
- Scatter Chart
- Treemap Chart

* I believe `tui.chart` uses `Raphaël` and not `D3.js` though.

**Comment by w20k** [comment]
Found a good example for testing, with dummy data, but works without problem (LineCart: https://octobercms.com/docs/ui/chart, scoreboard PieChart:https://octobercms.com/docs/ui/scoreboard).
@LukeTowers , @ayumihamsaki what do you think should I also test with real data also?

Code example:
```
<div class="scoreboard">
	<div data-control="toolbar">
		<div class="scoreboard-item control-chart" data-control="chart-pie">
			<ul>
				<li data-color="#95b753">Published <span>84</span></li>
				<li data-color="#e5a91a">Drafts <span>12</span></li>
				<li data-color="#cc3300">Deleted <span>18</span></li>
			</ul>
		</div>

		<div class="scoreboard-item control-chart" data-control="chart-bar">
			<ul>
				<li data-color="#95b753">Published <span>84</span></li>
				<li data-color="#e5a91a">Drafts <span>12</span></li>
				<li data-color="#cc3300">Deleted <span>18</span></li>
			</ul>
		</div>

		<div class="scoreboard-item title-value">
			<h4>Weight</h4>
			<p>100</p>
			<p class="description">unit: kg</p>
		</div>

		<div class="scoreboard-item title-value">
			<h4>Comments</h4>
			<p class="positive">44</p>
			<p class="description">previous month: 32</p>
		</div>

		<div class="scoreboard-item title-value">
			<h4>Length</h4>
			<p class="negative">31</p>
			<p class="description">previous: 42</p>
		</div>

		<div class="scoreboard-item title-value">
			<h4>Latest commenter</h4>
			<p class="oc-icon-star">John Smith</p>
			<p class="description">registered: yes</p>
		</div>

		<div class="scoreboard-item title-value" data-control="goal-meter" data-value="88">
			<h4>goal meter</h4>
			<p>88%</p>
			<p class="description">37 posts remain</p>
		</div>

		<div class="scoreboard-item title-value goal-meter-inverse" data-control="goal-meter" data-value="88">
			<h4>goal meter</h4>
			<p>88%</p>
			<p class="description">37 posts remain</p>
		</div>
	</div>
</div>

<div data-control="chart-line"
		data-time-mode="weeks"
		style="height: 200px;"
		data-chart-options="xaxis: {mode: 'time'}">
    <span
			data-chart="dataset"
			data-set-color="#008dc9"
			data-set-data="[1477857082000, 400], [1477943482000, 380], [1478029882000, 340], [1478116282000, 540], [1478202682000, 440], [1478289082000, 360], [1478375482000, 220]"
			data-set-name="Visits">
    </span>
</div>
```

**Comment by ayumihamsaki** [comment]
@w20k Maybe test on the dashboard as well? Install some test plugins on the dashboard like the two most popular ones:

https://octobercms.com/plugin/rainlab-googleanalytics
https://octobercms.com/plugin/indikator-backend

I can't think of anything else where else to test it.

**Comment by w20k** [comment]
@ayumihamsaki Good call! Will do it tomorrow 😉

**Comment by LukeTowers** [comment]
@gergo85 could you test this change with your plugins? I know you utilize a few of them. @adrenth  perhaps you could also test with the Redirect plugin: https://octobercms.com/plugin/vdlp-redirect

**Comment by w20k** [comment]
Not a lot of data, thought 😉  But no errors, yet!

https://octobercms.com/plugin/indikator-backend - **Done**
Screenshot:
screenshot 2018-11-29 at 13 03 11


https://octobercms.com/plugin/vdlp-redirect - **Done**
Screenshot:
screenshot 2018-11-29 at 13 02 13

**Pull request merged**
