### PR TITLE
update modules/backend/lang/zh-cn/lang.php file

### PR DESCRIPTION
**Pull request by buuug7**
this file can't keep up with the `en/lang.php` step, i update `modules/backend/lang/zh-cn/lang.php` file, keep synchronized with  `en/lang.php`

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by buuug7** [comment]
@LukeTowers i need to have a new pull request??

**Comment by LukeTowers** [comment]
No, you can change the base branch of a pull request just by editing the title, then it gives you an option to change the base branch.

**Comment by buuug7** [comment]
@LukeTowers thanks, i already delete the fork before you merge , now ,i have nothing to do with it .

**Pull request merged**
