### PR TITLE
Update richeditor.css & _froala.less

### PR DESCRIPTION
**Pull request by Lavrushin**
.fr-popup .fr-input-line input + label, .fr-popup .fr-input-line textarea + label

I only changed one z-index parameter from 3 to 1.

Before: http://prntscr.com/lwub7q
After: http://prntscr.com/lwubfh

### CODE REVIEW

**Comment by Lavrushin** [comment]
I only changed background parameter to transparent.

**Comment by w20k** [comment]
Thanks!
@Lavrushin will look at it today. Might be the problem with `.less` assets, from flora, not compiled dynamically...

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by w20k** [comment]
@Lavrushin, sry, you have to add it to '.css' file instead. We cannon contribute to less files of the flora engine.

**Comment by w20k** [comment]
Status - ✅
screenshot 2018-12-26 at 11 31 34

>only @daftspunk can compile the assets

Related to @LukeTowers comment in #3225

**Comment by LukeTowers** [comment]
@Lavrushin keep the change in the LESS file too please. Whenever @daftspunk gets around to getting the latest version in October and updates the assets your change is going to be overwritten unless it's in the LESS file too.

**Comment by Lavrushin** [comment]
> @Lavrushin keep the change in the LESS file too please. Whenever @daftspunk gets around to getting the latest version in October and updates the assets your change is going to be overwritten unless it's in the LESS file too.

Done

**Pull request merged**
