### PR TITLE
RecordFinder - add a remove button

### PR DESCRIPTION
**Pull request by ChVuagniaux**
I suggest for solving the following issue https://github.com/octobercms/october/issues/1669 to add a simple button that clear the input and reload the partial.

mise a jour d un e events _ octobercms - google chrome 2017-03-15 12 34 50

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
+1

**Comment by LukeTowers** [comment]
Thanks, I'll try to review this this week.

**Comment by Kunilt** [comment]
Maybe this update is related to this error?

```
Uncaught TypeError: Cannot read property 'dataLocker' of null
    at Object.success (recordfinder.js:72)
```

**Comment by LukeTowers** [comment]
@Kunilt Have you refreshed your browser's cache?

**Comment by Kunilt** [comment]
@LukeTowers Yes, of course. Tried replicate bug in oc-test-plugin. Getting the same error.

**Comment by daftspunk** [comment]
Hi @Kunilt , try performing a force update on your installation. It would appear some of your files are corrupt maybe? If the problem still continues, please create a new issue and feel free to reference this one.

**Comment by daftspunk** [comment]
Issue mentioned by @Kunilt should be fixed in Build 411+ (328a74c1ff66ecf38fa5575d9051980b795d1d66)

**Comment by Kunilt** [comment]
Ok, error gone, but recordfinder not working as expected... data-locker input change is not triggered, only value is changed. So, if we have field in form which dependsOn our recordfinder, fields are not refreshing. 

Tried manually change value of data-locker input, and everything worked as expected (fields was refreshed).

**Comment by daftspunk** [comment]
This should be sorted in #2798 - Build 412+

**Pull request merged**
