### PR TITLE
Use 12 column layout in dashboard instead of 10 column layout

### PR DESCRIPTION
**Pull request by ayumihamsaki**
I have updated the grid system from 10 spaces to 12 spaces. I have also updated the jquery.isotope library from v1.5.26 to v3.0.6 in doing so it has fixed many bugs! This PR is related to github issue: https://github.com/octobercms/october/issues/3823

### CODE REVIEW

**Comment by LukeTowers** [comment]
@ayumihamsaki I would prefer this was simply made available as an option, given that the existing sites all use 10 columns, I don't want to be suddenly breaking dashboard layouts.

**Comment by ayumihamsaki** [comment]
@LukeTowers Do you want this as a plugin? And just update the library as there are errors when you resize the screen with the jquery.isotope library v1.5.26 so that would need to be updated for everyone anyway.

**Comment by LukeTowers** [comment]
@ayumihamsaki no it could be a backend preference setting item perhaps? Or a file config item? The updated library should definitely be in core though.

**Comment by LukeTowers** [comment]
No, keep the library update in this PR. And we'll wait for @daftspunk's input on what's the best way to make this configurable before moving forwards on that front.

**Comment by ayumihamsaki** [comment]
Ok, thanks. 

For future reference, the updated library sorts out some issues on the responsive layout of the grids when you resize the screen resolution on the dashboard page.

**Comment by ayumihamsaki** [comment]
This PR has been closed and will be broken up into different separate PR's.

Update Dashboard Columns from 10 to 12, see here: https://github.com/octobercms/october/pull/3965

Update jquery.isotope library from v1.5.26 to v3.0.6, see here: x

**Pull request closed without merging**
