### PR TITLE
Make http_only cookies configurable

### PR DESCRIPTION
**Pull request by ayumi-cloud**
Re-upping this pull request. The reason: Github blocked my account, because free accounts can only be logged in by the same person and not be multiple people. Basically they wanted me to pay for an account.

Anyway, tagging the same people again who looked at the old pr.

@LukeTowers @bennothommo @daftspunk

### CODE REVIEW

**Comment by LukeTowers** [comment]
@ayumi-cloud there's too many changes here, fix it so it's only the config value please. Also, where is the value actually getting looked at in the code?

**Comment by ayumi-cloud** [comment]
@LukeTowers Most of those things @daftspunk did, I just copied the lost pr over here with all his added commits - so not to lose the work. Can you speak to him, not sure what's going on with this pr now.

**Comment by Samuell1** [comment]
@ayumi-cloud He reverted his pr because it was breaking OCMS. https://github.com/octobercms/october/commit/8da798a5cd2f5f640719550eebebc03e9a9d29d1

**Comment by ayumi-cloud** [comment]
@Samuell1 cool, thanks for the heads up!

**Comment by ayumi-cloud** [comment]
@bennothommo sorry! need to ask you again where is the middleware for the http_only located.

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo @Samuell1 friendly bump, if anyone knows the location of the HttpOnly Middleware, been searching for it for a few hours and can't find the location. I plan to add a wrapper to it , connected to the config setting.

**Comment by LukeTowers** [comment]
@ayumi-cloud I'm not sure what you're asking, I don't know of an HttpOnly middleware. What is it supposed to do?

**Comment by Samuell1** [comment]
I think he is reffering to defaut laravel config https://github.com/laravel/laravel/blob/5.5/config/session.php#L180

**Comment by bennothommo** [comment]
@ayumi-cloud @LukeTowers @Samuell1 There's no HttpOnly middleware - the only piece of code that uses the `http_only` configuration variable is the `Illuminate\Session\Middleware\StartSession` middleware.

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo @Samuell1

Thanks! To link that middleware is found here: https://github.com/illuminate/session/blob/a95be1a3bf2cc26256b094c637813331dae56cd4/Middleware/StartSession.php#L157

This pr is actually finished and below are the test results:

image

and

image

(I just wanted to make sure there wasn't anything else that I might of missed out, but everything seems to be working correctly).

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo if you both happy with this pr, could it be added to the v462 milestone?

**Pull request merged**
