### PR TITLE
Add HTML5 and WAI-ARIA to the breadcrumbs in the layout file

### PR DESCRIPTION
**Pull request by ayumihamsaki**
Two minor fixes that were causing me conflicts in October, so created a separate pr to fix them.

### CODE REVIEW

**Comment by w20k** [comment]
@ayumihamsaki you're removing aria-tabs code?

**Comment by ayumihamsaki** [comment]
@w20k as per our conversaion it's been deleted in that sharing file and has it's own file now found here: https://github.com/octobercms/october/blob/6fa1b09b91d38bea75a263ba7f5a690d7ba19083/modules/system/assets/ui/js/waiaria.js

p.s. Merge this pr at the same time when merging this pr: https://github.com/octobercms/october/pull/4501

**Comment by ayumihamsaki** [comment]
@w20k editted this pr for just the one thing to update.

**Comment by ayumihamsaki** [comment]
Closing this as I have merge this small bit of code into this PR to make life easier, https://github.com/octobercms/october/pull/4516

**Pull request closed without merging**
