### PR TITLE
Update client.php

### PR DESCRIPTION
**Pull request by HekmatFavid**
Some changes need to hijri calendar month and date names correction in fa language

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by HekmatFavid** [comment]
ok, thank you.

**Comment by LukeTowers** [comment]
There is a problem with your quote placements, they are broken completely because they are in the wrong place. Please fix

**Comment by LukeTowers** [comment]
All of your array element commas are quoted while the string values that are supposed to be there are not.

**Comment by HekmatFavid** [comment]
Problems fixed.

**Comment by LukeTowers** [comment]
Awesome thanks!

**Pull request merged**
