### PR TITLE
Ability to use a select dropdown for the repeater collapsed title

### PR DESCRIPTION
**Pull request by MattPurland**
I'm currently using this basic hack and I find it very useful, as may others. It allows you to use the selected option from a dropdown as the repeater items title, as well as the normal text input.

### CODE REVIEW

**Comment by w20k** [comment]
@MattPurland if you're still interested in the PR. Could you sync it with the dev branch, and feel like you'd have to change your code a little bit.

Minor notes:
1.  Don't use .eq(0)
2. Don't use children, `find()` should do the trick for `select`.

**Comment by DanHarrin** [comment]
Want this taken into a new PR @w20k?

**Comment by w20k** [comment]
Sure, @DanHarrin - go for it ;)

**Comment by DanHarrin** [comment]
@w20k your changes have been made in #4544 😄

**Comment by w20k** [comment]
@DanHarrin thanks! 😉 
Closing in favor of #4544

**Pull request closed without merging**
