### PR TITLE
Add color button to richeditor

### PR DESCRIPTION
**Pull request by gpasztor87**

### CODE REVIEW

**Comment by LukeTowers** [comment]
Please explain the need for this PR. Unexplained PRs will not be merged.

**Comment by gpasztor87** [comment]
I think it's useful if we can change the color of the text. This plugin is already in the widget.

**Comment by LukeTowers** [comment]
@gpasztor87 You already can by specifying the `toolbarButtons` value on the `richeditor` field: http://octobercms.com/docs/backend/forms#widget-richeditor

**Comment by daftspunk** [comment]
I'd prefer to add color by using CSS and the definitions Editor Settings. Gives more control that way, say, if you wanted to use a different shade of red in future versions of the site.

**Pull request closed without merging**
