### PR TITLE
Update Filter.php

### PR DESCRIPTION
**Pull request by joseph-d**
There is an addScopes function for extensibility but no way to remove scopes which are already there.

### CODE REVIEW

**Comment by daftspunk** [comment]
This could be problematic, we need to decide if it is better to "hide" scopes instead of destroying them. Can you give your use case for needing this? It will help with making a decision.

**Comment by joseph-d** [comment]
I have been extending the Rainlab Blogs plugin. As part of what I'm doing, I wanted to remove (or hide) the categories feature as it is not required.

I was able to do the following:

        Event::listen('backend.menu.extendItems', function($manager) {
           $manager->removeSideMenuItem('RainLab.Blog', 'blog','categories');
        });

        PostsController::extendListColumns(function($list) {
            $list->removeColumn('categories');
        });

        PostsController::extendFormFields(function($form) {
            $form->removeField('categories');
        });

The only thing remaining is the category filter in on the posts list view which there doesn't appear to be a method for.

To be honest, hiding the scope would be just as good as destroying the scope in this particular case, just as hiding the above column, field and side menu item would be acceptable too.

**Comment by daftspunk** [comment]
You cited precedence (Lists / Form widget have removeX methods), that's all I need to see. This will be accepted.

**Comment by LukeTowers** [comment]
@daftspunk The requested changes have been made, could you merge this?

**Comment by LukeTowers** [comment]
@daftspunk The requested changes have been made, could you merge this?

**Comment by daftspunk** [comment]
Strange, I wasn't notified about the base branch change. Thanks for picking it up @LukeTowers!

**Pull request merged**
