### PR TITLE
add meta_keywords

### PR DESCRIPTION
**Pull request by kideny**
add meta_keywords for seo

### CODE REVIEW

**Comment by LukeTowers** [comment]
Just something to consider with this:

At best Google & Bing completely ignore the meta keywords tag, at worst they penalize you for including it.

http://searchengineland.com/the-meta-keywords-tag-lives-at-bing-why-only-spammers-should-use-it-96874
https://chrisedwards.me/seo/keyword-meta-tag-google/
http://www.hobo-web.co.uk/definitive-guide-to-using-important-meta-tags/#meta-keywords-seo-best-practice

**Comment by kideny** [comment]
@LukeTowers meta_keywords tag have usefully for some seo tools ,  we should support meta_keywords setting  for some user and they can empty it .

**Comment by kideny** [comment]
meta_keywords have usefully for some other country's search engine .  octoberCMS is a  international cms . we should let user choice  itself .

**Comment by LukeTowers** [comment]
I don't disagree with you, just thought I should bring those articles up.

Honestly, in my opinion meta tags shouldn't have been part of the core in the first place; they're more within the realm of plugins.

**Comment by daftspunk** [comment]
We intentionally didn't include `keywords` because it has become redundant in many schools of thought, including our own. This could easily be injected by a plugin so we won't need to merge this.

**Pull request closed without merging**
