### PR TITLE
Allow for CMS Page translation.

### PR DESCRIPTION
**Pull request by mplodowski**
See https://github.com/rainlab/translate-plugin/pull/367

### CODE REVIEW

**Comment by LukeTowers** [comment]
@mplodowski why can't this property be dynamically added?

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred and we are trying to figure out what issues are still relevant. If this is still something that you would like to see through to fruition please respond and we can get the ball rolling.

**Comment by mjauvin** [comment]
@LukeTowers to be frank, I am not sure as @mplodowski only submitted a patch but did not give much more details. I tried his patch just now and it's breaking my branch...

**Comment by LukeTowers** [comment]
@mjauvin is this PR necessary for your PR to the translate plugin to work?

**Comment by mjauvin** [comment]
@LukeTowers It's not, but @mplodowski was trying to make my work extendable (which I have not been able to do)

**Pull request closed without merging**
