### PR TITLE
Add an unique identifier to all the filter container popup boxes

### PR DESCRIPTION
**Pull request by ayumi-cloud**
See github issue: https://github.com/octobercms/october/issues/4845

Best to show screenshots, so you can understand.

### Before

image

Fixed width no way to adjust each different filter pop-up container box to different widths. Because October's ID tag is the same for every filter box!

### After

image

Now can adjust each filter pop-up container boxes to different widths. Because now we got a true unique identifier on every filter box!

### CODE REVIEW

**Comment by w20k** [comment]
Simple - looks good to me.

**Comment by bennothommo** [comment]
@ayumi-cloud I reckon it might be better seeing if the ID of the filter `<div>` could be made unique as opposed to adding an ID to the encompassing `<form>` tag.

**Comment by ayumi-cloud** [comment]
@bennothommo 1st happy new year 👍 

Actually I did think of that at the time, the reason I choose the `<form>` tag and not the `<div>` tag was because there is already an id tag there, which is linked to the javascript code. Instead of changing a big amount of javascript, I was lazy and added the id tag to the parent container element.

If it's a major issue, I guess I will have to re-write the javascript code and all the files that use that id tag.

**Comment by bennothommo** [comment]
@ayumi-cloud Happy new year to you too.

I personally think it's the better fix - even if it means more work - as duplicate IDs in general are invalid HTML.

**Comment by ayumi-cloud** [comment]
@bennothommo I don't think it would be a duplicate id as they are on different code lines, the only issue I've ever seen is adding an id-tag to a HTML5 element, some old browsers don't recognise it, I think IE11 maybe in that list?

Guess have to do the longer route 🥇

**Comment by LukeTowers** [comment]
@ayumi-cloud personally I don't mind the current approach, what're your concerns @bennothommo?

**Comment by bennothommo** [comment]
@LukeTowers I'm certain that duplicate IDs are invalid HTML, even with HTML5. While it's not an issue when people use different types of filters for a single List widget, it presents when someone uses 2 of the *same* type of filter. The browsers work around it just fine, but it still is "cleaner" to have them use unique identifiers.

I personally don't think it's too big a change to make the IDs unique and change the selectors used in the JS files to point to the new IDs (or change them over to using the class `control-filter-popover`.

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo 

Before I continue with this pr, there is no duplicate IDs going on here! The javascript is loading the HTML into the dom not the source code! Also the javascript html code snippet is being loaded only once per filter. You can't open two filter boxes at the same time as the first one auto closes. **There is no duplicate ID issue here.** I can prove it with some screenshots if needed.

See here as proof:

image

**Comment by LukeTowers** [comment]
@bennothommo @ayumi-cloud is correct, there is no issue of duplicate IDs. The popup window itself is only present in the DOM when visible, and the div has `controlFilterPopoverDate` whereas the form would have `controlFilterPopoverDate-{{ scopeName }}`

**Comment by LukeTowers** [comment]
My main argument against changing it to just the form is all of the JS changes required to make that happen

**Comment by ayumi-cloud** [comment]
@LukeTowers @bennothommo going to revert my commit and not change the javascript code. I worry there is a tiny chance it may cause a breaking to some users. I rather keep it in the `<form>` tag.

**Comment by bennothommo** [comment]
@LukeTowers @ayumi-cloud Alright then - proceed as is.

**Comment by ayumi-cloud** [comment]
I think this pr is ready for testing now, if anyone wants to add a testing label to it.

**Pull request merged**
