### PR TITLE
Fix Rich Editor to fill the full height of the container textarea

### PR DESCRIPTION
**Pull request by ayumihamsaki**
Fixes this Github issue here: https://github.com/octobercms/october/issues/4484

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Finished.

**Comment by bennothommo** [comment]
@ayumihamsaki Would you mind rebasing your branch from develop? It seems your remote branch has picked up some of @LukeTowers changes to the master branch.

**Comment by ayumihamsaki** [comment]
No problem I was wondering about those extra files - will get on it now and sort out all those pr's.

**Comment by w20k** [comment]
@ayumihamsaki I hope you've not just removed the file from the PR, otherwise when we squash merge, changes will be removed from the Dev branch. Better to rebase your branch from Dev or merge Dev into your branch as @bennothommo said.

**Comment by ayumihamsaki** [comment]
done

**Comment by w20k** [comment]
Cool fixed, and tested!

### **Screenshots**
**Before:**
Screenshot 2019-07-29 at 20 30 45
Screenshot 2019-07-29 at 20 32 52

**After:**
Screenshot 2019-07-29 at 20 30 53
Screenshot 2019-07-29 at 20 33 04

**Comment by w20k** [comment]
@bennothommo anything to add or comment?

**Comment by bennothommo** [comment]
@w20k Nope, looks all good to me.

**Comment by ayumihamsaki** [comment]
p.s. This fails my extended testing. If you make the rich editor area big enough that it requires to use a y-axis scrollbar. The y-axis scrollbar will not display correctly and also fails when you down-scale the screen size and make the above control panel bigger!

To fix this I have converted the Rich editor from using display table row into using flexbox.

The CSS fix is as follows:

```css
.field-richeditor.stretch .fr-box:not(.fr-fullscreen) {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column;
}
```

Please leave this PR as it is, I will be adding this fix to the following PR: https://github.com/octobercms/october/pull/4509

Because this fix is also part of a Rich editor + plus `Stretch` feature.

I have left this comment just as a future ref note.

**Comment by ayumihamsaki** [comment]
p.s. This fails my extended testing. If you make the rich editor area big enough that it requires to use a y-axis scrollbar. The y-axis scrollbar will not display correctly and also fails when you down-scale the screen size and make the above control panel bigger!

To fix this I have converted the Rich editor from using `display:table-row` into using `flexbox`.

The CSS fix is as follows:

```css
.field-richeditor.stretch .fr-box:not(.fr-fullscreen) {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
        -ms-flex-direction: column;
            flex-direction: column;
}
```

Please leave this PR as it is, I will be adding this fix to the following PR: https://github.com/octobercms/october/pull/4509

Because this fix is also part of a Rich editor + plus `Stretch` feature.

image


I have left this comment just as a future ref note.

**Pull request merged**
