### PR TITLE
asset cache fix

### PR DESCRIPTION
**Pull request by christianWilling**
Hi,
this changes will make it possible to use a `HashableInterface` for the cache generation.

So you can make a hash with the modification dates from the included files.

And than changes in the included files will be displayed without saving the parent asset.

### CODE REVIEW

**Comment by daftspunk** [comment]
It's very hard to see what you've done here because the indentation has been changed to 5 spaces, it should be 4 spaces.

**Comment by daftspunk** [comment]
Old code:
```
        $cachedCollection = new AssetCache($collection, $cache);
```

New code:

```
        $cachedFiles = [];
        foreach ($files as $file) {
            $cachedFiles[] = new AssetCache($file, $cache);
        }

        $cachedCollection = new AssetCollection($cachedFiles, [], $filesSalt);
        $cachedCollection->setTargetPath($this->getTargetPath($rewritePath));
```

**Comment by daftspunk** [comment]
Please provide more detail on why we need to include this change, with supporting code examples.

**Comment by christianWilling** [comment]
hi

sry for changing the indentation.


The Problem is when I have an less or scss file with an include of an other file less or scss file and i only change the included scss the changes are not displayed. And if i add this to my filter

```
public function hash()
    {
        $themePath = themes_path(Theme::getActiveTheme()->getDirName());
        $factory = new AssetFactory($themePath);

        $allFiles = [];

        foreach ($this->files as $file) {
            $children = $this->getChildren($factory, file_get_contents($themePath.'/'.$file), $themePath.'/'.dirname($file));
            foreach ($children as $child) {
                $allFiles = array_merge($allFiles, $child->all());
            }
        }

        $modifieds = [];

        foreach ($allFiles as $file) {
            $modifieds[] = $file->getLastModified();
        }

        return md5(implode('|', $modifieds));
    }```

this will make an cache key from all children's modified date so when I change an included scss file the system will generate the file new and my changes will be displayed.

**Comment by daftspunk** [comment]
Can you paste the entire contents of your filter.

**Comment by christianWilling** [comment]
sure,

the filter

```php
/**
 * a custom scss Filter with hash function for children
 */
class ScssFilter extends ScssphpFilter implements HashableInterface
{
    //the files to check children in the hash function
    protected $files = [];

    public function __construct(&$files)
    {
        //set the files wich are changed by an event
        $this->files = &$files;
    }

    public function hash()
    {
        $themePath = themes_path(Theme::getActiveTheme()->getDirName());
        $factory = new AssetFactory($themePath);

        $allFiles = [];

        foreach ($this->files as $file) {
            $children = $this->getChildren($factory, file_get_contents($themePath.'/'.$file), $themePath.'/'.dirname($file));
            foreach ($children as $child) {
                $allFiles = array_merge($allFiles, $child->all());
            }
        }

        $modifieds = [];

        foreach ($allFiles as $file) {
            $modifieds[] = $file->getLastModified();
        }

        return md5(implode('|', $modifieds));
    }
}
```

And the loading 

```php
/**
     * set the filter to compile scss files
     */
    public function boot()
    {
        //the files wich children are included in the hash function of the filter
        $files = [];

        \System\Classes\CombineAssets::registerCallback(function($combiner) use (&$files){
            if ($combiner->useMinify) {
                $combiner->registerFilter('scss', new \October\Rain\Support\Filters\StylesheetMinify);
            }
            //init the filter class with the reverrence to the hash files
            $filter = new \Willing\Scss\Classes\ScssFilter($files);

            //set the output formate
            $filter->setFormatter('Leafo\ScssPhp\Formatter\Expanded');

            //set some helpfull variables
            $filter->setVariables([
                'theme-folder' => '"'.url('/themes/'.Theme::getActiveTheme()->getDirName()).'/"',
            ]);

            //set the filter
            $combiner->registerFilter('scss', $filter);
        });

        //get current files for the hash function and give them to it by reverrence
        Event::listen('cms.combiner.beforePrepare', function($combiner, $assets) use (&$files) {
            $files = $assets;
        });
    }
```

example asset1
```sass
@import asset2.scss";
```

example asset2
```sass
body{
    background: red;
}
```

and my layout

```php
<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ this.page.title }}</title>
        <link href="{{ ['assets/bootstrap.scss']|theme }}" rel="stylesheet">
    </head>
    <body>
        <h1>Hello, world!</h1>
    </body>
</html>
```


so the problem to fix is when i only change the asset2 conent.


i hope this will help to understand the problem:)

**Comment by daftspunk** [comment]
Wow, we need this functionality in the core. Would you mind contributing:

1. Your SCSS filter
1. Modifying our LESS filter to support it

Filters are located here: https://github.com/octobercms/library/tree/master/src/Parse/Assetic

**Comment by christianWilling** [comment]
of course i'll add this things this afternoon or at the weekend if i don't have enough time.

**Comment by christianWilling** [comment]
how did you fix the problem with relative paths to images in less files ? 

https://github.com/christianWilling/Scss/issues/5

**Comment by christianWilling** [comment]
so of course ther is now an error in the test.

becourse of the missing changes in the library https://github.com/octobercms/library/pull/220

**Comment by daslicht** [comment]
awesome !

**Comment by christianWilling** [comment]
I added new PR to the right branch

**Pull request closed without merging**
