### PR TITLE
Make partial parameters accessable in the PHP section of the partial template #1235

### PR DESCRIPTION
**Pull request by Kilgaloon**
Enabled parameters passed to partial to be used in Code segment of partial

### CODE REVIEW

**Comment by daftspunk** [comment]
This looks good, can you provide an example of how it is used.

**Comment by Kilgaloon** [comment]
When you include partial in template like this ``{% partial "some" testParam=testValue %}`` you can get parameter inside code block of partial like this ``$this->getParam('testParam')`` or you can get all parameters with  ``$this->getParams()``. Also will change code like said.

**Comment by daftspunk** [comment]
Thanks, this relates to #1235. The method `$this->param()` will access the URL parameters currently, so this method would create some confusion. 

We'll need to find a more suitable way. I would expect that the values are available simply with `$this`. (`$this->controller->vars`) or some other approach.

**Comment by Kilgaloon** [comment]
Will look at this in next few days.

**Comment by Kilgaloon** [comment]
@daftspunk Instead of adding parameter that is passed to `$this->vars["this"]["param"]`` i think its good idea to add them ``$this->vars["this"]["partial"]["param"]``. And get them like previously set in pull request. I wanted to make parameters passed to partial available in ``$this`` scope, but better is to separete partial from anything else and make section partial inside ``$this->vars["this"]`` so other things can be set for partial and that can be accessed.

**Comment by daftspunk** [comment]
@Kilgaloon, it turns out the variables are available. It's possible this was implemented recently through general maintenance but #1235 was never closed. Am I missing something here?

#### Partial contents

```
==
function onStart()
{
    traceLog($this->foo);
}
==
{{ foo }}
```

#### Calling the partial

```
{% partial 'mypartial' foo='bar' %}
```

**Comment by daftspunk** [comment]
This was fixed in Feb as part of ec03b7b2f85cbe89082eda9fe7e457534bdc522d

**Pull request closed without merging**
