### PR TITLE
Update Modernizr V3.6.0 to V3.7.1

### PR DESCRIPTION
**Pull request by ayumihamasaki2**
Note: There is no official build on the website yet, so I downloaded the files and did a manual automatic build myself. Please test for any errors (**there should not be any errors with this now**).

Github Issue: #3867

---

Their website doesn't say it's stuck on [V3.5.0](https://modernizr.com/news) but I will try and give a brief overview of the updates:

- There 14 commits since 3.6.0
- Google Chrome V70+ have changed the touch event detection https://bugs.chromium.org/p/chromium/issues/detail?id=36415
- Many bug fixes in the code (basic errors) that have been fixed
- Updated and bug fixed several components October uses
- Added new API's
- Updated their package list dependencies for their Core code
- Google Chrome V73+ have changed their pointer events also (last week I had to fix one of my github repo's with regards to this as well) - Can see here for more details: https://developers.google.com/web/updates/2019/02/scrolling-intervention

p.s. Not really happy to merge with this PR right now. I would be happy to leave it open and when they update their website I can update this PR with their code (just to make sure I haven't created any mistakes by manually building it myself).

But in the mean time please decide whether this is a good one to update or not? ~If it is then I will update this PR and tag you when they update their website builder.

---

Just going through and creating the custom json file to do an automatic build process, I would like to add the following extra things:

```json
    "css/flexwrap", <-- Part of the flexbox attributes
    "css/fontdisplay", <-- This is a new standard for loading fonts (I want to add this to October in a different pr)
    "img/sizes", <-- This is very common and should be included
    "img/srcset", <-- This is very common and should be included
    "img/webp", <-- Webp is the most common image standard and should be included
    "img/webp-alpha", <-- Webp is the most common image standard and should be included
    "img/webp-animation", <-- Webp is the most common image standard and should be included
    "img/webp-lossless", <-- Webp is the most common image standard and should be included
    "css/cssgrid", <-- We have Flexbox included, I think we should also include css grids
    "css/boxsizing", <-- We use this in the css backend in css files
    "css/calc", <-- We use this in the css backend in javascript files
```

The custom file I have created is here: https://github.com/ayumihamsaki/october-modernizr/blob/master/modernizr-config.json

Please can you go through it and double check things. If you are happy I will re-build the Modernizr commit.

Also I think it would be a good idea to create a folder and store it in the repo: https://github.com/octoberrain/meta/modernizr-config.md

Also a big ask. Is it possible to move that repo over here to have a url of:

https://github.com/octobercms/meta

Because it just took me 30 mins trying to find that repo! Be easier to have everything in one place.

---

This commit is ready for testing and to merge now! There should not be any errors with this.

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Maybe add the extra modules to allow `vh` and `vw` as per the connected other pr.

**Comment by ayumihamsaki** [comment]
This PR is ready, I don't plan on updating anymore commits on it.

**Comment by w20k** [comment]
Reviewed, looks good! Need to retest everything once again and could be merged.

**Comment by ayumihamsaki** [comment]
Thanks for testing!

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers I've found an issue with this PR while testing. Some of the modules are trying to inject the following:

csp

This is not harmful, but fails my tough CSP rules. There are many `data:audio` and `data:media` elements, I'm not exactly sure the reason for them, but there are quite a few! I will open an issue over there to find out the reason and see if I can remove this extra code.

**Comment by ayumihamsaki** [comment]
> As for your question: those data:audio and data:video elements are used in the `audio\autoplay`, `audio\preload` and `video\autoplay` tests. So if you want to get rid of them, just exclude those tests from your build.

Can I remove these modules from the build ? - Do we need them ?

**Comment by ayumihamsaki** [comment]
> As for your question: those data:audio and data:video elements are used in the `audio\autoplay`, `audio\preload` and `video\autoplay` tests. So if you want to get rid of them, just exclude those tests from your build.

Can I remove these modules from the build ? - Do we need them ?

p.s. `autoplay` is being removed by most browsers these days and is an annoying feature to users!

**Browsers policy**

- Chrome: [Autoplay Policy Changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)
- Safari: [Autoplay Policy Changes](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/)
- Firefox: [Autoplay Policy Changes](https://blog.mozilla.org/firefox/block-autoplay/)

Therefore due to the direction the browsers are going towards, poly-filling this feature seems pointless anyway.

**Comment by ayumihamsaki** [comment]
Had issue with github allows an update to this so had to create a new pr with the update commit that fixes the above issue it is found here: https://github.com/octobercms/october/pull/4352

**Pull request closed without merging**
