### PR TITLE
Follow up #2035 - Improve backend exception beautifier

### PR DESCRIPTION
**Pull request by gabsource**
- Fixed the names of the assets files and CSS classes
- Popup UI fixes (select2, checkbox to remember)
- Escaped HTML reserved characters with October builtin JS helper function

Improves #2035

Let me know if it still needs some improvements.

### CODE REVIEW

**Comment by daftspunk** [comment]
I am seeing some weirdness on my Windows machine.

screenshot 2016-05-25 05 56 35

I feel like perhaps we don't need to apply any beautification to the main exception message, since it is often easy to read. The beautifier makes it harder to read at the moment. I am unsure if this was your original intention because my Windows path seems to break it.

**Comment by daftspunk** [comment]
The stack trace is pretty heavy on the page. Let's hide it by default and use a button like the one found on the **CMS > Front-end theme** settings page:

screenshot-2016-05-25-06 00 08

The button should say "Show stack trace" then have it display all the stack trace lines.

**Comment by daftspunk** [comment]
More fun in Windows:

screenshot 2016-05-25 06 06 49

**Comment by gabsource** [comment]
Yes we can disable the beautifier for the message part. Using a `<pre>` like style to display line break should be sufficient. I'll add a button to hide the stacktrace as proposed.

May I ask you to attach a sample or two of raw text for exceptions found on Windows, to make sure the paths are parsed correctly in the stack trace ?

**Comment by daftspunk** [comment]
Sample 1:

```
exception 'October\Rain\Exception\SystemException' with message 'The partial '_page_links_form.htm' is not found.' in H:\Sites\TestEnv\modules\system\traits\ViewMaker.php:65
Stack trace:
#0 H:\Sites\TestEnv\modules\backend\formwidgets\RichEditor.php(107): Backend\Classes\WidgetBase->makePartial('page_links_form')
#1 [internal function]: Backend\FormWidgets\RichEditor->onLoadPageLinksForm('1')
#2 H:\Sites\TestEnv\modules\backend\classes\Controller.php(541): call_user_func_array(Array, Array)
#3 H:\Sites\TestEnv\modules\backend\classes\Controller.php(417): Backend\Classes\Controller->runAjaxHandler('onLoadPageLinks...')
#4 H:\Sites\TestEnv\modules\backend\classes\Controller.php(227): Backend\Classes\Controller->execAjaxHandlers()
#5 H:\Sites\TestEnv\modules\backend\classes\BackendController.php(94): Backend\Classes\Controller->run('update', Array)
#6 [internal function]: Backend\Classes\BackendController->run('october/test/po...')
#7 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#8 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#9 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), 'run')
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Backend\Classes\BackendController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#16 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Backend\\Classes...', 'run')
#17 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#32 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#35 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#38 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#41 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#48 H:\Sites\TestEnv\index.php(44): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#49 {main}
```

**Comment by daftspunk** [comment]
Sample 2:

```
exception 'Less_Exception_Compiler' with message 'variable @white is undefined in file H:/Sites/TestEnv/modules/system/assets/ui/less/toolbar.variables.less in toolbar.variables.less on line 9, column 46
07| @color-toolbar-editor-btn-color:         fade(@btn-secondary-color, 80%);
08| @color-toolbar-editor-btn-bg-hover:      #ddd;
09| @color-toolbar-editor-btn-bg-active:     mix(@white, #999, 60%);
10| @color-toolbar-editor-btn-color-hover:   #000;
11| ' in H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Variable.php:49
Stack trace:
#0 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Expression.php(52): Less_Tree_Variable->compile(Object(Less_Environment))
#1 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Call.php(45): Less_Tree_Expression->compile(Object(Less_Environment))
#2 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Expression.php(52): Less_Tree_Call->compile(Object(Less_Environment))
#3 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Value.php(27): Less_Tree_Expression->compile(Object(Less_Environment))
#4 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Rule.php(75): Less_Tree_Value->compile(Object(Less_Environment))
#5 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Tree\Ruleset.php(94): Less_Tree_Rule->compile(Object(Less_Environment))
#6 H:\Sites\TestEnv\vendor\oyejorge\less.php\lib\Less\Parser.php(198): Less_Tree_Ruleset->compile(Object(Less_Environment))
#7 H:\Sites\TestEnv\vendor\october\rain\src\Support\Filters\LessCompiler.php(25): Less_Parser->getCss()
#8 H:\Sites\TestEnv\vendor\kriswallsmith\assetic\src\Assetic\Filter\FilterCollection.php(62): October\Rain\Support\Filters\LessCompiler->filterLoad(Object(Assetic\Asset\FileAsset))
#9 H:\Sites\TestEnv\vendor\kriswallsmith\assetic\src\Assetic\Asset\BaseAsset.php(94): Assetic\Filter\FilterCollection->filterLoad(Object(Assetic\Asset\FileAsset))
#10 H:\Sites\TestEnv\vendor\kriswallsmith\assetic\src\Assetic\Asset\FileAsset.php(65): Assetic\Asset\BaseAsset->doLoad('// Basic grid s...', NULL)
#11 H:\Sites\TestEnv\vendor\kriswallsmith\assetic\src\Assetic\Asset\BaseAsset.php(103): Assetic\Asset\FileAsset->load()
#12 H:\Sites\TestEnv\vendor\kriswallsmith\assetic\src\Assetic\Asset\AssetCollection.php(151): Assetic\Asset\BaseAsset->dump(NULL)
#13 H:\Sites\TestEnv\modules\system\classes\CombineAssets.php(158): Assetic\Asset\AssetCollection->dump()
#14 H:\Sites\TestEnv\modules\system\console\OctoberUtil.php(121): System\Classes\CombineAssets->combineToFile(Array, 'H:\\Sites\\TestEnv...')
#15 H:\Sites\TestEnv\modules\system\console\OctoberUtil.php(96): System\Console\OctoberUtil->utilCompileAssets('less')
#16 H:\Sites\TestEnv\modules\system\console\OctoberUtil.php(60): System\Console\OctoberUtil->utilCompileLess()
#17 [internal function]: System\Console\OctoberUtil->fire()
#18 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#19 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Console\Command.php(150): Illuminate\Container\Container->call(Array)
#20 H:\Sites\TestEnv\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 H:\Sites\TestEnv\vendor\symfony\console\Application.php(841): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 H:\Sites\TestEnv\vendor\symfony\console\Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(System\Console\OctoberUtil), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 H:\Sites\TestEnv\vendor\symfony\console\Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 H:\Sites\TestEnv\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 H:\Sites\TestEnv\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 {main}
```

**Comment by gabsource** [comment]
Thanks !

Do you prefer 

#### 1. nothing at all : 
image
image

#### 2. nothing at all in `<pre>` style (horizontal scrolling)
image
image

#### 3. with some parsing fixed for windows path (newlines -> `<br>`, 2-spaces -> `&nbsp;&nbsp;`) : 
image
image

**Comment by daftspunk** [comment]
Visually 3 is preferred, however I think 1 will be more reliable because who knows what an exception error message may contain? Do you think 3 can be reliable enough? If so, lets go with 3.

**Comment by gabsource** [comment]
3 with a tab-control to keep the raw message available with only newlines replaced by `<br>` and 2-spaces replaced by `&nbsp;&nbsp;` for indention : 

image
_Show stacktrace button will be below the message_

image

**Comment by gabsource** [comment]
#### Initial state
image
#### Mouse hover
image
#### Deployed
image
#### Raw
image

**Pull request merged**
