### PR TITLE
Fix Sidebar and File Column bar in the code editor section

### PR DESCRIPTION
**Pull request by ayumihamsaki2**
See github Issue: #4005

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Don't know why still a conflict? But everything is in one commit and all tidy and easy to work with now.

**Comment by ayumihamsaki** [comment]
Testing this I have seen another issue, which I will merge into this pr, (You have to Drag the window open and closed quickly) see screenshot:

untitled

**Comment by LukeTowers** [comment]
@ayumihamsaki2 could you fix the conflicts?

**Comment by ayumihamsaki2** [comment]
@LukeTowers Sorry, I could not find the cause of why it's saying there is a conflict, I tried both your and w20k methods to try and resolve it, but to no avail ?

**Comment by w20k** [comment]
@ayumihamsaki2, you haven't used minified version? I guess, or with old minification. Might give a try to fix this as well.

**Comment by ayumihamsaki** [comment]
@w20k The un-minifed version with no changes passes ok. It's just when I try to add edits to it, doesn't want to pass? Hopefully you can find a solution to it.

**Comment by ayumihamsaki** [comment]
Luke's comment on another said to try this:

> to resolve the conflicts you need to use the latest dev branch of the library repo and run `october:util compile assets`

**Comment by ayumihamsaki** [comment]
@LukeTowers I will wait until next year for the reply, I have tried your method and did the following:

1. Run `php artisan october:util compile assets`

2. Says error and need to run `Composer install`

3. I do that and re-run the `php artisan october:util compile assets`

4. It works then, but generates 2121 changed files.

5. Removing most of the files and updating only the folder: `modules/backend/assets/*` I get 61 files changed.

Should I pull all those files or not?

**Comment by ayumihamsaki** [comment]
@LukeTowers I will wait until next year for the reply, I have tried your method and did the following:

1. Run `php artisan october:util compile assets`

2. Says error and need to run `Composer install`

3. I do that and re-run the `php artisan october:util compile assets`

4. It works then, but generates 2121 changed files.

5. Removing most of the files and updating only the folder: `modules/backend/assets/*` I get 61 files changed.

Should I push all those files or not? Or will it not create an error just to extract only the 5 files being changed in this pr.

Link for my notes: https://octobercms.com/docs/console/commands#october-util-command

**Comment by ayumihamsaki2** [comment]
I think I see the issue in october.css

```css
@media (max-width: 769px){#layout-side-panel{top:45px}
}
@media (min-width: 769px){#layout-side-panel{top:62px}
}
```

Before the 769px is a space, so maybe needs to be changed into:

```css
@media (max-width:769px){#layout-side-panel{top:45px}
}
@media (min-width:769px){#layout-side-panel{top:62px}
}
```

Github did that because the code on my computer doesn't have that space? Also github has unconnected me from this pr see top of screen: `octobercms:develop` from `unknown repository`

I'm sorry but I got no choice but to close this pr and open a new one with the corrected code.

**Pull request closed without merging**
