### PR TITLE
Bulgarian translation for october modules - backend, cms, system. VasilSlavchev@gmail.com

### PR DESCRIPTION
**Pull request by VasilSlavchev**

### CODE REVIEW

**Comment by VasilSlavchev** [comment]
Hey, how i can change the branch? Or i need to open a new pull request to develop?

**Comment by daftspunk** [comment]
It's alright, I should be able to merge it using the patch file.

**Comment by daftspunk** [comment]
Merged in 8c9340457692812f72594205179eb871515718b0

Thanks

**Comment by VasilSlavchev** [comment]
Nice. Thanks.

**Pull request closed without merging**
