### PR TITLE
Responsive scoreboard items

### PR DESCRIPTION
**Pull request by gergo85**

### CODE REVIEW

**Comment by daftspunk** [comment]
Can you please explain what you're doing here? Screenshots or sample code would be helpful.

**Comment by gergo85** [comment]
Before:
oc-before

After:
oc-after

**Comment by daftspunk** [comment]
These are already responsive, you can click and drag with the mouse or with your finger on a touch device.

**Comment by gergo85** [comment]
You are right. I didn't know about it.

**Pull request closed without merging**
