### PR TITLE
added tests for optional wildcard parameters

### PR DESCRIPTION
**Pull request by mariavilaro**
Tests for https://github.com/octobercms/library/pull/363

### CODE REVIEW

**Comment by w20k** [comment]
@mariavilaro could you clean up the Test?

As I've understood this part should be removed?
```
//this happens
$this->assertEquals(array_keys($parameters)[0], 'category_name?');
$this->assertEquals($parameters[array_keys($parameters)[0]], '*');
//this should happen`
``

**Comment by mariavilaro** [comment]
Oops, I didn't see your answer, I already did it

**Comment by w20k** [comment]
@mariavilaro don't revert))

**Comment by LukeTowers** [comment]
@w20k can you edit the travis.yaml to run tests with the develop branch of the library? Same for the library running tests with the develop branch of the modules?

**Comment by w20k** [comment]
Sure thing, @LukeTowers. Will do!

**Comment by w20k** [comment]
Will be pending for now, before I add new TravisCI routine.

**Pull request merged**
