### PR TITLE
Add crossorigin attribute to images being loaded from third-party locations

### PR DESCRIPTION
**Pull request by summercms**
Add crossorigin protection to images be loaded from third-party locations

See github issue: https://github.com/octobercms/october/issues/5435

### CODE REVIEW

**Comment by LukeTowers** [comment]
What does this attribute achieve?

**Comment by summercms** [comment]
@LukeTowers 

~~The connected issue wasn't sure if you want to put it in the `discussions` section or not by the way?~~

> What does this attribute achieve?

A picture can tell you a thousand words.

image

Above: The new api's turned on - without this pr.

image

Above: The new api's turned on - with this pr.

Note: These images are being loaded `crossorigin` from `gateway.october.com` to the cms backend.

**Comment by LukeTowers** [comment]
When is chrome enabling this API by default?

**Comment by summercms** [comment]
@LukeTowers 

> When is chrome enabling this API by default?

I just checked, the api spec has now been moved into the `html standard` spec (so that's a major move).

Chrome added it to stable version 83 - so it's been around for a while. It's now out of the flag in Canary.

```
Don't merge this pr for now.
```

Not sure if you want to close this pr or put a label on it like `Status: Blocked` ?

I feel this issue needs to be addressed in the future - but can be left alone right now.

**Comment by summercms** [comment]
My reason is because the browser is telling me that the `gateway.october.com` needs to add security headers - because it's cors policy is not giving the complete protection. That's something the admins need to address in the future and I prefer not to mess around with the `gateway.october.com` server for now.

**Pull request closed without merging**
