### PR TITLE
Fix the Keyboard Navigation for switch and record finder

### PR DESCRIPTION
**Pull request by ayumihamsaki**
This is for: https://github.com/octobercms/october/issues/4473

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
Not finished - need find solution for the record finder

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I can't finished this, as I'm using the files in my other pr.

The following needs to be done:

/modules/system/assets/ui/storm.css

```css
.field-recordfinder .btn {background:transparent;position:absolute;right:1px;top:1px;height:36px;color:#595959;text-shadow:none;padding-left:15px;padding-right:15px;-webkit-box-shadow:none;box-shadow:none}
```

/modules/system/assets/ui/less/form.less

```css
.field-recordfinder {
    ..
    }
    .btn {
        background: transparent;
        position: absolute;
        right: 1px;
        top: 1px;
        height: 36px;
        color: lighten(@color-form-field-recordfinder-btn, 15%);
        text-shadow: none;
        padding-left: 15px;
        padding-right: 15px;
        -webkit-box-shadow: none;
        box-shadow: none;
```

**Comment by ayumihamsaki** [comment]
Finished.

**Comment by ayumihamsaki** [comment]
Finished.

**Comment by w20k** [comment]
@Eoler could you test this PR, and comment if it fixes your issue?

**Comment by Eoler** [comment]
> could you test this PR, and comment if it fixes your issue?

Sure, just let me grab the life jacket before swimming in all those commits! 😝

**Comment by w20k** [comment]
Tell me about it))

**Comment by ayumihamsaki** [comment]
I don't like how github is made! Take these comment boxes, they are tiny and you have to go back and forth to check the code. If you could click on these comment boxes and make them fullscreen and split the page so you can see the output at the same time, it would make life so much easier!

But for now I will stand by the side line as the life guard 😄

**Comment by Eoler** [comment]
Hey, I'm still above the surface (barely). Pulled the proposed changes into my development branch:
https://github.com/Eoler/october/pull/1 and recompiled October assets. Testing in Chrome+Firefox on Win10:

1. tabbing into switch widget is ok visually, but it lost ability to toggle itself with keyboard (Space)

2. record finder is still jumpy while tabbing into, especially if there's already selected value (twice):
OctoCMS-form-switch-recordfinder

**Comment by ayumihamsaki** [comment]
@Eoler 

1. 

>  but it lost ability to toggle itself with keyboard (Space)

Sorting that out right now, there is some junk code in October:

```css
input[type="radio"], input[type="checkbox"] {
    margin: 4px 0 0;
    margin-top: 1px \9;
    line-height: normal;
}
```

I'm going to guess the margin is all rubbish and remove both lines into this:

```css
input[type="radio"], input[type="checkbox"] {
    line-height: normal;
}
```

2. 

> record finder is still jumpy while tabbing

Do you have a test plugin I could use.

**Comment by Eoler** [comment]
> Do you have a test plugin I could use.

Yes, October test plugin has record finders in several places - People form controller for example:
https://github.com/octoberrain/test-plugin/tree/master/controllers

**Comment by ayumihamsaki** [comment]
A few things:

### Switch

1. I need to add the javascript code to update the `aria-checked` controls I will try to do that at the same time of updating the radio buttons pr, see here: https://github.com/octobercms/october/pull/4494

2. There is no focus ring setup on the switch, again I will add it in via javascript in the about mentioned pr.

### Record finder

3. I can't reproduce your error, I tested it on several plugins. Could you try doing a hard refresh on the browser. Also let me know if you change the standard record finder field in anyway. Just because I can't reproduce it doesn't mean I think there is not an error somewhere?

**Comment by ayumihamsaki** [comment]
I'm closing this pr - I have merged it into the radio keyboard navigation as they share almost the same code, please see here: https://github.com/octobercms/october/pull/4494

**Pull request closed without merging**
