### PR TITLE
Allow plugins to register their own mail partials

### PR DESCRIPTION
**Pull request by tobias-kuendig**
This PR adds support for plugins to register their own mail partials. This is done by adding a `registerMailPartials` method to the plugin base class. 

If it gets merged I will update the docs accordingly:
http://octobercms.com/docs/services/mail#mail-template-registration

### CODE REVIEW

**Comment by LukeTowers** [comment]
@tobias-kuendig could you submit the docs PR now? This will be accepted pending review

**Comment by tobias-kuendig** [comment]
Sure, see https://github.com/octobercms/docs/pull/325

**Comment by LukeTowers** [comment]
@tobias-kuendig was there a related issue?

**Comment by tobias-kuendig** [comment]
Not that I know of. I needed this feature for a plugin I am working on.

**Pull request merged**
