### PR TITLE
Update loader.less

### PR DESCRIPTION
**Pull request by Alex360hd**
This PR reference #3393 

Here is before / after screenshot.

loading-indicator-screen

### CODE REVIEW

**Comment by LukeTowers** [comment]
And the before after screenshot for where it's used in core?

**Comment by Alex360hd** [comment]
Here is screenshot when used with default backend list page (one generated by the builder plugin).

backend-loader-list

Another example when you click on "refresh" button on the event log backend setting page.

backend-loader-log

As my PR remove the background css rule of the backend loader, it will always be displayed with the background color of the parent element, which I suppose is a better behavior than inherit the body background color.

**Comment by LukeTowers** [comment]
Excellent, thanks!

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by Alex360hd** [comment]
Ok no problem, I didn't know sorry.

**Comment by LukeTowers** [comment]
@Alex360hd it turns out this wasn't the best solution as it's caused a bunch of other issues so it will be reverted: https://github.com/octobercms/october/pull/3840.

It looks like your case is custom, at least it's not a widget configuration / design combination that I recognize. In this case you should write your own CSS specifically targeting your specific implementation and only include it on the pages where it is needed.

Let me know if you have any questions!

**Comment by Alex360hd** [comment]
No problem to me, it's better to have an unwanted grey box (that you could configure in your plugin if it's really unwanted) than a buggy text overlay on most backend ajax buttons.

**Pull request merged**
