### PR TITLE
Install any required plugins with theme through "theme:install"

### PR DESCRIPTION
**Pull request by bennothommo**
This change will make the `theme:install` Artisan command also install any plugins that are required by the theme, shortcutting the bootstrapping or deploying of a site with a theme.

This works by determining if any plugins are required by the theme, and if so - and these plugins are missing from the current install, the command will run subsequent `plugin:install` commands to install the missing plugins.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@bennothommo can you look at https://github.com/octobercms/october/blob/develop/modules/system/controllers/Updates.php#L874-L905 and see if there's anyway we can consolidate these two locations into using the same code?

**Comment by bennothommo** [comment]
@LukeTowers it might be tricky - the Updates controller is using `UpdateManager` which is querying the October marketplace for most info, and checks dependencies *before* the theme is downloaded. Whereas, the console command downloads the theme and *then* checks dependencies.

I suppose an argument could be made to bring the command more inline with how the controller does it, but the controller is reliant on the AJAX framework, so we'd have to replicate the "steps" in the command.

**Comment by bennothommo** [comment]
We could potentially refactor the `UpdateManager` to handle a lot more of the functionality that has been added to the controller, and perhaps introduce some sort of `output` feed that can work with either the AJAX framework, or a CLI output, but such a task is a) a lot of effort and, b) would likely require approval from @daftspunk as this is very much veering into the realm of affecting the marketplace functionality.

**Comment by LukeTowers** [comment]
@bennothommo what aspects of the marketplace functionality would be affected by that suggestion?

**Comment by bennothommo** [comment]
@LukeTowers none per se, it wouldn't affect the marketplace directly - it's more that it's so tied to the marketplace API that I'd imagine he might reservations of the functionality being substantially changed.

**Comment by LukeTowers** [comment]
Would the functionality be changed or just the implementation of it?

**Comment by bennothommo** [comment]
It's more an implementation change, I'd say.

**Comment by LukeTowers** [comment]
I think it should be fine. I'd personally prefer that the logic was centralized in the UpdateManager class and the controller / console were just accessing the same core business logic to do their jobs.

**Comment by bennothommo** [comment]
Closing as we'll implement this differently.

**Pull request closed without merging**
