### PR TITLE
add oc.inputPreset.beforeUpdate plugin hook

### PR DESCRIPTION
**Pull request by mjauvin**
If locale data attributes are found, avoid applying source input changes to all target translations

fix for https://github.com/rainlab/translate-plugin/issues/429

Note: don't forget to recompile JS assets when applying this change

Credits to @munxar and @w20k for this fix!

### CODE REVIEW

**Comment by w20k** [comment]
@Rike-cz - mind if I ask you to test this PR. Should probably fix your issue with translate plugin :)

**Comment by mjauvin** [comment]
> @Rike-cz - mind if I ask you to test this PR. Should probably fix your issue with translate plugin :)

You will of course need to recompile your js assets with artisan...

**Comment by Rike-cz** [comment]
@w20k Works for me, thanks!

**Comment by w20k** [comment]
Cool, thanks @Rike-cz!

**Comment by mjauvin** [comment]
The only thing I noticed is that if the target element is currently selected in a different language than the source element language, its value will show the copied input from the source even though the language selector button still shows the other language. 

Still, the behavior underneath does what it's supposed to do.
The only way to not see this would be to trigger a language change in the target to match the one on the source, but I don't know how to do this or if this is really needed.

Opinions?

**Comment by alxy** [comment]
Do not forget to test this if the translate plugin is not installed.

**Comment by w20k** [comment]
@alxy It shouldn't be a problem here, you won't have more than two input fields, pretty much every time $src and $el will be present.
`sourceLocale && targetLocale` -> will be undefined 😄

**Comment by w20k** [comment]
@mjauvin this should do the trick - ✅. 
Currently you chagne value of a single field that corresponds to source locale. So, changing `text`(lang code) in button is the best solution here ;)

Example:
```javascript
var sourceLocale = $(this).siblings('.ml-btn[data-active-locale]').text()
var targetActiveLocale = $el.siblings('.ml-btn[data-active-locale]').text()
var targetLocale = $el.data('locale-value')
if (sourceLocale && targetLocale && sourceLocale !== targetLocale)
    return

if (targetLocale && targetActiveLocale && targetActiveLocale !== targetLocale)
    $el.siblings('.ml-btn[data-active-locale]').text(targetLocale)
```

**Comment by munxar** [comment]
@mjauvin thank a lot for the implementation. the only thing that bothers me is the fakt that we make the system dependant to the translate plugin. there are other places where this happens and I personally don't like it. This stuff should be in the translate plugin and the system must be extendable that the translate plugin can modify in a way that it works.
If we continue this route it will be unmaintainable in the future and against the mdularity of october cms.

On the other hand I see the need for this fix, because right now it breaks quite a lot of sites (especially the paes plugin site title to slug logic). Could slack together after this is mered to find a way in the future to move this kind of code into the translate plugin?
Again tnx for your work!

**Comment by w20k** [comment]
@munxar we could fix it in the Translate Plugin as well, but core code should be changed before that. 
This part, for sure:  `this.$src.on('input paste'....`. Should be a class, id or data specififc.

**Comment by mjauvin** [comment]
@munxar I wouldn't say "dependant" but it's definitely an exception FOR the translate plugin. Whether the translate plugin is installed or not does not break the code.

But, yes, making a change in core to allow plugins to change the behavior would be preferable.

**Comment by w20k** [comment]
People are ignoring me 😄 Will state it once again, the core was written so it shouldn't support multi-lang behavior by default or better to say multiple inputs.

**Comment by LukeTowers** [comment]
I would prefer if this could be implemented as the input.preset.js firing an event that could be hooked into by the translate plugin. Adding these specific exceptions directly to core negatively impact code readability and unnecessarily muddy the waters.

**Comment by mjauvin** [comment]
Ok, here's a new proposal which should please everyone, albeit potential implementation bugs:

```
        this.$src.on('input paste', function(event) {
            if (self.cancelled)
                return

            var timeout = event.type === 'paste' ? 100 : 0
            var updateValue = function(self, el, prefix) {
                if (self.cancelled)
                    return
                el  
                    .val(prefix + self.formatValue())
                    .trigger('oc.inputPreset.afterUpdate')
            }

            var src = $(this)
            setTimeout(function() {
                $el.trigger('oc.inputPreset.beforeUpdate', [self, src])
                setTimeout(updateValue, 100, self, $el, prefix)
            }, timeout)
        })
```

I am calling updateValue() with a 100ms delay to avoid racing problems with the 'oc.inputPreset.beforeUpdate' event handler

**Comment by mjauvin** [comment]
And we need to add this to Rainlab.Translate plugin multilingual.js:

```
    $('[data-input-preset]').on('oc.inputPreset.beforeUpdate', function(event, inputPreset, src) {
        var sourceLocale = src.siblings('.ml-btn[data-active-locale]').text()
        var targetLocale = $(this).data('locale-value')
        var targetActiveLocale = $(this).siblings('.ml-btn[data-active-locale]').text()
            
        if (sourceLocale && targetLocale && sourceLocale !== targetLocale)
            inputPreset.cancelled = true

        if (inputPreset.cancelled === false && targetLocale && targetActiveLocale && targetActiveLocale !== targetLocale)
            $(this).siblings('.ml-btn[data-active-locale]').text(targetLocale)
    })  
```

**Comment by mjauvin** [comment]
I tested this and it works very well, with or without the translate plugin active

**Comment by LukeTowers** [comment]
That looks good to me @mjauvin, submit the code for testing please

**Comment by mjauvin** [comment]
Accompanying Rainlab.Translate PR:

https://github.com/rainlab/translate-plugin/pull/458

**Comment by w20k** [comment]
@mjauvin Not it looks better! Thanks ;) Will re-test, hopefully, today! Thanks!

**Comment by Rike-cz** [comment]
I found a problem. When I write to field which is listened slowly, it works. When I write quickly, it falls to previous bad behavior.
ml-slug-bug

**Comment by w20k** [comment]
Hm... will test it today, might not be a prob at all 😄

**Comment by mjauvin** [comment]
confirmed @Rike-cz discovery, applied a fix to both related PRs to address this.

it's now working as expected for fast typers... ;)

**Comment by Rike-cz** [comment]
@mjauvin Woderful! For me it works with and without Rainlab.Translate plugin great!

**Comment by w20k** [comment]
@mjauvin doesn't work for me with the latest build... not sure, yet, why.

**Comment by mjauvin** [comment]
did you forget to rebuild your js assets? did you make sure your cleared
your cache to get the new multilingual.js file?

--
Marc

**Comment by w20k** [comment]
Nope, I didn't...Url field language switch doesn't change... will debug it a little bit.

**Comment by mjauvin** [comment]
I'm pretty sure it's a caching issue, that works really well now...

--
Marc

**Comment by w20k** [comment]
Do you use chrome devtools with `cache: false`?

**Comment by mjauvin** [comment]
I don't know, but I force a cache clear after each changes with
ctrl-shift-del

--
Marc

**Comment by w20k** [comment]
@mjauvin latest build, fresh install with everything - doesn't work, that's confirmed. Will look deeper, why, and let you know.

**Comment by w20k** [comment]
@LukeTowers this one should be good for merge.

**Comment by w20k** [comment]
@mjauvin could you re-build assets, or it's not needed for `input.preset.js`?

**Comment by mjauvin** [comment]
@w20k We need the built assets to be checked-in!? I thought the install process did this, no? If not, wouldn't it make sense it did?

**Comment by LukeTowers** [comment]
@mjauvin no, built assets need to be checked in. Please ping me once that's complete.

**Comment by mjauvin** [comment]
added compiled assets @LukeTowers

**Pull request merged**
