### PR TITLE
Correcting the class for correctly displaying the bootstrap grid in the tabs

### PR DESCRIPTION
**Pull request by ebashu-on-holidays**
```yaml
cssClass: row
fields:

# ......... Works very well

tabs:
    # This 'cssClass' is assigned to all tabs, but for the right
    # display - must be assigned for each tab separately
    cssClass: row
    fields:

        # ......... Indenting is not correct

        meta_title:
            tab: SEO
            label: Meta title
            span: storm
            cssClass: col-xs-6

        meta_keywords:
            tab: SEO
            label: Meta keywords
            span: storm
            cssClass: col-xs-6

        meta_description:
            tab: SEO
            label: Meta description
            span: storm
            cssClass: col-xs-12
```

opera- _2018-09-05_140933_bigbear

### CODE REVIEW

**Comment by ebashu-on-holidays** [comment]
Returned the value of `cssClass` as it was, since this option can be used in other plugins for other purposes. Added a new option `contentCssClass`, it applies the style to the contents of all tabs

**Comment by ebashu-on-holidays** [comment]
The last commit removes the problem with the width of the block in the sidebar

**Comment by LukeTowers** [comment]
Isn't this already implemented by `paneCssClass`?

**Comment by ebashu-on-holidays** [comment]
@LukeTowers, you suggest doing something like this?

```yaml
tabs:
    paneCssClass:
        0: row
        1: row
        2: row
        3: row
    fields:
```

Can it then be easier to add the ability to add to `paneCssClass` not only the array but also the string?

```yaml
tabs:
    paneCssClass: row
    fields:
```

**Comment by LukeTowers** [comment]
@ebashu-on-holidays you could easily adapt the getPaneCssClass method to just always return the same string if `paneCssClass` was defined as a string instead of an array.

**Comment by LukeTowers** [comment]
Just waiting on changes to be made to https://github.com/octobercms/docs/pull/320

**Comment by ebashu-on-holidays** [comment]
@LukeTowers , you forgot to merge branches

**Comment by LukeTowers** [comment]
@ebashu-on-holidays thanks

**Pull request merged**
