### PR TITLE
Make default format options configurable

### PR DESCRIPTION
**Pull request by alxy**
If the default format mode is selected, there is no chance to configure the format options for delimiter, enclosure, escape and encoding. This considers a new config file item `formatOptions` and falls back to `null` if it is not specified.

I will also provide a PR to the docs.

### CODE REVIEW

**Comment by alxy** [comment]
Documentation PR: https://github.com/octobercms/docs/pull/363

**Comment by LukeTowers** [comment]
Can you rename this to `defaultFormatOptions` @alxy?

**Comment by alxy** [comment]
Sure, however I prefer shorter configuration key names. It should be clear that in many cases this configuration is not needed (where the standard values just work) and can thus be completely omitted from the config file.
Can we hear a second opinion on the naming?

**Comment by LukeTowers** [comment]
Shorter is usually better yes, but in my opinion the `default` part of this is necessary. `formatOptions` implies that you are providing the available format options, and it's not like the extra 7 characters turn it into a novel 😉

**Comment by LukeTowers** [comment]
Feel free to ping @daftspunk on this if you really want a second opinion, although the likelihood of him responding is low.

**Comment by alxy** [comment]
Okay, anyhow, will add the default then...

**Comment by alxy** [comment]
@LukeTowers Done.

**Comment by LukeTowers** [comment]
Great! @w20k could you test this please?

**Comment by w20k** [comment]
@LukeTowers will try to deal with testing on this week. I'm a bit out of sync with testing PRs right now, trying to move on to my own company... takes time and effort :)

**Comment by w20k** [comment]
@LukeTowers tested - done! Works great!

**Pull request merged**
