### PR TITLE
Make relation form type's select portable

### PR DESCRIPTION
**Pull request by multiwebinc**
Proposed fix for https://github.com/octobercms/october/issues/4670. I made it a switch to make it extendable to other database drivers.

### CODE REVIEW

**Comment by bennothommo** [comment]
@multiwebinc Whilst this is good work, my main concern is that a regular expression match may not catch every permutation of a `concat()` query that people could do, and thus it would not cover all bases.

A possible different implementation of this would be instead providing a `selectConcat` property for the relation form widget, which could be provided by the developer as an array. We could then take the array and populate a controlled concatenation statement to the query based on the database type.

What are your thoughts on that?

**Comment by multiwebinc** [comment]
I think that's a great idea.

**Comment by multiwebinc** [comment]
I got started coding this and I'm wondering how would you want the yaml to be. There needs to be a way to distinguish between column names and strings.

If I have the following yaml:

        selectConcat:
            - year      # column
            - ', '      # string
            - make      # column
            - ' '       # string
            - model     # column

And in PHP, they're all just strings with no quotation marks around them, so when I do:

    return 'CONCAT(' . implode(', ', $values) . ')';

The result is

    "CONCAT(year, , , make,  , model)"

which is obviously wrong. The only way I can see to get the quotation marks in there is to use **double** quotation marks in yaml, which seems super ugly and error-prone to me:

        selectConcat:
            - year
            - "', '"
            - make
            - "' '"
            - model

Can anyone think of a better way?

**Comment by bennothommo** [comment]
@multiwebinc I'm fine with double-quoted strings, especially if they are intending to use different separators between fields. Otherwise, perhaps another option called "concatSeparator" which defines a single string to use between all fields in the "selectConcat" array.

**Comment by multiwebinc** [comment]
I think it might be better to just use the `select` property instead of introducing a new one. If it's an array, concatenate. If not, use it direct like it is now.

p.s. Sorry for the many commits here. I often manage to mangle things up on github.

**Comment by bennothommo** [comment]
@multiwebinc That's fine - we squash it when we merge anyway (with credit given to you, of course).

**Comment by LukeTowers** [comment]
Hmm, I'm almost wondering if we should extend the base grammar to allow for a separate `selectConcat` method that can be defined on each driver's grammar class instead. Then it's available everywhere.

**Comment by multiwebinc** [comment]
@LukeTowers I wouldn't know how to begin doing that, to be honest.

**Comment by LukeTowers** [comment]
Related https://github.com/laravel/framework/issues/5676

**Comment by LukeTowers** [comment]
@bennothommo what do you think about taking a stab at implementing it in the Builder / Grammar classes?

**Comment by bennothommo** [comment]
@LukeTowers sounds like fun. :)

**Comment by prhost** [comment]
I do not want to be boring but I do not see this code snippet as good, too many conditions to try to solve a situation that occurs infrequently, not all that use sqlite, that is, a little more processing for nothing.

I would come up with the idea of creating a new optional formWidget parameter, which does the similar functionality of the `select` parameter but uses Yaml tags to assemble the result. Symfony did something like this in its Yaml configs.

Example:
```
customSelect: "%year% %make% %model%"
```

**Comment by LukeTowers** [comment]
@prhost the whole point of the `select` property is to have the database do the concatenation so you can perform searches, filtering, and sorting operations on that concatenated result. Having YAML do it would move that into the application layer making those operations undoable.

**Comment by prhost** [comment]
> @prhost the whole point of the `select` property is to have the database do the concatenation so you can perform searches, filtering, and sorting operations on that concatenated result. Having YAML do it would move that into the application layer making those operations undoable.

Exactly, my idea is precisely not to mess with `select` but create another optional parameter to set the value, the right is pure sql in `select`, the developer must adapt to the format of your driver query.

In a few years, this `switch()` will be great trying to predict all that are divergences between drivers.

**Comment by LukeTowers** [comment]
@prhost the suggestion is to add to the grammar, so it's not a switch in the October application code, it's a grammar statement in the Laravel internals so that developers don't need to worry about what db structure they're targeting.

**Comment by multiwebinc** [comment]
@bennothommo Excellent work. I'm closing this PR.

**Comment by bennothommo** [comment]
@multiwebinc Are you sure this should be closed? While the `selectConcat` does provide the functionality you are looking for, it still needs to be linked to the YAML configuration value, I would think.

**Comment by multiwebinc** [comment]
@bennothommo Ok, I'll wait for https://github.com/octobercms/library/pull/434 to be merged first to make sure there aren't any major changes.

**Comment by LukeTowers** [comment]
@multiwebinc https://github.com/octobercms/library/pull/434 has been merged, are you still interested in getting this PR merged?

**Comment by multiwebinc** [comment]
@LukeTowers I still think it would be good to merge it after modifications to take advantage of https://github.com/octobercms/library/pull/434. If anyone could do that, that would be great.

**Comment by daftspunk** [comment]
Moved to #4670

**Pull request closed without merging**
