### PR TITLE
Attempt proposal of relation controller's events

### PR DESCRIPTION
**Pull request by Rike-cz**
Someone very clever said me "try it" :-) So I am trying to make proposal of relation controller's events handling as in form controller behavior they are.
If you will find this proposal useful, we can make it.

### CODE REVIEW

**Comment by bennothommo** [comment]
@Rike-cz given there's a fair few repeated callback calls, could you simplify it by creating a new method called `fireCallback()` that accepts the callback name and related arguments? Perhaps using this sort of method:

```php
protected function fireCallback(string $callback, ...$arguments)
{
    if ($this->controller->methodExists($callback)) {
        call_user_func_array([$this->controller, $callback], $arguments);
    }
}
```

Then you can simply use the following to fire a callback:

```php
$this->fireCallback('relationBeforeSave', $modelToSave, $this->relationName, $this->relationObject);
```

Thoughts?

**Comment by Rike-cz** [comment]
@bennothommo No problem, if this concept of events is in general good and acceptable feature for all maintainers.

**Comment by LukeTowers** [comment]
@Rike-cz shouldn't these events be implemented at the model level, not the controller level?

**Comment by Rike-cz** [comment]
@LukeTowers Absolutely, but as in form controller behavior, you can use both approaches.

**Comment by LukeTowers** [comment]
@Rike-cz I would prefer for them to exist as model events first, and then if we need to we can look at implementing them as relationcontroller methods

**Comment by bennothommo** [comment]
@Rike-cz are you still interested in finishing this? If so, you will need to implement this based on @LukeTowers [suggestion](https://github.com/octobercms/october/pull/4691#issuecomment-542302260).

**Comment by Rike-cz** [comment]
@bennothommo This PR is waiting for @LukeTowers deal with this [Bounty](https://www.bountysource.com/issues/79185728-add-other-model-s-relation-events).

**Comment by bennothommo** [comment]
@Rike-cz @LukeTowers what is the status with this PR? It appears to be for a bountied issue that @Rike-cz placed the bounty for, but Rike indicated that they're waiting on @LukeTowers for something...?

**Comment by LukeTowers** [comment]
I'm not sure what @Rike-cz is waiting on me for?

**Comment by Rike-cz** [comment]
> @Rike-cz shouldn't these events be implemented at the model level, not the controller level?

Trying to deal with it with @mjauvin #4561. When we finish that, this PR can be closed as redundant (but I think some events in RelationController can me handy).

**Comment by LukeTowers** [comment]
Closing in favour of https://github.com/octobercms/library/pull/537

**Pull request closed without merging**
