### PR TITLE
Add alias for jquery migrate (fixes #3917)

### LINKED ISSUE #3917: @jquery alias only includes jquery migrate
##### Expected behavior
Using `@jquery` in the combiner includes the jquery (backend) library that is used in the backend.

##### Actual behavior
Using `@jquery` in the combiner only includes the jquery migrate (backend) library that is used in the backend.

##### Reproduce steps
Put following script on front-end.

    <script src="{{ [
        '@jquery'
    ] | theme }}"></script>

##### October build
443 with composer on on dev-develop
    
    october/backend (dev-develop 2561a78)
    october/cms (dev-develop 125bee0)
    october/system (dev-develop e139e15)

My guess it has to with #3230 and #3886 , which adds a new version of jQuery and adds Migrate to the mix.

### PR DESCRIPTION
**Pull request by CptMeatball**
This fixes the double alias that was introduced when jquery was updated and migrate was added.

### CODE REVIEW

**Comment by ayumihamsaki** [comment]
@CptMeatball I help you out, Can you not delete the jquery and migrate files - they are needed for other files, just create an extra file with the merged. Then it will pass.

e.g.

```
modules/backend/assets/js/vendor/jquery.min.js
modules/backend/assets/js/vendor/jquery-migrate.min.js
modules/backend/assets/js/vendor/jquery-and-migrate.min.js

$this->registerAlias('jquery', '~/modules/backend/assets/js/vendor/jquery-and-migrate.min.js');
```

Sorry to be a pain, and thanks for sorting out my mess!

**Comment by LukeTowers** [comment]
@CptMeatball could you implement @ayumihamsaki's suggestion?

**Comment by w20k** [comment]
@ayumihamsaki Was also my bad, didn't thought about this kind of issue ;) Great there is devs who is using dev-branch!

**Comment by CptMeatball** [comment]
Honestly I haven't got any real issues with dev branch until now.

**Comment by LukeTowers** [comment]
@CptMeatball is this ready to go and working?

**Comment by CptMeatball** [comment]
I'd like for someone to reproduce the error and apply the fix. I'm getting mixed results for the backend and frontend. It looks like the backend works **without this PR**, while it only returns the migrate library on the front-end.

**Comment by w20k** [comment]
Backend doesn't use the allies :) If i'm not mistaken, but loading jquery and migrated directly, I'll test it tomorrow.

**Comment by CptMeatball** [comment]
@LukeTowers: I've tested this on 3 local projects, 1 staging and one with the Google Pagespeed Module turned on for caching. This causes some caching errors, but seems to work apart from that. Waiting on @w20k for confirmation.

**Comment by w20k** [comment]
For me with default configurations everything works fine. Haven't tested it with 'caching' enabled. Will try.

Backend (modules/backend/layouts/_head.htm):
screenshot 2018-11-16 at 11 04 42

Frontend with combined scripts:
```
<script src="{{ [
            '@jquery',
        ] | theme }}"></script>
```

screenshot 2018-11-16 at 11 06 59

**Comment by ayumihamsaki** [comment]
I get loads of caching issues with October CMS everyday, due to using a combination of Service Workers, CDN Caching, Server Side Caching, Preloading/Prefecth, 304 redirects and .HTaccess etc. So I am use to dealing with this issue everyday! With regards to caching issues, October doesn't clear or reset any cache and I hope my PR found here: https://github.com/octobercms/october/pull/3879 fixes some of the many caching issues in the backend.

I personally have never seen an issue with the jQuery library causing a caching issue like you are saying. I am not saying I dont believe you. I'm just thinking there maybe a separate issue with your setup causing a conflict issue - that's my gut feeling.

I think the way this PR has been setup should fix the alias issue - but not a caching issue.

But I will still follow this issue as I will be interested to hear any updates on any caching issue, as like I said everyday I have to deal with caching problems in October. p.s. It's worst in a Chrome browser for me and I already raised an Issue with the Google Chrome team on it and they said they have no plans to fix the caching issue in their Browser but did verify the issue when I showed them the proof.

**Comment by ayumihamsaki** [comment]
I get loads of caching issues with October CMS everyday, due to using a combination of Service Workers, CDN Caching, Server Side Caching, Preloading/Prefecth, 304 redirects and .HTaccess etc. So I am use to dealing with this issue everyday! With regards to caching issues, October doesn't clear or reset any cache and I hope my PR found here: https://github.com/octobercms/october/pull/3879 fixes some of the many caching issues in the backend.

I personally have never seen an issue with the jQuery library causing a caching issue like you are saying. I am not saying I dont believe you. I'm just thinking there maybe a separate issue with your setup causing a conflict issue - that's my gut feeling.

I think the way this PR has been setup should fix the alias issue - but not a caching issue.

But I will still follow this issue as I will be interested to hear any updates on any caching issue, as I already said, everyday I have to deal with caching problems in October. p.s. For me it's worse in a Chrome browser than Firefox for example and I have already raised an Issue with the Google Chrome team on it. They said in the end that they have no plans to fix the caching issue in their Browser, but did verify the issue when I showed them the proof. Their solution was to do the following: 

1. go to `about:flags`, 
2. search for "**enable network service**" (Without quotes),
3. disable the network service,
4. restart Chrome

Their solution did work for October and I did see an improvement with October caching issues, but this is was a kind of temp fix and adding the clear Cache headers to October is a much better long-term goal. The API is still in draft but Google and other major browsers are all already using it. So I really hope my PR goes through to update October for backend caching issues.

**Pull request merged**
