### PR TITLE
Fix error code

### PR DESCRIPTION
**Pull request by cx-emerge**
logical error

### CODE REVIEW

**Comment by LukeTowers** [comment]
This pull request has been made to the wrong branch. Please review [the contributing guidelines](https://github.com/octobercms/october/blob/master/CONTRIBUTING.md#pull-requests) as all PRs need to be made to the develop branch.

I'll fix it for you this time, but please ensure you make any future PRs to the develop branch, not the master branch.

**Comment by LukeTowers** [comment]
@cx-emerge You need to post a detailed description of what the issue is and why this is the appropriate fix to it.

**Comment by tschallacka** [comment]
There is indeed a logical error.
it fixes 
``` count($nameParts > 1)```
to
```count($nameParts) > 1```

making sure it's truly countable.
But regarding #3440  I'd suggest replacing it with

```
count($nameparts?:[])
```
so theres always a countable thing fed into the count function.

**Comment by LukeTowers** [comment]
@tschallacka I can see that it's a logical error, but I would like to know exactly what issue is caused by this error existing so that we can consider whether it needs a better fix or not.

**Comment by viamage** [comment]
https://github.com/octobercms/october/pull/3326 wasn't that fixed here?

**Comment by LukeTowers** [comment]
Closed in favour of #3326

**Pull request closed without merging**
